apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8007'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: creator-workflow-service
    environment: staging
    service-type: business-service
  name: creator-workflow-service
  namespace: ainflue-staging
spec:
  ports:
  - name: http
    port: 8007
    protocol: TCP
    targetPort: 8007
  selector:
    app: creator-workflow-service
  type: ClusterIP
