apiVersion: v1
kind: Namespace
metadata:
  annotations:
    contact: mlaiel@live.de
    description: Ainflue microservices - staging
  labels:
    environment: staging
    managed-by: enterprise-orchestrator
    project: ainflue
  name: ainflue-staging
spec: {}
