apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8008'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: platform-sync-service
    environment: staging
    service-type: platform-service
  name: platform-sync-service
  namespace: ainflue-staging
spec:
  ports:
  - name: http
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: platform-sync-service
  type: ClusterIP
