"""Data Governance Reporting and Analytics System

Advanced reporting engine for governance metrics, compliance reports,
audit trails, and analytical insights across all governance domains.

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright: Fahed Mlaiel - All rights reserved
License: Proprietary - Unauthorized use prohibited

WARNING: This code is the exclusive intellectual property of Fahed Mlaiel.
Any unauthorized use, reproduction, or distribution without explicit written
permission is strictly prohibited and will result in legal action.
Contact: mlaiel@live.de
"""
import logging
import json
import csv
import io
from typing import Dict, List, Optional, Any, Tuple, Union
from datetime import datetime, timedelta
from enum import Enum
from dataclasses import dataclass, field, asdict
from abc import ABC, abstractmethod
import statistics

from ...core.base import BaseManager
from ...core.exceptions import ReportingError, ValidationError
from .policies import PolicyManager, PolicyViolation
from .compliance import ComplianceManager, ComplianceAssessment
from .privacy import PrivacyManager, PIIDetectionResult
from .access import AccessController
from .monitoring import GovernanceMonitor, GovernanceAlert, MetricType


class ReportType(Enum):
    """Types of governance reports"""    COMPLIANCE_SUMMARY = "compliance_summary"
    POLICY_VIOLATIONS = "policy_violations"
    PRIVACY_ASSESSMENT = "privacy_assessment"
    ACCESS_AUDIT = "access_audit"
    DATA_QUALITY = "data_quality"
    GOVERNANCE_DASHBOARD = "governance_dashboard"
    REGULATORY_COMPLIANCE = "regulatory_compliance"
    TREND_ANALYSIS = "trend_analysis"
    EXECUTIVE_SUMMARY = "executive_summary"


class ReportFormat(Enum):
    """Report output formats"""    JSON = "json"
    CSV = "csv"
    HTML = "html"
    PDF = "pdf"
    EXCEL = "excel"


class TimeAggregation(Enum):
    """Time aggregation periods"""    HOURLY = "hourly"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"


@dataclass
class ReportRequest:
    """Report generation request"""    request_id: str
    report_type: ReportType
    format: ReportFormat
    time_range: Tuple[datetime, datetime]
    filters: Dict[str, Any] = field(default_factory=dict)
    aggregation: Optional[TimeAggregation] = None
    requested_by: str = "system"
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class ReportMetadata:
    """Report metadata"""    report_id: str
    request: ReportRequest
    generated_at: datetime
    data_sources: List[str]
    record_count: int
    file_size: int
    checksum: str


@dataclass
class GovernanceMetrics:
    """Aggregated governance metrics"""    period_start: datetime
    period_end: datetime
    total_policies: int
    active_violations: int
    resolved_violations: int
    compliance_score: float
    privacy_risk_score: float
    access_violations: int
    data_quality_score: float
    alerts_generated: int
    alerts_resolved: int


@dataclass
class ComplianceReport:
    """Compliance assessment report"""    assessment_period: Tuple[datetime, datetime]
    overall_score: float
    framework_scores: Dict[str, float]
    violations_by_type: Dict[str, int]
    improvement_recommendations: List[str]
    compliance_trends: List[float]
    risk_areas: List[str]


class BaseReportGenerator(ABC):
    """Base class for report generators"""    
    @abstractmethod
    async def generate(
        self,
        request: ReportRequest,
        data_sources: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate report based on request"""        logger.warning(f"generate method not implemented in {self.__class__.__name__}")
        
        # Create basic report content
        report_content = f"Default report generated by {self.__class__.__name__}\n"
        report_content += f"Request ID: {request.request_id}\n"
        report_content += f"Generated at: {datetime.utcnow().isoformat()}\n"
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"default_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=list(data_sources.keys()),
            record_count=len(data_sources),
            file_size=len(report_content.encode()),
            checksum="default_checksum"
        )
        
        return report_content.encode(), metadata
    
    @abstractmethod
    def get_supported_formats(self) -> List[ReportFormat]:
        """Get supported output formats"""        logger.warning(f"get_supported_formats method not implemented in {self.__class__.__name__}")
        return [ReportFormat.JSON, ReportFormat.CSV]  # Return basic supported formats


class ComplianceReportGenerator(BaseReportGenerator):
    """Generates compliance assessment reports"""    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.logger = logging.getLogger(__name__)
    
    async def generate(
        self,
        request: ReportRequest,
        data_sources: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate compliance report"""        try:
            compliance_manager = data_sources.get("compliance_manager")
            if not compliance_manager:
                raise ReportingError("Compliance manager not available")
            
            # Collect compliance data
            assessments = await self._collect_compliance_data(
                compliance_manager, request.time_range
            )
            
            # Generate report based on format
            if request.format == ReportFormat.JSON:
                report_data, metadata = await self._generate_json_report(
                    request, assessments
                )
            elif request.format == ReportFormat.CSV:
                report_data, metadata = await self._generate_csv_report(
                    request, assessments
                )
            elif request.format == ReportFormat.HTML:
                report_data, metadata = await self._generate_html_report(
                    request, assessments
                )
            else:
                raise ReportingError(f"Unsupported format: {request.format}")
            
            return report_data, metadata
            
        except Exception as e:
            self.logger.error(f"Error generating compliance report: {e}")
            raise ReportingError(f"Compliance report generation failed: {e}")
    
    def get_supported_formats(self) -> List[ReportFormat]:
        return [ReportFormat.JSON, ReportFormat.CSV, ReportFormat.HTML]
    
    async def _collect_compliance_data(
        self,
        compliance_manager: ComplianceManager,
        time_range: Tuple[datetime, datetime]
    ) -> List[ComplianceAssessment]:
        """Collect compliance assessment data for time range"""        # This would interface with the compliance manager's data storage
        # For now, return mock data structure
        start_time, end_time = time_range
        
        # Get all assessments in time range
        assessments = await compliance_manager.get_compliance_assessments(
            start_time=start_time,
            end_time=end_time
        )
        
        return assessments
    
    async def _generate_json_report(
        self,
        request: ReportRequest,
        assessments: List[ComplianceAssessment]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate JSON format compliance report"""        # Calculate summary metrics
        total_assessments = len(assessments)
        if total_assessments == 0:
            overall_score = 0.0
            framework_scores = {}
        else:
            overall_score = statistics.mean([a.overall_score for a in assessments])
            framework_scores = {
                "gdpr": statistics.mean([a.gdpr_score for a in assessments]),
                "ccpa": statistics.mean([a.ccpa_score for a in assessments]),
                "dmca": statistics.mean([a.dmca_score for a in assessments])
            }
        
        # Create report structure
        report_data = {
            "report_metadata": {
                "report_type": request.report_type.value,
                "generated_at": datetime.utcnow().isoformat(),
                "time_range": {
                    "start": request.time_range[0].isoformat(),
                    "end": request.time_range[1].isoformat()
                },
                "total_assessments": total_assessments
            },
            "summary": {
                "overall_compliance_score": overall_score,
                "framework_scores": framework_scores
            },
            "assessments": [asdict(assessment) for assessment in assessments]
        }
        
        # Convert to JSON bytes
        json_data = json.dumps(report_data, indent=2, default=str)
        report_bytes = json_data.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"comp_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=["compliance_manager"],
            record_count=total_assessments,
            file_size=len(report_bytes),
            checksum=str(hash(json_data))
        )
        
        return report_bytes, metadata
    
    async def _generate_csv_report(
        self,
        request: ReportRequest,
        assessments: List[ComplianceAssessment]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate CSV format compliance report"""        output = io.StringIO()
        writer = csv.writer(output)
        
        # Write header
        headers = [
            "Assessment ID", "Content ID", "Framework", "Overall Score",
            "GDPR Score", "CCPA Score", "DMCA Score", "Risk Level",
            "Issues Count", "Assessed At"
        ]
        writer.writerow(headers)
        
        # Write data rows
        for assessment in assessments:
            writer.writerow([
                assessment.assessment_id,
                assessment.content_id,
                assessment.framework,
                assessment.overall_score,
                assessment.gdpr_score,
                assessment.ccpa_score,
                assessment.dmca_score,
                assessment.risk_level,
                len(assessment.issues),
                assessment.assessed_at.isoformat()
            ])
        
        # Convert to bytes
        csv_data = output.getvalue()
        report_bytes = csv_data.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"comp_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=["compliance_manager"],
            record_count=len(assessments),
            file_size=len(report_bytes),
            checksum=str(hash(csv_data))
        )
        
        return report_bytes, metadata
    
    async def _generate_html_report(
        self,
        request: ReportRequest,
        assessments: List[ComplianceAssessment]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate HTML format compliance report"""        # Calculate summary metrics
        total_assessments = len(assessments)
        overall_score = statistics.mean([a.overall_score for a in assessments]) if assessments else 0.0
        
        # Generate HTML content
        html_content = f"""        <!DOCTYPE html>
        <html>
        <head>
            <title>Compliance Assessment Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f0f0f0; padding: 20px; border-radius: 5px; }}
                .summary {{ margin: 20px 0; }}
                .metric {{ display: inline-block; margin: 10px; padding: 10px; border: 1px solid #ccc; }}
                table {{ border-collapse: collapse; width: 100%; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Compliance Assessment Report</h1>
                <p>Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
                <p>Period: {request.time_range[0].strftime('%Y-%m-%d')} to {request.time_range[1].strftime('%Y-%m-%d')}</p>
            </div>
            
            <div class="summary">
                <h2>Summary</h2>
                <div class="metric">
                    <strong>Total Assessments:</strong> {total_assessments}
                </div>
                <div class="metric">
                    <strong>Overall Score:</strong> {overall_score:.2f}%
                </div>
            </div>
            
            <h2>Assessment Details</h2>
            <table>
                <tr>
                    <th>Assessment ID</th>
                    <th>Content ID</th>
                    <th>Framework</th>
                    <th>Overall Score</th>
                    <th>Risk Level</th>
                    <th>Issues</th>
                    <th>Date</th>
                </tr>
        """        
        # Add assessment rows
        for assessment in assessments:
            html_content += f"""                <tr>
                    <td>{assessment.assessment_id}</td>
                    <td>{assessment.content_id}</td>
                    <td>{assessment.framework}</td>
                    <td>{assessment.overall_score:.2f}%</td>
                    <td>{assessment.risk_level}</td>
                    <td>{len(assessment.issues)}</td>
                    <td>{assessment.assessed_at.strftime('%Y-%m-%d %H:%M')}</td>
                </tr>
            """        
        html_content += """            </table>
        </body>
        </html>
        """        
        # Convert to bytes
        report_bytes = html_content.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"comp_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=["compliance_manager"],
            record_count=len(assessments),
            file_size=len(report_bytes),
            checksum=str(hash(html_content))
        )
        
        return report_bytes, metadata


class PolicyViolationReportGenerator(BaseReportGenerator):
    """Generates policy violation reports"""    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.logger = logging.getLogger(__name__)
    
    async def generate(
        self,
        request: ReportRequest,
        data_sources: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate policy violation report"""        try:
            policy_manager = data_sources.get("policy_manager")
            if not policy_manager:
                raise ReportingError("Policy manager not available")
            
            # Collect violation data
            violations = await self._collect_violation_data(
                policy_manager, request.time_range
            )
            
            # Generate report based on format
            if request.format == ReportFormat.JSON:
                report_data, metadata = await self._generate_json_report(
                    request, violations
                )
            elif request.format == ReportFormat.CSV:
                report_data, metadata = await self._generate_csv_report(
                    request, violations
                )
            else:
                raise ReportingError(f"Unsupported format: {request.format}")
            
            return report_data, metadata
            
        except Exception as e:
            self.logger.error(f"Error generating policy violation report: {e}")
            raise ReportingError(f"Policy violation report generation failed: {e}")
    
    def get_supported_formats(self) -> List[ReportFormat]:
        return [ReportFormat.JSON, ReportFormat.CSV]
    
    async def _collect_violation_data(
        self,
        policy_manager: PolicyManager,
        time_range: Tuple[datetime, datetime]
    ) -> List[PolicyViolation]:
        """Collect policy violation data for time range"""        start_time, end_time = time_range
        
        # Get all violations in time range
        violations = await policy_manager.get_policy_violations(
            start_time=start_time,
            end_time=end_time
        )
        
        return violations
    
    async def _generate_json_report(
        self,
        request: ReportRequest,
        violations: List[PolicyViolation]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate JSON format violation report"""        # Calculate summary metrics
        total_violations = len(violations)
        resolved_violations = len([v for v in violations if v.resolved])
        
        # Group by violation type
        violations_by_type = {}
        for violation in violations:
            vtype = violation.violation_type
            if vtype not in violations_by_type:
                violations_by_type[vtype] = 0
            violations_by_type[vtype] += 1
        
        # Create report structure
        report_data = {
            "report_metadata": {
                "report_type": request.report_type.value,
                "generated_at": datetime.utcnow().isoformat(),
                "time_range": {
                    "start": request.time_range[0].isoformat(),
                    "end": request.time_range[1].isoformat()
                },
                "total_violations": total_violations
            },
            "summary": {
                "total_violations": total_violations,
                "resolved_violations": resolved_violations,
                "pending_violations": total_violations - resolved_violations,
                "violations_by_type": violations_by_type
            },
            "violations": [asdict(violation) for violation in violations]
        }
        
        # Convert to JSON bytes
        json_data = json.dumps(report_data, indent=2, default=str)
        report_bytes = json_data.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"viol_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=["policy_manager"],
            record_count=total_violations,
            file_size=len(report_bytes),
            checksum=str(hash(json_data))
        )
        
        return report_bytes, metadata
    
    async def _generate_csv_report(
        self,
        request: ReportRequest,
        violations: List[PolicyViolation]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate CSV format violation report"""        output = io.StringIO()
        writer = csv.writer(output)
        
        # Write header
        headers = [
            "Violation ID", "Policy ID", "Content ID", "Violation Type",
            "Severity", "Description", "Detected At", "Resolved",
            "Resolved At", "Auto Resolved"
        ]
        writer.writerow(headers)
        
        # Write data rows
        for violation in violations:
            writer.writerow([
                violation.violation_id,
                violation.policy_id,
                violation.content_id,
                violation.violation_type,
                violation.severity,
                violation.description,
                violation.detected_at.isoformat(),
                violation.resolved,
                violation.resolved_at.isoformat() if violation.resolved_at else "",
                violation.auto_resolved
            ])
        
        # Convert to bytes
        csv_data = output.getvalue()
        report_bytes = csv_data.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"viol_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=["policy_manager"],
            record_count=len(violations),
            file_size=len(report_bytes),
            checksum=str(hash(csv_data))
        )
        
        return report_bytes, metadata


class ExecutiveSummaryGenerator(BaseReportGenerator):
    """Generates executive summary reports"""    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.logger = logging.getLogger(__name__)
    
    async def generate(
        self,
        request: ReportRequest,
        data_sources: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate executive summary report"""        try:
            # Collect data from all sources
            summary_data = await self._collect_summary_data(data_sources, request.time_range)
            
            # Generate report based on format
            if request.format == ReportFormat.JSON:
                report_data, metadata = await self._generate_json_summary(
                    request, summary_data
                )
            elif request.format == ReportFormat.HTML:
                report_data, metadata = await self._generate_html_summary(
                    request, summary_data
                )
            else:
                raise ReportingError(f"Unsupported format: {request.format}")
            
            return report_data, metadata
            
        except Exception as e:
            self.logger.error(f"Error generating executive summary: {e}")
            raise ReportingError(f"Executive summary generation failed: {e}")
    
    def get_supported_formats(self) -> List[ReportFormat]:
        return [ReportFormat.JSON, ReportFormat.HTML]
    
    async def _collect_summary_data(
        self,
        data_sources: Dict[str, Any],
        time_range: Tuple[datetime, datetime]
    ) -> Dict[str, Any]:
        """Collect summary data from all governance components"""        summary = {
            "governance_overview": {},
            "compliance_status": {},
            "privacy_metrics": {},
            "access_control": {},
            "key_findings": [],
            "recommendations": []
        }
        
        # Policy and violations summary
        policy_manager = data_sources.get("policy_manager")
        if policy_manager:
            violations = await policy_manager.get_policy_violations()
            summary["governance_overview"] = {
                "total_policies": len(getattr(policy_manager, 'policies', {})),
                "total_violations": len(violations),
                "active_violations": len([v for v in violations if not v.resolved]),
                "violation_resolution_rate": (
                    len([v for v in violations if v.resolved]) / len(violations) * 100
                    if violations else 100
                )
            }
        
        # Compliance summary
        compliance_manager = data_sources.get("compliance_manager")
        if compliance_manager:
            metrics = await compliance_manager.get_metrics()
            summary["compliance_status"] = {
                "overall_score": metrics.get("overall_compliance_score", 0),
                "gdpr_score": metrics.get("gdpr_compliance_score", 0),
                "ccpa_score": metrics.get("ccpa_compliance_score", 0),
                "dmca_score": metrics.get("dmca_compliance_score", 0),
                "total_assessments": metrics.get("total_assessments", 0)
            }
        
        # Privacy summary
        privacy_manager = data_sources.get("privacy_manager")
        if privacy_manager:
            metrics = await privacy_manager.get_metrics()
            summary["privacy_metrics"] = {
                "total_scans": metrics.get("total_scans", 0),
                "pii_detection_rate": metrics.get("pii_detection_rate", 0),
                "anonymizations_performed": metrics.get("anonymizations_performed", 0),
                "privacy_violations": metrics.get("privacy_violations", 0)
            }
        
        # Access control summary
        access_controller = data_sources.get("access_controller")
        if access_controller:
            metrics = await access_controller.get_metrics()
            summary["access_control"] = {
                "total_requests": metrics.get("total_requests", 0),
                "access_granted_rate": (
                    metrics.get("access_granted_count", 0) / 
                    max(metrics.get("total_requests", 1), 1) * 100
                ),
                "access_violations": metrics.get("access_denied_count", 0)
            }
        
        # Generate key findings and recommendations
        summary["key_findings"] = await self._generate_key_findings(summary)
        summary["recommendations"] = await self._generate_recommendations(summary)
        
        return summary
    
    async def _generate_key_findings(self, summary: Dict[str, Any]) -> List[str]:
        """Generate key findings from summary data"""        findings = []
        
        # Governance findings
        gov = summary.get("governance_overview", {})
        if gov.get("active_violations", 0) > 10:
            findings.append(f"High number of active policy violations: {gov['active_violations']}")
        
        # Compliance findings
        comp = summary.get("compliance_status", {})
        if comp.get("overall_score", 100) < 80:
            findings.append(f"Compliance score below target: {comp['overall_score']:.1f}%")
        
        # Privacy findings
        priv = summary.get("privacy_metrics", {})
        if priv.get("pii_detection_rate", 0) > 20:
            findings.append(f"High PII detection rate: {priv['pii_detection_rate']:.1f}%")
        
        # Access control findings
        access = summary.get("access_control", {})
        if access.get("access_granted_rate", 100) < 90:
            findings.append(f"Low access grant rate: {access['access_granted_rate']:.1f}%")
        
        return findings
    
    async def _generate_recommendations(self, summary: Dict[str, Any]) -> List[str]:
        """Generate recommendations from summary data"""        recommendations = []
        
        # Based on violations
        gov = summary.get("governance_overview", {})
        if gov.get("active_violations", 0) > 5:
            recommendations.append("Review and update data governance policies")
            recommendations.append("Implement automated policy enforcement")
        
        # Based on compliance
        comp = summary.get("compliance_status", {})
        if comp.get("overall_score", 100) < 85:
            recommendations.append("Enhance compliance monitoring and reporting")
            recommendations.append("Provide additional staff training on regulatory requirements")
        
        # Based on privacy
        priv = summary.get("privacy_metrics", {})
        if priv.get("pii_detection_rate", 0) > 15:
            recommendations.append("Implement stronger PII detection and anonymization")
            recommendations.append("Review data collection and storage practices")
        
        return recommendations
    
    async def _generate_json_summary(
        self,
        request: ReportRequest,
        summary_data: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate JSON format executive summary"""        report_data = {
            "executive_summary": {
                "report_metadata": {
                    "report_type": request.report_type.value,
                    "generated_at": datetime.utcnow().isoformat(),
                    "time_range": {
                        "start": request.time_range[0].isoformat(),
                        "end": request.time_range[1].isoformat()
                    }
                },
                **summary_data
            }
        }
        
        # Convert to JSON bytes
        json_data = json.dumps(report_data, indent=2, default=str)
        report_bytes = json_data.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"exec_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=list(summary_data.keys()),
            record_count=1,
            file_size=len(report_bytes),
            checksum=str(hash(json_data))
        )
        
        return report_bytes, metadata
    
    async def _generate_html_summary(
        self,
        request: ReportRequest,
        summary_data: Dict[str, Any]
    ) -> Tuple[bytes, ReportMetadata]:
        """Generate HTML format executive summary"""        # Generate comprehensive HTML report
        html_content = f"""        <!DOCTYPE html>
        <html>
        <head>
            <title>Executive Governance Summary</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #2c3e50; color: white; padding: 20px; border-radius: 5px; }}
                .section {{ margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }}
                .metric {{ display: inline-block; margin: 10px; padding: 15px; background-color: #f8f9fa; border-radius: 5px; }}
                .findings {{ background-color: #fff3cd; padding: 15px; border-radius: 5px; }}
                .recommendations {{ background-color: #d1ecf1; padding: 15px; border-radius: 5px; }}
                ul {{ margin: 10px 0; }}
                .score {{ font-size: 24px; font-weight: bold; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Data Governance Executive Summary</h1>
                <p>Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
                <p>Reporting Period: {request.time_range[0].strftime('%Y-%m-%d')} to {request.time_range[1].strftime('%Y-%m-%d')}</p>
            </div>
        """        
        # Governance Overview Section
        gov = summary_data.get("governance_overview", {})
        html_content += f"""            <div class="section">
                <h2>Governance Overview</h2>
                <div class="metric">
                    <strong>Total Policies:</strong><br>
                    <span class="score">{gov.get('total_policies', 0)}</span>
                </div>
                <div class="metric">
                    <strong>Active Violations:</strong><br>
                    <span class="score">{gov.get('active_violations', 0)}</span>
                </div>
                <div class="metric">
                    <strong>Resolution Rate:</strong><br>
                    <span class="score">{gov.get('violation_resolution_rate', 0):.1f}%</span>
                </div>
            </div>
        """        
        # Compliance Status Section
        comp = summary_data.get("compliance_status", {})
        html_content += f"""            <div class="section">
                <h2>Compliance Status</h2>
                <div class="metric">
                    <strong>Overall Score:</strong><br>
                    <span class="score">{comp.get('overall_score', 0):.1f}%</span>
                </div>
                <div class="metric">
                    <strong>GDPR Score:</strong><br>
                    <span class="score">{comp.get('gdpr_score', 0):.1f}%</span>
                </div>
                <div class="metric">
                    <strong>CCPA Score:</strong><br>
                    <span class="score">{comp.get('ccpa_score', 0):.1f}%</span>
                </div>
                <div class="metric">
                    <strong>DMCA Score:</strong><br>
                    <span class="score">{comp.get('dmca_score', 0):.1f}%</span>
                </div>
            </div>
        """        
        # Key Findings Section
        findings = summary_data.get("key_findings", [])
        html_content += """            <div class="section">
                <h2>Key Findings</h2>
                <div class="findings">
        """        if findings:
            html_content += "<ul>"
            for finding in findings:
                html_content += f"<li>{finding}</li>"
            html_content += "</ul>"
        else:
            html_content += "<p>No significant issues identified.</p>"
        
        html_content += """                </div>
            </div>
        """        
        # Recommendations Section
        recommendations = summary_data.get("recommendations", [])
        html_content += """            <div class="section">
                <h2>Recommendations</h2>
                <div class="recommendations">
        """        if recommendations:
            html_content += "<ul>"
            for rec in recommendations:
                html_content += f"<li>{rec}</li>"
            html_content += "</ul>"
        else:
            html_content += "<p>Continue current governance practices.</p>"
        
        html_content += """                </div>
            </div>
        </body>
        </html>
        """        
        # Convert to bytes
        report_bytes = html_content.encode('utf-8')
        
        # Create metadata
        metadata = ReportMetadata(
            report_id=f"exec_{request.request_id}",
            request=request,
            generated_at=datetime.utcnow(),
            data_sources=list(summary_data.keys()),
            record_count=1,
            file_size=len(report_bytes),
            checksum=str(hash(html_content))
        )
        
        return report_bytes, metadata


class GovernanceReportManager(BaseManager):
    """    Central governance reporting system
    
    Coordinates report generation across all governance domains,
    manages report requests, and provides analytical insights.
    """    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """Initialize the governance report manager"""        super().__init__(config)
        self.logger = logging.getLogger(__name__)
        
        # Initialize report generators
        self.generators = {
            ReportType.COMPLIANCE_SUMMARY: ComplianceReportGenerator(config),
            ReportType.POLICY_VIOLATIONS: PolicyViolationReportGenerator(config),
            ReportType.EXECUTIVE_SUMMARY: ExecutiveSummaryGenerator(config)
        }
        
        # Report storage
        self.report_requests: Dict[str, ReportRequest] = {}
        self.generated_reports: Dict[str, Tuple[bytes, ReportMetadata]] = {}
        
        # Component references
        self.policy_manager: Optional[PolicyManager] = None
        self.compliance_manager: Optional[ComplianceManager] = None
        self.privacy_manager: Optional[PrivacyManager] = None
        self.access_controller: Optional[AccessController] = None
        self.governance_monitor: Optional[GovernanceMonitor] = None
    
    async def initialize(self) -> None:
        """Initialize the report manager"""        try:
            self.logger.info("Governance report manager initialized successfully")
            
        except Exception as e:
            self.logger.error(f"Failed to initialize report manager: {e}")
            raise ReportingError(f"Report manager initialization failed: {e}")
    
    def set_governance_components(
        self,
        policy_manager: PolicyManager,
        compliance_manager: ComplianceManager,
        privacy_manager: PrivacyManager,
        access_controller: AccessController,
        governance_monitor: GovernanceMonitor
    ) -> None:
        """Set references to governance components"""        self.policy_manager = policy_manager
        self.compliance_manager = compliance_manager
        self.privacy_manager = privacy_manager
        self.access_controller = access_controller
        self.governance_monitor = governance_monitor
    
    async def generate_report(
        self,
        report_type: ReportType,
        format: ReportFormat,
        time_range: Tuple[datetime, datetime],
        filters: Optional[Dict[str, Any]] = None,
        requested_by: str = "system"
    ) -> Tuple[bytes, ReportMetadata]:
        """        Generate a governance report
        
        Args:
            report_type: Type of report to generate
            format: Output format
            time_range: Time range for the report
            filters: Optional filters
            requested_by: User requesting the report
            
        Returns:
            Tuple of report data and metadata
        """        try:
            # Create report request
            request = ReportRequest(
                request_id=f"req_{datetime.utcnow().timestamp()}",
                report_type=report_type,
                format=format,
                time_range=time_range,
                filters=filters or {},
                requested_by=requested_by
            )
            
            # Store request
            self.report_requests[request.request_id] = request
            
            # Get appropriate generator
            generator = self.generators.get(report_type)
            if not generator:
                raise ReportingError(f"No generator available for report type: {report_type}")
            
            # Check format support
            if format not in generator.get_supported_formats():
                raise ReportingError(f"Format {format} not supported for {report_type}")
            
            # Prepare data sources
            data_sources = {
                "policy_manager": self.policy_manager,
                "compliance_manager": self.compliance_manager,
                "privacy_manager": self.privacy_manager,
                "access_controller": self.access_controller,
                "governance_monitor": self.governance_monitor
            }
            
            # Generate report
            report_data, metadata = await generator.generate(request, data_sources)
            
            # Store generated report
            self.generated_reports[metadata.report_id] = (report_data, metadata)
            
            self.logger.info(f"Generated report {metadata.report_id} of type {report_type.value}")
            return report_data, metadata
            
        except Exception as e:
            self.logger.error(f"Error generating report: {e}")
            raise ReportingError(f"Report generation failed: {e}")
    
    async def get_available_reports(self) -> List[ReportType]:
        """Get list of available report types"""        return list(self.generators.keys())
    
    async def get_supported_formats(self, report_type: ReportType) -> List[ReportFormat]:
        """Get supported formats for a report type"""        generator = self.generators.get(report_type)
        if generator:
            return generator.get_supported_formats()
        return []
    
    async def get_report_history(
        self,
        report_type: Optional[ReportType] = None,
        requested_by: Optional[str] = None
    ) -> List[ReportRequest]:
        """Get report generation history"""        requests = list(self.report_requests.values())
        
        if report_type:
            requests = [r for r in requests if r.report_type == report_type]
        
        if requested_by:
            requests = [r for r in requests if r.requested_by == requested_by]
        
        return sorted(requests, key=lambda r: r.created_at, reverse=True)
    
    async def get_governance_metrics_summary(
        self,
        time_range: Tuple[datetime, datetime]
    ) -> Dict[str, Any]:
        """Get aggregated governance metrics for time period"""        try:
            summary = {}
            
            # Collect metrics from each component
            if self.policy_manager:
                violations = await self.policy_manager.get_policy_violations()
                summary["policy_metrics"] = {
                    "total_violations": len(violations),
                    "active_violations": len([v for v in violations if not v.resolved]),
                    "resolution_rate": (
                        len([v for v in violations if v.resolved]) / len(violations) * 100
                        if violations else 100
                    )
                }
            
            if self.compliance_manager:
                comp_metrics = await self.compliance_manager.get_metrics()
                summary["compliance_metrics"] = comp_metrics
            
            if self.privacy_manager:
                privacy_metrics = await self.privacy_manager.get_metrics()
                summary["privacy_metrics"] = privacy_metrics
            
            if self.access_controller:
                access_metrics = await self.access_controller.get_metrics()
                summary["access_metrics"] = access_metrics
            
            return summary
            
        except Exception as e:
            self.logger.error(f"Error collecting governance metrics: {e}")
            return {"error": f"Metrics collection failed: {e}"}
    
    async def schedule_recurring_report(
        self,
        report_type: ReportType,
        format: ReportFormat,
        schedule: str,  # cron-like schedule
        recipients: List[str]
    ) -> str:
        """Schedule a recurring report (placeholder for future implementation)"""        # This would integrate with a task scheduler
        schedule_id = f"schedule_{datetime.utcnow().timestamp()}"
        
        self.logger.info(f"Scheduled recurring report {report_type.value} with ID {schedule_id}")
        return schedule_id
