
# Security headers enforcement - Added by Security Expert
# X-Content-Type-Options: nosniff, X-Frame-Options: DENY, X-XSS-Protection: 1; mode=block
#!/usr/bin/env python3
"""
Security Monitoring System - Enterprise SIEM and SOC Platform
Real-time security monitoring with advanced analytics and automated response

Author: Fahed Mlaiel (mlaiel@live.de)
Copyright: © 2025 Fahed Mlaiel. All rights reserved.
Licensed under Enterprise Commercial License.

⚠️ LEGAL WARNING - INTELLECTUAL PROPERTY PROTECTION:
==========================================================
© 2025 Fahed Mlaiel <mlaiel@live.de>
ALL RIGHTS RESERVED

🚨 INTELLECTUAL PROPERTY PROTECTION:
- Proprietary code of Fahed Mlaiel
- Commercial use FORBIDDEN without written authorization
- Reverse engineering STRICTLY PROHIBITED
- Distribution FORBIDDEN without explicit license
- Violation = Automatic legal prosecution

🏢 ENTERPRISE USAGE:
- Enterprise license available on request
- Technical support included with license
- Maintenance and updates assured
- Technical team training provided

This module provides comprehensive security monitoring including:
- Real-time SIEM capabilities with log aggregation and correlation
- Security Operations Center (SOC) automation and orchestration
- Advanced analytics and machine learning for threat detection
- Automated incident response and alert management
- Creator economy specific monitoring patterns
"""

import asyncio
import hashlib
import json
import logging
import statistics
import time
from collections import defaultdict, deque
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Set, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum
import re
import secrets

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels"""
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MonitoringType(Enum):
    """Monitoring type enumeration"""
    NETWORK = "network"
    APPLICATION = "application"
    SYSTEM = "system"
    DATABASE = "database"
    API = "api"
    USER_BEHAVIOR = "user_behavior"
    FILE_INTEGRITY = "file_integrity"
    PERFORMANCE = "performance"
    COMPLIANCE = "compliance"


class EventType(Enum):
    """Security event types"""
    LOGIN_ATTEMPT = "login_attempt"
    LOGIN_SUCCESS = "login_success"
    LOGIN_FAILURE = "login_failure"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    DATA_ACCESS = "data_access"
    FILE_MODIFICATION = "file_modification"
    NETWORK_CONNECTION = "network_connection"
    API_CALL = "api_call"
    SYSTEM_CHANGE = "system_change"
    ERROR_EVENT = "error_event"
    SECURITY_VIOLATION = "security_violation"
    COMPLIANCE_EVENT = "compliance_event"


class AlertStatus(Enum):
    """Alert status enumeration"""
    OPEN = "open"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    SUPPRESSED = "suppressed"


class ResponseAction(Enum):
    """Automated response actions"""
    ALERT_ONLY = "alert_only"
    BLOCK_IP = "block_ip"
    DISABLE_USER = "disable_user"
    QUARANTINE_FILE = "quarantine_file"
    RESTART_SERVICE = "restart_service"
    ESCALATE = "escalate"
    CUSTOM_SCRIPT = "custom_script"


@dataclass
class SecurityEvent:
    """Security event data structure"""
    event_id: str
    event_type: EventType
    timestamp: datetime
    source: str
    severity: AlertSeverity = AlertSeverity.INFO
    user_id: Optional[str] = None
    ip_address: str = ""
    user_agent: str = ""
    resource: str = ""
    action: str = ""
    outcome: str = "success"
    details: Dict[str, Any] = field(default_factory=dict)
    raw_log: str = ""
    processed: bool = False
    correlated_events: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MonitoringRule:
    """Security monitoring rule"""
    rule_id: str
    name: str
    description: str
    monitoring_type: MonitoringType
    event_pattern: str  # Regex or query pattern
    conditions: Dict[str, Any] = field(default_factory=dict)
    threshold: Optional[int] = None
    time_window_minutes: int = 60
    severity: AlertSeverity = AlertSeverity.MEDIUM
    response_actions: List[ResponseAction] = field(default_factory=list)
    enabled: bool = True
    false_positive_threshold: float = 0.1
    last_triggered: Optional[datetime] = None
    trigger_count: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SecurityAlert:
    """Security alert generated by monitoring"""
    alert_id: str
    rule_id: str
    title: str
    description: str
    severity: AlertSeverity
    status: AlertStatus = AlertStatus.OPEN
    triggered_events: List[str] = field(default_factory=list)
    evidence: Dict[str, Any] = field(default_factory=dict)
    confidence_score: float = 1.0
    false_positive_probability: float = 0.0
    assigned_to: Optional[str] = None
    escalated: bool = False
    response_actions_taken: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    resolved_at: Optional[datetime] = None
    resolution_notes: str = ""
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Dashboard:
    """Security monitoring dashboard"""
    dashboard_id: str
    name: str
    description: str
    widgets: List[Dict[str, Any]] = field(default_factory=list)
    refresh_interval_seconds: int = 30
    permissions: Dict[str, List[str]] = field(default_factory=dict)
    created_by: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    last_accessed: Optional[datetime] = None


@dataclass
class MetricDataPoint:
    """Security metric data point"""
    metric_name: str
    timestamp: datetime
    value: float
    tags: Dict[str, str] = field(default_factory=dict)
    dimensions: Dict[str, str] = field(default_factory=dict)


@dataclass
class SIEMCorrelationRule:
    """SIEM event correlation rule"""
    rule_id: str
    name: str
    description: str
    event_patterns: List[str] = field(default_factory=list)
    correlation_window_minutes: int = 30
    min_events: int = 2
    max_events: int = 100
    correlation_fields: List[str] = field(default_factory=list)  # user_id, ip_address, etc.
    severity_escalation: bool = True
    enabled: bool = True
    detection_count: int = 0
    last_detection: Optional[datetime] = None


class SecurityMonitoringSystem:
    """
    Enterprise Security Monitoring System
    
    Provides comprehensive SIEM capabilities with real-time monitoring,
    advanced analytics, automated response, and SOC operations for
    creator economy platforms with specialized monitoring patterns.
    """

    def __init__(self):
        # Event storage and processing
        self.security_events: deque = deque(maxlen=1000000)  # Ring buffer for events
        self.event_indexes: Dict[str, Set[str]] = defaultdict(set)  # For fast lookups
        
        # Monitoring rules and alerts
        self.monitoring_rules: Dict[str, MonitoringRule] = {}
        self.correlation_rules: Dict[str, SIEMCorrelationRule] = {}
        self.active_alerts: Dict[str, SecurityAlert] = {}
        self.alert_history: List[SecurityAlert] = []
        
        # Dashboards and metrics
        self.dashboards: Dict[str, Dashboard] = {}
        self.metrics: Dict[str, List[MetricDataPoint]] = defaultdict(list)
        self.real_time_stats: Dict[str, Any] = {}
        
        # Event processors and handlers
        self.event_processors: List[Callable] = []
        self.alert_handlers: Dict[AlertSeverity, List[Callable]] = defaultdict(list)
        self.response_handlers: Dict[ResponseAction, Callable] = {}
        
        # Machine learning models for anomaly detection
        self.behavioral_models: Dict[str, Dict[str, Any]] = {}
        self.anomaly_detectors: Dict[str, Any] = {}
        
        # Performance tracking
        self.processing_metrics: Dict[str, List[float]] = {
            "event_processing_time": [],
            "alert_generation_time": [],
            "correlation_time": []
        }
        
        # Configuration
        self.config = {
            "max_events_per_second": 10000,
            "correlation_batch_size": 1000,
            "alert_retention_days": 365,
            "metric_retention_days": 90,
            "real_time_window_minutes": 5
        }
        
        # Initialize monitoring system
        self._initialize_default_rules()
        self._initialize_correlation_rules()
        self._initialize_dashboards()
        self._setup_response_handlers()
        
        # Start background tasks
        asyncio.create_task(self._event_processor_loop())
        asyncio.create_task(self._correlation_engine_loop())
        asyncio.create_task(self._metrics_collector_loop())
        
        logger.info("Security Monitoring System initialized with enterprise SIEM capabilities")

    def _initialize_default_rules(self) -> None:
        """Initialize default monitoring rules"""
        try:
            default_rules = [
                # Authentication monitoring
                MonitoringRule(
                    rule_id="failed_login_attempts",
                    name="Multiple Failed Login Attempts",
                    description="Detect multiple failed login attempts from same IP",
                    monitoring_type=MonitoringType.USER_BEHAVIOR,
                    event_pattern=r"login_failure",
                    conditions={"user_different_count": 5, "ip_same": True},
                    threshold=5,
                    time_window_minutes=10,
                    severity=AlertSeverity.HIGH,
                    response_actions=[ResponseAction.BLOCK_IP, ResponseAction.ALERT_ONLY]
                ),
                
                # Data access monitoring
                MonitoringRule(
                    rule_id="unusual_data_access",
                    name="Unusual Data Access Pattern",
                    description="Detect unusual data access patterns",
                    monitoring_type=MonitoringType.USER_BEHAVIOR,
                    event_pattern=r"data_access",
                    conditions={"volume_threshold": 1000, "time_pattern": "off_hours"},
                    threshold=100,
                    time_window_minutes=60,
                    severity=AlertSeverity.MEDIUM,
                    response_actions=[ResponseAction.ALERT_ONLY]
                ),
                
                # System integrity monitoring
                MonitoringRule(
                    rule_id="critical_file_modification",
                    name="Critical File Modification",
                    description="Detect unauthorized modification of critical files",
                    monitoring_type=MonitoringType.FILE_INTEGRITY,
                    event_pattern=r"file_modification",
                    conditions={"file_criticality": "high", "user_authorized": False},
                    threshold=1,
                    time_window_minutes=1,
                    severity=AlertSeverity.CRITICAL,
                    response_actions=[ResponseAction.QUARANTINE_FILE, ResponseAction.ESCALATE]
                ),
                
                # API abuse monitoring
                MonitoringRule(
                    rule_id="api_rate_limit_exceeded",
                    name="API Rate Limit Exceeded",
                    description="Detect API abuse through rate limiting violations",
                    monitoring_type=MonitoringType.API,
                    event_pattern=r"api_call",
                    conditions={"rate_per_minute": 1000, "endpoint_sensitive": True},
                    threshold=1000,
                    time_window_minutes=1,
                    severity=AlertSeverity.HIGH,
                    response_actions=[ResponseAction.BLOCK_IP]
                ),
                
                # Creator platform specific rules
                MonitoringRule(
                    rule_id="content_mass_download",
                    name="Mass Content Download",
                    description="Detect potential content theft through mass downloads",
                    monitoring_type=MonitoringType.USER_BEHAVIOR,
                    event_pattern=r"content_download",
                    conditions={"download_count": 50, "unique_creators": 10},
                    threshold=50,
                    time_window_minutes=30,
                    severity=AlertSeverity.HIGH,
                    response_actions=[ResponseAction.DISABLE_USER, ResponseAction.ALERT_ONLY]
                ),
                
                MonitoringRule(
                    rule_id="revenue_manipulation_attempt",
                    name="Revenue Manipulation Attempt",
                    description="Detect attempts to manipulate creator revenue calculations",
                    monitoring_type=MonitoringType.APPLICATION,
                    event_pattern=r"revenue_calculation",
                    conditions={"calculation_anomaly": True, "deviation_percentage": 20},
                    threshold=1,
                    time_window_minutes=5,
                    severity=AlertSeverity.CRITICAL,
                    response_actions=[ResponseAction.ESCALATE, ResponseAction.CUSTOM_SCRIPT]
                ),
                
                # Network monitoring
                MonitoringRule(
                    rule_id="suspicious_network_connection",
                    name="Suspicious Network Connection",
                    description="Detect connections to known malicious IPs",
                    monitoring_type=MonitoringType.NETWORK,
                    event_pattern=r"network_connection",
                    conditions={"destination_reputation": "malicious", "protocol": "any"},
                    threshold=1,
                    time_window_minutes=1,
                    severity=AlertSeverity.CRITICAL,
                    response_actions=[ResponseAction.BLOCK_IP, ResponseAction.ESCALATE]
                ),
                
                # Privilege escalation monitoring
                MonitoringRule(
                    rule_id="privilege_escalation_attempt",
                    name="Privilege Escalation Attempt",
                    description="Detect attempts to escalate privileges",
                    monitoring_type=MonitoringType.SYSTEM,
                    event_pattern=r"privilege_escalation",
                    conditions={"success": False, "user_role": "normal"},
                    threshold=3,
                    time_window_minutes=15,
                    severity=AlertSeverity.HIGH,
                    response_actions=[ResponseAction.DISABLE_USER, ResponseAction.ALERT_ONLY]
                ),
                
                # Compliance monitoring
                MonitoringRule(
                    rule_id="gdpr_data_access_violation",
                    name="GDPR Data Access Violation",
                    description="Detect potential GDPR compliance violations",
                    monitoring_type=MonitoringType.COMPLIANCE,
                    event_pattern=r"personal_data_access",
                    conditions={"consent_status": "withdrawn", "data_type": "personal"},
                    threshold=1,
                    time_window_minutes=1,
                    severity=AlertSeverity.HIGH,
                    response_actions=[ResponseAction.ALERT_ONLY, ResponseAction.ESCALATE]
                )
            ]
            
            for rule in default_rules:
                self.monitoring_rules[rule.rule_id] = rule
            
            logger.info(f"Initialized {len(default_rules)} default monitoring rules")
            
        except Exception as e:
            logger.error(f"Failed to initialize default monitoring rules: {e}")

    def _initialize_correlation_rules(self) -> None:
        """Initialize SIEM correlation rules"""
        try:
            correlation_rules = [
                SIEMCorrelationRule(
                    rule_id="credential_stuffing_pattern",
                    name="Credential Stuffing Attack Pattern",
                    description="Correlate multiple failed logins across different users from same IP",
                    event_patterns=["login_failure"],
                    correlation_window_minutes=15,
                    min_events=20,
                    correlation_fields=["ip_address"],
                    severity_escalation=True
                ),
                
                SIEMCorrelationRule(
                    rule_id="lateral_movement_pattern",
                    name="Lateral Movement Pattern",
                    description="Correlate privilege escalation with data access events",
                    event_patterns=["privilege_escalation", "data_access"],
                    correlation_window_minutes=60,
                    min_events=2,
                    correlation_fields=["user_id"],
                    severity_escalation=True
                ),
                
                SIEMCorrelationRule(
                    rule_id="data_exfiltration_pattern",
                    name="Data Exfiltration Pattern",
                    description="Correlate unusual data access with network connections",
                    event_patterns=["data_access", "network_connection"],
                    correlation_window_minutes=30,
                    min_events=2,
                    correlation_fields=["user_id", "ip_address"],
                    severity_escalation=True
                ),
                
                SIEMCorrelationRule(
                    rule_id="apt_behavior_pattern",
                    name="APT Behavior Pattern",
                    description="Correlate multiple attack stages indicating APT activity",
                    event_patterns=["login_success", "privilege_escalation", "file_modification", "network_connection"],
                    correlation_window_minutes=240,
                    min_events=3,
                    correlation_fields=["user_id"],
                    severity_escalation=True
                )
            ]
            
            for rule in correlation_rules:
                self.correlation_rules[rule.rule_id] = rule
            
            logger.info(f"Initialized {len(correlation_rules)} correlation rules")
            
        except Exception as e:
            logger.error(f"Failed to initialize correlation rules: {e}")

    def _initialize_dashboards(self) -> None:
        """Initialize default security dashboards"""
        try:
            # Main SOC dashboard
            soc_dashboard = Dashboard(
                dashboard_id="soc_main",
                name="SOC Main Dashboard",
                description="Primary security operations center dashboard",
                widgets=[
                    {
                        "type": "alert_summary",
                        "title": "Active Alerts by Severity",
                        "size": "medium",
                        "refresh_interval": 30
                    },
                    {
                        "type": "event_volume",
                        "title": "Security Events (Last 24h)",
                        "size": "large",
                        "refresh_interval": 60
                    },
                    {
                        "type": "top_threats",
                        "title": "Top Threat Types",
                        "size": "medium",
                        "refresh_interval": 300
                    },
                    {
                        "type": "response_metrics",
                        "title": "Incident Response Metrics",
                        "size": "medium",
                        "refresh_interval": 300
                    }
                ]
            )
            
            # Creator platform dashboard
            creator_dashboard = Dashboard(
                dashboard_id="creator_security",
                name="Creator Platform Security",
                description="Security monitoring for creator economy features",
                widgets=[
                    {
                        "type": "content_protection",
                        "title": "Content Protection Status",
                        "size": "large",
                        "refresh_interval": 60
                    },
                    {
                        "type": "revenue_security",
                        "title": "Revenue Security Monitoring",
                        "size": "medium",
                        "refresh_interval": 120
                    },
                    {
                        "type": "creator_threats",
                        "title": "Creator-Specific Threats",
                        "size": "medium",
                        "refresh_interval": 300
                    }
                ]
            )
            
            # Compliance dashboard
            compliance_dashboard = Dashboard(
                dashboard_id="compliance_monitoring",
                name="Compliance Monitoring",
                description="Regulatory compliance and audit monitoring",
                widgets=[
                    {
                        "type": "gdpr_compliance",
                        "title": "GDPR Compliance Status",
                        "size": "medium",
                        "refresh_interval": 300
                    },
                    {
                        "type": "audit_events",
                        "title": "Audit Events",
                        "size": "large",
                        "refresh_interval": 120
                    },
                    {
                        "type": "data_protection",
                        "title": "Data Protection Metrics",
                        "size": "medium",
                        "refresh_interval": 300
                    }
                ]
            )
            
            dashboards = [soc_dashboard, creator_dashboard, compliance_dashboard]
            for dashboard in dashboards:
                self.dashboards[dashboard.dashboard_id] = dashboard
            
            logger.info(f"Initialized {len(dashboards)} security dashboards")
            
        except Exception as e:
            logger.error(f"Failed to initialize dashboards: {e}")

    def _setup_response_handlers(self) -> None:
        """Setup automated response handlers"""
        try:
            self.response_handlers = {
                ResponseAction.BLOCK_IP: self._handle_block_ip,
                ResponseAction.DISABLE_USER: self._handle_disable_user,
                ResponseAction.QUARANTINE_FILE: self._handle_quarantine_file,
                ResponseAction.RESTART_SERVICE: self._handle_restart_service,
                ResponseAction.ESCALATE: self._handle_escalate,
                ResponseAction.CUSTOM_SCRIPT: self._handle_custom_script
            }
            
            logger.info("Response handlers configured")
            
        except Exception as e:
            logger.error(f"Failed to setup response handlers: {e}")

    async def ingest_security_event(self, event: SecurityEvent) -> str:
        """Ingest security event into monitoring system"""
        try:
            if not event.event_id:
                event.event_id = f"event_{int(time.time())}_{secrets.token_hex(8)}"
            
            # Add to event storage
            self.security_events.append(event)
            
            # Update indexes for fast lookups
            self._update_event_indexes(event)
            
            # Update real-time statistics
            await self._update_real_time_stats(event)
            
            # Trigger event processing
            await self._process_security_event(event)
            
            logger.debug(f"Security event {event.event_id} ingested successfully")
            return event.event_id
            
        except Exception as e:
            logger.error(f"Failed to ingest security event: {e}")
            raise

    async def _process_security_event(self, event: SecurityEvent) -> None:
        """Process security event against monitoring rules"""
        try:
            start_time = time.time()
            
            # Check against monitoring rules
            triggered_rules = []
            for rule in self.monitoring_rules.values():
                if rule.enabled and await self._check_rule_conditions(rule, event):
                    triggered_rules.append(rule)
                    await self._handle_rule_trigger(rule, event)
            
            # Run custom event processors
            for processor in self.event_processors:
                try:
                    await processor(event)
                except Exception as e:
                    logger.error(f"Event processor failed: {e}")
            
            # Mark event as processed
            event.processed = True
            
            # Update performance metrics
            processing_time = (time.time() - start_time) * 1000
            self.processing_metrics["event_processing_time"].append(processing_time)
            
        except Exception as e:
            logger.error(f"Failed to process security event: {e}")

    async def _check_rule_conditions(self, rule: MonitoringRule, event: SecurityEvent) -> bool:
        """Check if event matches rule conditions"""
        try:
            # Check event pattern
            if not re.search(rule.event_pattern, event.event_type.value):
                return False
            
            # Check time window if threshold is set
            if rule.threshold and rule.threshold > 1:
                matching_events = await self._get_matching_events(rule, event)
                if len(matching_events) < rule.threshold:
                    return False
            
            # Check specific conditions
            for condition, value in rule.conditions.items():
                if not await self._evaluate_condition(condition, value, event):
                    return False
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to check rule conditions: {e}")
            return False

    async def _evaluate_condition(self, condition: str, expected_value: Any, event: SecurityEvent) -> bool:
        """Evaluate specific rule condition"""
        try:
            if condition == "user_different_count":
                # Count different users in time window
                time_threshold = datetime.utcnow() - timedelta(minutes=30)
                recent_events = [e for e in self.security_events 
                               if e.timestamp > time_threshold and e.ip_address == event.ip_address]
                unique_users = set(e.user_id for e in recent_events if e.user_id)
                return len(unique_users) >= expected_value
            
            elif condition == "ip_same":
                return expected_value  # Always true for IP-based grouping
            
            elif condition == "volume_threshold":
                # Check data volume in event details
                volume = event.details.get("data_volume", 0)
                return volume >= expected_value
            
            elif condition == "time_pattern":
                if expected_value == "off_hours":
                    current_hour = event.timestamp.hour
                    return current_hour < 8 or current_hour > 18
            
            elif condition == "file_criticality":
                file_path = event.details.get("file_path", "")
                if expected_value == "high":
                    critical_paths = ["/etc/", "/bin/", "/usr/bin/", "/system/"]
                    return any(path in file_path for path in critical_paths)
            
            elif condition == "user_authorized":
                # Check if user is authorized for the action
                user_role = event.details.get("user_role", "user")
                return user_role in ["admin", "system"] if expected_value else True
            
            elif condition == "rate_per_minute":
                # Count events per minute for rate limiting
                time_threshold = datetime.utcnow() - timedelta(minutes=1)
                recent_events = [e for e in self.security_events 
                               if e.timestamp > time_threshold and e.ip_address == event.ip_address]
                return len(recent_events) >= expected_value
            
            elif condition == "endpoint_sensitive":
                endpoint = event.details.get("endpoint", "")
                sensitive_endpoints = ["/api/admin/", "/api/revenue/", "/api/analytics/"]
                return any(sens in endpoint for sens in sensitive_endpoints) if expected_value else True
            
            elif condition == "download_count":
                # Count downloads in time window
                time_threshold = datetime.utcnow() - timedelta(minutes=30)
                download_events = [e for e in self.security_events 
                                 if (e.timestamp > time_threshold and 
                                     e.user_id == event.user_id and
                                     e.event_type.value == "content_download")]
                return len(download_events) >= expected_value
            
            elif condition == "unique_creators":
                # Count unique creators accessed
                time_threshold = datetime.utcnow() - timedelta(minutes=30)
                download_events = [e for e in self.security_events 
                                 if (e.timestamp > time_threshold and 
                                     e.user_id == event.user_id and
                                     e.event_type.value == "content_download")]
                unique_creators = set(e.details.get("creator_id") for e in download_events)
                return len(unique_creators) >= expected_value
            
            elif condition == "calculation_anomaly":
                # Check for revenue calculation anomalies
                return event.details.get("anomaly_detected", False) if expected_value else True
            
            elif condition == "deviation_percentage":
                deviation = event.details.get("deviation_percentage", 0)
                return deviation >= expected_value
            
            elif condition == "destination_reputation":
                reputation = event.details.get("destination_reputation", "unknown")
                return reputation == expected_value
            
            elif condition == "success":
                success = event.details.get("success", event.outcome == "success")
                return success == expected_value
            
            elif condition == "user_role":
                user_role = event.details.get("user_role", "user")
                return user_role == expected_value
            
            elif condition == "consent_status":
                consent = event.details.get("consent_status", "active")
                return consent == expected_value
            
            elif condition == "data_type":
                data_type = event.details.get("data_type", "general")
                return data_type == expected_value
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to evaluate condition {condition}: {e}")
            return False

    async def _get_matching_events(self, rule: MonitoringRule, current_event: SecurityEvent) -> List[SecurityEvent]:
        """Get events matching rule pattern in time window"""
        try:
            time_threshold = datetime.utcnow() - timedelta(minutes=rule.time_window_minutes)
            
            matching_events = []
            for event in self.security_events:
                if (event.timestamp > time_threshold and 
                    re.search(rule.event_pattern, event.event_type.value)):
                    
                    # Additional filtering based on rule type
                    if rule.monitoring_type == MonitoringType.USER_BEHAVIOR:
                        if event.ip_address == current_event.ip_address:
                            matching_events.append(event)
                    elif rule.monitoring_type == MonitoringType.API:
                        if event.ip_address == current_event.ip_address:
                            matching_events.append(event)
                    else:
                        matching_events.append(event)
            
            return matching_events
            
        except Exception as e:
            logger.error(f"Failed to get matching events: {e}")
            return []

    async def _handle_rule_trigger(self, rule: MonitoringRule, event: SecurityEvent) -> None:
        """Handle triggered monitoring rule"""
        try:
            # Update rule statistics
            rule.last_triggered = datetime.utcnow()
            rule.trigger_count += 1
            
            # Create security alert
            alert = await self._create_security_alert(rule, event)
            
            # Execute response actions
            for action in rule.response_actions:
                try:
                    if action in self.response_handlers:
                        await self.response_handlers[action](alert, event)
                        alert.response_actions_taken.append(action.value)
                except Exception as e:
                    logger.error(f"Response action {action.value} failed: {e}")
            
            logger.warning(f"Monitoring rule {rule.rule_id} triggered: {alert.title}")
            
        except Exception as e:
            logger.error(f"Failed to handle rule trigger: {e}")

    async def _create_security_alert(self, rule: MonitoringRule, trigger_event: SecurityEvent) -> SecurityAlert:
        """Create security alert from triggered rule"""
        try:
            alert_id = f"alert_{rule.rule_id}_{int(time.time())}"
            
            # Get related events
            matching_events = await self._get_matching_events(rule, trigger_event)
            
            # Calculate confidence score
            confidence_score = await self._calculate_alert_confidence(rule, matching_events)
            
            # Calculate false positive probability
            fp_probability = await self._calculate_false_positive_probability(rule, matching_events)
            
            alert = SecurityAlert(
                alert_id=alert_id,
                rule_id=rule.rule_id,
                title=rule.name,
                description=rule.description,
                severity=rule.severity,
                triggered_events=[e.event_id for e in matching_events],
                evidence={
                    "trigger_event": trigger_event.event_id,
                    "matching_events_count": len(matching_events),
                    "time_window_minutes": rule.time_window_minutes,
                    "threshold": rule.threshold
                },
                confidence_score=confidence_score,
                false_positive_probability=fp_probability,
                tags=[rule.monitoring_type.value]
            )
            
            # Store alert
            self.active_alerts[alert_id] = alert
            
            # Trigger alert handlers
            for handler in self.alert_handlers[rule.severity]:
                try:
                    await handler(alert)
                except Exception as e:
                    logger.error(f"Alert handler failed: {e}")
            
            return alert
            
        except Exception as e:
            logger.error(f"Failed to create security alert: {e}")
            raise

    async def _calculate_alert_confidence(self, rule: MonitoringRule, events: List[SecurityEvent]) -> float:
        """Calculate confidence score for alert"""
        try:
            base_confidence = 0.8
            
            # Adjust based on number of events
            event_factor = min(1.0, len(events) / max(rule.threshold or 1, 1))
            
            # Adjust based on rule history
            if rule.trigger_count > 0:
                # Lower confidence if rule has high false positive rate
                fp_rate = rule.false_positive_threshold
                history_factor = max(0.5, 1.0 - fp_rate)
            else:
                history_factor = 1.0
            
            # Adjust based on event diversity
            unique_sources = set(e.source for e in events)
            diversity_factor = min(1.0, len(unique_sources) / max(len(events), 1))
            
            confidence = base_confidence * event_factor * history_factor * diversity_factor
            return round(min(1.0, max(0.0, confidence)), 2)
            
        except Exception as e:
            logger.error(f"Failed to calculate alert confidence: {e}")
            return 0.8

    async def _calculate_false_positive_probability(self, rule: MonitoringRule, 
                                                   events: List[SecurityEvent]) -> float:
        """Calculate false positive probability"""
        try:
            # Base false positive rate from rule configuration
            base_fp = rule.false_positive_threshold
            
            # Adjust based on event patterns
            # More diverse events = lower FP probability
            if len(events) > 1:
                unique_ips = set(e.ip_address for e in events)
                unique_users = set(e.user_id for e in events if e.user_id)
                
                diversity_score = (len(unique_ips) + len(unique_users)) / len(events)
                fp_adjustment = max(0.5, 1.0 - diversity_score)
            else:
                fp_adjustment = 1.0
            
            # Time distribution analysis
            if len(events) > 2:
                time_intervals = []
                sorted_events = sorted(events, key=lambda x: x.timestamp)
                for i in range(1, len(sorted_events)):
                    interval = (sorted_events[i].timestamp - sorted_events[i-1].timestamp).total_seconds()
                    time_intervals.append(interval)
                
                # Very regular intervals might indicate automation (lower FP)
                if time_intervals:
                    avg_interval = statistics.mean(time_intervals)
                    if avg_interval < 60:  # Less than 1 minute intervals
                        fp_adjustment *= 0.7
            
            fp_probability = base_fp * fp_adjustment
            return round(min(1.0, max(0.0, fp_probability)), 2)
            
        except Exception as e:
            logger.error(f"Failed to calculate false positive probability: {e}")
            return 0.1

    # Response handlers
    
    async def _handle_block_ip(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle IP blocking response"""
        try:
            ip_address = event.ip_address
            if ip_address:
                # In real implementation, would integrate with firewall/WAF
                logger.warning(f"Blocking IP address: {ip_address} (Alert: {alert.alert_id})")
                
                # Store blocked IP for tracking
                self.real_time_stats.setdefault("blocked_ips", set()).add(ip_address)
                
        except Exception as e:
            logger.error(f"Failed to block IP: {e}")

    async def _handle_disable_user(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle user account disabling"""
        try:
            user_id = event.user_id
            if user_id:
                # In real implementation, would integrate with user management system
                logger.warning(f"Disabling user account: {user_id} (Alert: {alert.alert_id})")
                
                # Store disabled user for tracking
                self.real_time_stats.setdefault("disabled_users", set()).add(user_id)
                
        except Exception as e:
            logger.error(f"Failed to disable user: {e}")

    async def _handle_quarantine_file(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle file quarantine response"""
        try:
            file_path = event.details.get("file_path")
            if file_path:
                # In real implementation, would move file to quarantine
                logger.warning(f"Quarantining file: {file_path} (Alert: {alert.alert_id})")
                
                # Store quarantined file for tracking
                self.real_time_stats.setdefault("quarantined_files", []).append(file_path)
                
        except Exception as e:
            logger.error(f"Failed to quarantine file: {e}")

    async def _handle_restart_service(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle service restart response"""
        try:
            service_name = event.details.get("service_name", "unknown")
            # In real implementation, would restart actual service
            logger.warning(f"Restarting service: {service_name} (Alert: {alert.alert_id})")
            
        except Exception as e:
            logger.error(f"Failed to restart service: {e}")

    async def _handle_escalate(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle alert escalation"""
        try:
            alert.escalated = True
            alert.severity = AlertSeverity.CRITICAL  # Escalate severity
            
            # In real implementation, would notify SOC team
            logger.critical(f"Alert escalated: {alert.title} (ID: {alert.alert_id})")
            
        except Exception as e:
            logger.error(f"Failed to escalate alert: {e}")

    async def _handle_custom_script(self, alert: SecurityAlert, event: SecurityEvent) -> None:
        """Handle custom script execution"""
        try:
            script_name = f"response_script_{alert.rule_id}"
            # In real implementation, would execute custom response script
            logger.warning(f"Executing custom response script: {script_name} (Alert: {alert.alert_id})")
            
        except Exception as e:
            logger.error(f"Failed to execute custom script: {e}")

    # Background processing loops
    
    async def _event_processor_loop(self) -> None:
        """Background event processing loop"""
        while True:
            try:
                # Process events in batches
                unprocessed_events = [e for e in self.security_events if not e.processed]
                
                if unprocessed_events:
                    batch_size = min(100, len(unprocessed_events))
                    batch = unprocessed_events[:batch_size]
                    
                    for event in batch:
                        await self._process_security_event(event)
                
                await asyncio.sleep(1)  # Process every second
                
            except Exception as e:
                logger.error(f"Event processor loop error: {e}")
                await asyncio.sleep(5)

    async def _correlation_engine_loop(self) -> None:
        """Background correlation engine loop"""
        while True:
            try:
                # Run correlation rules
                for rule in self.correlation_rules.values():
                    if rule.enabled:
                        await self._run_correlation_rule(rule)
                
                await asyncio.sleep(30)  # Run every 30 seconds
                
            except Exception as e:
                logger.error(f"Correlation engine error: {e}")
                await asyncio.sleep(60)

    async def _run_correlation_rule(self, rule: SIEMCorrelationRule) -> None:
        """Run SIEM correlation rule"""
        try:
            time_threshold = datetime.utcnow() - timedelta(minutes=rule.correlation_window_minutes)
            
            # Get events matching patterns
            matching_events = []
            for pattern in rule.event_patterns:
                pattern_events = [e for e in self.security_events 
                                if (e.timestamp > time_threshold and 
                                    re.search(pattern, e.event_type.value))]
                matching_events.extend(pattern_events)
            
            if len(matching_events) < rule.min_events:
                return
            
            # Group by correlation fields
            event_groups = defaultdict(list)
            for event in matching_events:
                group_key = []
                for field in rule.correlation_fields:
                    if field == "user_id":
                        group_key.append(event.user_id or "unknown")
                    elif field == "ip_address":
                        group_key.append(event.ip_address or "unknown")
                    else:
                        group_key.append(event.details.get(field, "unknown"))
                
                event_groups[tuple(group_key)].append(event)
            
            # Check for correlated patterns
            for group_key, group_events in event_groups.items():
                if len(group_events) >= rule.min_events:
                    await self._handle_correlation_detection(rule, group_events)
            
        except Exception as e:
            logger.error(f"Failed to run correlation rule {rule.rule_id}: {e}")

    async def _handle_correlation_detection(self, rule: SIEMCorrelationRule, 
                                          correlated_events: List[SecurityEvent]) -> None:
        """Handle correlation detection"""
        try:
            rule.detection_count += 1
            rule.last_detection = datetime.utcnow()
            
            # Create correlated alert
            alert_id = f"corr_alert_{rule.rule_id}_{int(time.time())}"
            
            alert = SecurityAlert(
                alert_id=alert_id,
                rule_id=rule.rule_id,
                title=f"Correlated Activity: {rule.name}",
                description=rule.description,
                severity=AlertSeverity.HIGH if rule.severity_escalation else AlertSeverity.MEDIUM,
                triggered_events=[e.event_id for e in correlated_events],
                evidence={
                    "correlation_rule": rule.rule_id,
                    "correlated_events_count": len(correlated_events),
                    "correlation_window_minutes": rule.correlation_window_minutes,
                    "event_patterns": rule.event_patterns
                },
                confidence_score=0.9,
                tags=["correlation", "complex_attack"]
            )
            
            self.active_alerts[alert_id] = alert
            
            # Update event correlation
            event_ids = [e.event_id for e in correlated_events]
            for event in correlated_events:
                event.correlated_events.extend([eid for eid in event_ids if eid != event.event_id])
            
            logger.warning(f"Correlation detected: {rule.name} ({len(correlated_events)} events)")
            
        except Exception as e:
            logger.error(f"Failed to handle correlation detection: {e}")

    async def _metrics_collector_loop(self) -> None:
        """Background metrics collection loop"""
        while True:
            try:
                await self._collect_system_metrics()
                await asyncio.sleep(60)  # Collect every minute
                
            except Exception as e:
                logger.error(f"Metrics collector error: {e}")
                await asyncio.sleep(300)

    async def _collect_system_metrics(self) -> None:
        """Collect system performance metrics"""
        try:
            current_time = datetime.utcnow()
            
            # Event processing metrics
            if self.processing_metrics["event_processing_time"]:
                avg_processing_time = statistics.mean(self.processing_metrics["event_processing_time"][-100:])
                self._add_metric("event_processing_time_ms", avg_processing_time, current_time)
            
            # Alert generation metrics
            active_alerts_count = len(self.active_alerts)
            self._add_metric("active_alerts_count", active_alerts_count, current_time)
            
            # Event volume metrics
            recent_events = [e for e in self.security_events 
                           if e.timestamp > current_time - timedelta(minutes=5)]
            event_rate = len(recent_events) / 5.0  # Events per minute
            self._add_metric("event_rate_per_minute", event_rate, current_time)
            
            # System resource metrics (simulated)
            self._add_metric("cpu_usage_percent", 25.0, current_time)
            self._add_metric("memory_usage_percent", 60.0, current_time)
            self._add_metric("disk_usage_percent", 45.0, current_time)
            
        except Exception as e:
            logger.error(f"Failed to collect system metrics: {e}")

    def _add_metric(self, metric_name: str, value: float, timestamp: datetime) -> None:
        """Add metric data point"""
        try:
            data_point = MetricDataPoint(
                metric_name=metric_name,
                timestamp=timestamp,
                value=value
            )
            
            self.metrics[metric_name].append(data_point)
            
            # Maintain metric retention
            retention_threshold = timestamp - timedelta(days=self.config["metric_retention_days"])
            self.metrics[metric_name] = [
                dp for dp in self.metrics[metric_name]
                if dp.timestamp > retention_threshold
            ]
            
        except Exception as e:
            logger.error(f"Failed to add metric: {e}")

    def _update_event_indexes(self, event: SecurityEvent) -> None:
        """Update event indexes for fast lookups"""
        try:
            # Index by event type
            self.event_indexes[f"type:{event.event_type.value}"].add(event.event_id)
            
            # Index by user ID
            if event.user_id:
                self.event_indexes[f"user:{event.user_id}"].add(event.event_id)
            
            # Index by IP address
            if event.ip_address:
                self.event_indexes[f"ip:{event.ip_address}"].add(event.event_id)
            
            # Index by source
            self.event_indexes[f"source:{event.source}"].add(event.event_id)
            
        except Exception as e:
            logger.error(f"Failed to update event indexes: {e}")

    async def _update_real_time_stats(self, event: SecurityEvent) -> None:
        """Update real-time statistics"""
        try:
            current_time = datetime.utcnow()
            
            # Initialize stats if needed
            if "last_update" not in self.real_time_stats:
                self.real_time_stats = {
                    "last_update": current_time,
                    "events_last_hour": 0,
                    "events_last_minute": 0,
                    "top_event_types": defaultdict(int),
                    "top_sources": defaultdict(int),
                    "alert_counts_by_severity": defaultdict(int)
                }
            
            # Update event counts
            hour_threshold = current_time - timedelta(hours=1)
            minute_threshold = current_time - timedelta(minutes=1)
            
            self.real_time_stats["events_last_hour"] = len([
                e for e in self.security_events if e.timestamp > hour_threshold
            ])
            
            self.real_time_stats["events_last_minute"] = len([
                e for e in self.security_events if e.timestamp > minute_threshold
            ])
            
            # Update top event types and sources
            self.real_time_stats["top_event_types"][event.event_type.value] += 1
            self.real_time_stats["top_sources"][event.source] += 1
            
            # Update alert counts
            for alert in self.active_alerts.values():
                self.real_time_stats["alert_counts_by_severity"][alert.severity.value] += 1
            
            self.real_time_stats["last_update"] = current_time
            
        except Exception as e:
            logger.error(f"Failed to update real-time stats: {e}")

    async def get_monitoring_statistics(self) -> Dict[str, Any]:
        """Get security monitoring system statistics"""
        try:
            current_time = datetime.utcnow()
            
            # Event statistics
            total_events = len(self.security_events)
            recent_events = [e for e in self.security_events 
                           if e.timestamp > current_time - timedelta(hours=24)]
            
            # Alert statistics
            active_alerts = len(self.active_alerts)
            alert_by_severity = defaultdict(int)
            for alert in self.active_alerts.values():
                alert_by_severity[alert.severity.value] += 1
            
            # Rule statistics
            enabled_rules = len([r for r in self.monitoring_rules.values() if r.enabled])
            triggered_rules = len([r for r in self.monitoring_rules.values() if r.trigger_count > 0])
            
            return {
                "total_security_events": total_events,
                "events_last_24h": len(recent_events),
                "active_monitoring_rules": enabled_rules,
                "triggered_rules": triggered_rules,
                "correlation_rules": len(self.correlation_rules),
                "active_alerts": active_alerts,
                "alerts_by_severity": dict(alert_by_severity),
                "dashboards": len(self.dashboards),
                "metrics_collected": len(self.metrics),
                "real_time_stats": self.real_time_stats,
                "average_processing_time_ms": sum(self.processing_metrics["event_processing_time"][-1000:]) / min(len(self.processing_metrics["event_processing_time"]), 1000) if self.processing_metrics["event_processing_time"] else 0.0,
                "system_performance": {
                    "events_per_second": len(recent_events) / (24 * 3600) if recent_events else 0,
                    "alerts_per_hour": len([a for a in self.active_alerts.values() 
                                          if a.created_at > current_time - timedelta(hours=1)]),
                    "correlation_detections": sum(r.detection_count for r in self.correlation_rules.values())
                },
                "timestamp": current_time.isoformat()
            }
            
        except Exception as e:
            logger.error(f"Failed to get monitoring statistics: {e}")
            return {"error": str(e)}


# Factory function for easier instantiation
def create_security_monitoring_system() -> SecurityMonitoringSystem:
    """Factory function to create a Security Monitoring System"""
    return SecurityMonitoringSystem()


# Example usage and testing
async def main():
    """Example usage of Security Monitoring System"""
    monitoring_system = create_security_monitoring_system()
    
    # Simulate security events
    events = [
        SecurityEvent(
            event_id="",
            event_type=EventType.LOGIN_FAILURE,
            timestamp=datetime.utcnow(),
            source="web_app",
            severity=AlertSeverity.MEDIUM,
            user_id="user_123",
            ip_address="192.168.1.100",
            details={"reason": "invalid_password"}
        ),
        SecurityEvent(
            event_id="",
            event_type=EventType.DATA_ACCESS,
            timestamp=datetime.utcnow(),
            source="api",
            severity=AlertSeverity.LOW,
            user_id="user_456",
            ip_address="192.168.1.200",
            details={"resource": "/api/creator/revenue", "data_volume": 1500}
        )
    ]
    
    # Ingest events
    for event in events:
        event_id = await monitoring_system.ingest_security_event(event)
        print(f"Security event ingested: {event_id}")
    
    # Wait for processing
    await asyncio.sleep(2)
    
    # Get statistics
    stats = await monitoring_system.get_monitoring_statistics()
    print(f"Monitoring System Statistics: {stats}")


if __name__ == "__main__":
    asyncio.run(main())