apiVersion: v1
kind: Namespace
metadata:
  annotations:
    contact: mlaiel@live.de
    description: IA Chérie microservices - staging
  labels:
    environment: staging
    managed-by: enterprise-orchestrator
    project: iacherie
  name: iacherie-staging
spec: {}
