apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8003'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: ai-inference-service
    environment: staging
    service-type: ai-service
  name: ai-inference-service
  namespace: ainflue-staging
spec:
  ports:
  - name: http
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: ai-inference-service
  type: ClusterIP
