apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: ai-inference-service
    service-type: ai-service
  name: ai-inference-service-netpol
  namespace: ainflue-staging
spec:
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    to: []
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ainflue-staging
    ports:
    - port: 8003
      protocol: TCP
  podSelector:
    matchLabels:
      app: ai-inference-service
  policyTypes:
  - Ingress
  - Egress
