"""Constants for IA2GOOD module"""
from typing import List, Dict

# Case Types
CASE_TYPE_HOMELESS = "homeless"
CASE_TYPE_ANIMAL = "animal"
CASE_TYPE_EMERGENCY = "emergency"
CASE_TYPE_OTHER = "other"

CASE_TYPES: List[str] = [
    CASE_TYPE_HOMELESS,
    CASE_TYPE_ANIMAL,
    CASE_TYPE_EMERGENCY,
    CASE_TYPE_OTHER,
]

# Case Status
CASE_STATUS_OPEN = "open"
CASE_STATUS_CLAIMED = "claimed"
CASE_STATUS_IN_PROGRESS = "in_progress"
CASE_STATUS_COMPLETED = "completed"
CASE_STATUS_CANCELLED = "cancelled"

CASE_STATUSES: List[str] = [
    CASE_STATUS_OPEN,
    CASE_STATUS_CLAIMED,
    CASE_STATUS_IN_PROGRESS,
    CASE_STATUS_COMPLETED,
    CASE_STATUS_CANCELLED,
]

# Assignment Status
ASSIGNMENT_STATUS_PENDING = "pending"
ASSIGNMENT_STATUS_ACCEPTED = "accepted"
ASSIGNMENT_STATUS_DECLINED = "declined"
ASSIGNMENT_STATUS_IN_PROGRESS = "in_progress"
ASSIGNMENT_STATUS_COMPLETED = "completed"
ASSIGNMENT_STATUS_CANCELLED = "cancelled"

ASSIGNMENT_STATUSES: List[str] = [
    ASSIGNMENT_STATUS_PENDING,
    ASSIGNMENT_STATUS_ACCEPTED,
    ASSIGNMENT_STATUS_DECLINED,
    ASSIGNMENT_STATUS_IN_PROGRESS,
    ASSIGNMENT_STATUS_COMPLETED,
    ASSIGNMENT_STATUS_CANCELLED,
]

# Volunteer Skills
SKILL_MEDICAL = "medical"
SKILL_TRANSPORT = "transport"
SKILL_SHELTER = "shelter"
SKILL_FOOD = "food"
SKILL_LEGAL = "legal"
SKILL_PSYCHOLOGICAL = "psychological"
SKILL_TRANSLATION = "translation"
SKILL_TECHNICAL = "technical"

VOLUNTEER_SKILLS: List[str] = [
    SKILL_MEDICAL,
    SKILL_TRANSPORT,
    SKILL_SHELTER,
    SKILL_FOOD,
    SKILL_LEGAL,
    SKILL_PSYCHOLOGICAL,
    SKILL_TRANSLATION,
    SKILL_TECHNICAL,
]

# Verification Status
VERIFICATION_PENDING = "pending"
VERIFICATION_VERIFIED = "verified"
VERIFICATION_REJECTED = "rejected"

VERIFICATION_STATUSES: List[str] = [
    VERIFICATION_PENDING,
    VERIFICATION_VERIFIED,
    VERIFICATION_REJECTED,
]

# Activity Types
ACTIVITY_CASE_CREATED = "case_created"
ACTIVITY_CASE_UPDATED = "case_updated"
ACTIVITY_CASE_DELETED = "case_deleted"
ACTIVITY_VOLUNTEER_ASSIGNED = "volunteer_assigned"
ACTIVITY_VOLUNTEER_ACCEPTED = "volunteer_accepted"
ACTIVITY_VOLUNTEER_DECLINED = "volunteer_declined"
ACTIVITY_CASE_STARTED = "case_started"
ACTIVITY_CASE_COMPLETED = "case_completed"
ACTIVITY_CASE_CANCELLED = "case_cancelled"
ACTIVITY_RATING_SUBMITTED = "rating_submitted"

ACTIVITY_TYPES: List[str] = [
    ACTIVITY_CASE_CREATED,
    ACTIVITY_CASE_UPDATED,
    ACTIVITY_CASE_DELETED,
    ACTIVITY_VOLUNTEER_ASSIGNED,
    ACTIVITY_VOLUNTEER_ACCEPTED,
    ACTIVITY_VOLUNTEER_DECLINED,
    ACTIVITY_CASE_STARTED,
    ACTIVITY_CASE_COMPLETED,
    ACTIVITY_CASE_CANCELLED,
    ACTIVITY_RATING_SUBMITTED,
]

# Validation Constraints
MIN_TITLE_LENGTH = 5
MAX_TITLE_LENGTH = 255
MIN_DESCRIPTION_LENGTH = 20
MAX_DESCRIPTION_LENGTH = 5000

MIN_URGENCY_LEVEL = 1
MAX_URGENCY_LEVEL = 10

MIN_RATING = 1
MAX_RATING = 5

MAX_PHOTOS_PER_CASE = 5
MAX_PHOTO_SIZE_MB = 10

MIN_SKILLS_COUNT = 1
MAX_SKILLS_COUNT = 10

MIN_DISTANCE_KM = 1
MAX_DISTANCE_KM = 100

DEFAULT_NOTIFICATION_RADIUS_KM = 5
DEFAULT_MAX_DISTANCE_KM = 10

# Matching Algorithm Weights
MATCHING_WEIGHT_SKILLS = 40.0  # 40% of total score
MATCHING_WEIGHT_DISTANCE = 30.0  # 30% of total score
MATCHING_WEIGHT_AVAILABILITY = 15.0  # 15% of total score
MATCHING_WEIGHT_RELIABILITY = 15.0  # 15% of total score

# Distance Scoring Thresholds (km)
DISTANCE_EXCELLENT = 2  # < 2km: 30 points
DISTANCE_GOOD = 5  # 2-5km: 25 points
DISTANCE_OK = 10  # 5-10km: 20 points
DISTANCE_FAR = 20  # 10-20km: 10 points
# > 20km: 5 points

# Reliability Score Thresholds
RELIABILITY_EXCELLENT = 90.0  # > 90: bonus +5
RELIABILITY_POOR = 50.0  # < 50: penalty -5

# Auto-Assignment Threshold
AUTO_ASSIGN_MIN_SCORE = 80.0  # Auto-assign if match score > 80

# Achievement Codes
ACHIEVEMENT_FIRST_CASE = "first_case"
ACHIEVEMENT_HELPING_HAND = "helping_hand"
ACHIEVEMENT_GUARDIAN_ANGEL = "guardian_angel"
ACHIEVEMENT_NIGHT_OWL = "night_owl"
ACHIEVEMENT_FAST_RESPONDER = "fast_responder"
ACHIEVEMENT_TEAM_PLAYER = "team_player"

ACHIEVEMENT_CODES: List[str] = [
    ACHIEVEMENT_FIRST_CASE,
    ACHIEVEMENT_HELPING_HAND,
    ACHIEVEMENT_GUARDIAN_ANGEL,
    ACHIEVEMENT_NIGHT_OWL,
    ACHIEVEMENT_FAST_RESPONDER,
    ACHIEVEMENT_TEAM_PLAYER,
]

# Achievement Points
ACHIEVEMENT_POINTS: Dict[str, int] = {
    ACHIEVEMENT_FIRST_CASE: 10,
    ACHIEVEMENT_HELPING_HAND: 50,
    ACHIEVEMENT_GUARDIAN_ANGEL: 250,
    ACHIEVEMENT_NIGHT_OWL: 20,
    ACHIEVEMENT_FAST_RESPONDER: 30,
    ACHIEVEMENT_TEAM_PLAYER: 40,
}

# Notification Types
NOTIFICATION_CASE_CREATED = "case_created"
NOTIFICATION_VOLUNTEER_ASSIGNED = "volunteer_assigned"
NOTIFICATION_VOLUNTEER_ACCEPTED = "volunteer_accepted"
NOTIFICATION_CASE_COMPLETED = "case_completed"
NOTIFICATION_RATING_REQUEST = "rating_request"
NOTIFICATION_ACHIEVEMENT_UNLOCKED = "achievement_unlocked"

NOTIFICATION_TYPES: List[str] = [
    NOTIFICATION_CASE_CREATED,
    NOTIFICATION_VOLUNTEER_ASSIGNED,
    NOTIFICATION_VOLUNTEER_ACCEPTED,
    NOTIFICATION_CASE_COMPLETED,
    NOTIFICATION_RATING_REQUEST,
    NOTIFICATION_ACHIEVEMENT_UNLOCKED,
]

# Default Values
DEFAULT_COUNTRY = "France"
DEFAULT_LANGUAGE = "fr"
DEFAULT_URGENCY_LEVEL = 5
DEFAULT_VOLUNTEERS_NEEDED = 1
DEFAULT_RELIABILITY_SCORE = 100.0
DEFAULT_PAGE = 1
DEFAULT_PER_PAGE = 20
MAX_PER_PAGE = 100

# Response Time Categories (minutes)
RESPONSE_IMMEDIATE = 10  # < 10 min
RESPONSE_FAST = 30  # 10-30 min
RESPONSE_MODERATE = 60  # 30-60 min
RESPONSE_SLOW = 120  # 60-120 min
# > 120 min: very slow

# API Rate Limits
RATE_LIMIT_PER_MINUTE = 60
RATE_LIMIT_PER_HOUR = 1000

# Geolocation
DEFAULT_SEARCH_RADIUS_KM = 20
MAX_SEARCH_RADIUS_KM = 50

# Photo Upload
ALLOWED_IMAGE_FORMATS = ['jpg', 'jpeg', 'png', 'webp']
ALLOWED_IMAGE_MIMETYPES = ['image/jpeg', 'image/png', 'image/webp']
