"""Surveillance Utilities Module
=============================

Professional surveillance utilities for web crawlers and content monitoring.
Implements advanced surveillance strategies, monitoring engines, and alert systems.

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright: All rights reserved. Unauthorized use, reproduction, or distribution prohibited.

WARNING: This code is protected by copyright law. Any unauthorized copying, 
distribution, or modification is strictly prohibited and will result in 
legal action. Contact mlaiel@live.de for licensing.

Project Team Specialties:
- Lead Dev IA: Advanced AI integration and machine learning
- Backend Senior: Scalable architecture and microservices  
- ML Engineer: Content analysis and recommendation systems
- DBA: High-performance database optimization
- Security Expert: Enterprise-grade security and encryption
- Microservices Architect: Distributed systems design
- Audio Engineer: Advanced audio processing and analysis
- DevOps Engineer: CI/CD and infrastructure automation
- IA Prompt Engineer: Intelligent prompt optimization
"""

import asyncio
import logging
from typing import Dict, List, Optional, Tuple, Any, Union, Callable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import json
import uuid
from urllib.parse import urlparse, urljoin
import re
import time

# External imports
import aiohttp
import redis
from sqlalchemy.ext.asyncio import AsyncSession
from celery import Celery

logger = logging.getLogger(__name__)

class SurveillanceStatus(Enum):
    """
Surveillance target status."""

    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"
    COMPLETED = "completed"

class ThreatLevel(Enum):
    """Threat classification levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
    UNKNOWN = "unknown"

class AlertType(Enum):
    """Alert notification types."""

    EMAIL = "email"
    SMS = "sms"
    WEBHOOK = "webhook"
    SLACK = "slack"
    DISCORD = "discord"
    PUSH = "push"

class MonitoringFrequency(Enum):
    """Monitoring frequency options."""

    REAL_TIME = "real_time"  # Continuous
    EVERY_MINUTE = "every_minute"
    EVERY_5_MINUTES = "every_5_minutes"
    EVERY_15_MINUTES = "every_15_minutes"
    HOURLY = "hourly"
    DAILY = "daily"
    WEEKLY = "weekly"

@dataclass
class SurveillanceTarget:
    """Configuration for surveillance target."""
    target_id: str
    user_id: str
    name: str
    description: str
    target_urls: List[str]
    keywords: List[str]
    content_fingerprints: List[str]
    platforms: List[str]
    monitoring_frequency: MonitoringFrequency
    alert_threshold: float
    threat_detection_enabled: bool
    automated_response: bool
    status: SurveillanceStatus
    created_at: datetime
    last_check: Optional[datetime] = None
    next_check: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class SurveillanceAlert:
    """
Alert generated by surveillance system."""
    alert_id: str
    target_id: str
    user_id: str
    alert_type: str
    severity: ThreatLevel
    title: str
    description: str
    evidence_urls: List[str]
    confidence_score: float
    detected_at: datetime
    platform: str
    matched_content: Optional[str] = None
    similarity_score: Optional[float] = None
    automated_actions: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ThreatAssessment:
    """
Threat assessment result."""
    threat_id: str
    target_id: str
    threat_level: ThreatLevel
    confidence: float
    threat_type: str
    description: str
    indicators: List[str]
    recommended_actions: List[str]
    assessed_at: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class MonitoringMetrics:
    """
Monitoring performance metrics."""
    target_id: str
    total_checks: int
    successful_checks: int
    failed_checks: int
    alerts_generated: int
    threats_detected: int
    average_response_time: float
    last_error: Optional[str] = None
    uptime_percentage: float = 0.0
    performance_score: float = 0.0

class SurveillanceEngine:
    """
    Advanced surveillance engine for content monitoring.
    
    Features:
    - Multi-target monitoring
    - Real-time threat detection
    - Intelligent alert management
    - Automated response systems
    - Performance optimization
    - Scalable architecture
    """
    
    def __init__(
        self,
        redis_client: Optional[redis.Redis] = None,
        celery_app: Optional[Celery] = None,
        db_session: Optional[AsyncSession] = None
    ):
        """
Initialize surveillance engine."""
        self.redis_client = redis_client
        self.celery_app = celery_app
        self.db_session = db_session
        
        # Internal state
        self.active_targets: Dict[str, SurveillanceTarget] = {}
        self.monitoring_tasks: Dict[str, asyncio.Task] = {}
        self.alert_handlers: Dict[AlertType, Callable] = {}
        self.threat_classifiers: List[Callable] = []
        
        # Performance tracking
        self.metrics: Dict[str, MonitoringMetrics] = {}
        
        # Configuration
        self.max_concurrent_monitors = 100
        self.alert_cooldown_seconds = 300
        self.threat_analysis_timeout = 30
        
        logger.info("Surveillance engine initialized")
    
    async def add_surveillance_target(self, target: SurveillanceTarget) -> bool:
        """Add new surveillance target."""
        try:
            # Validate target
            if not self._validate_target(target):
                logger.error(f"Invalid surveillance target: {target.target_id}")
                return False
            
            # Store target
            self.active_targets[target.target_id] = target
            
            # Initialize metrics
            self.metrics[target.target_id] = MonitoringMetrics(
                target_id=target.target_id,
                total_checks=0,
                successful_checks=0,
                failed_checks=0,
                alerts_generated=0,
                threats_detected=0,
                average_response_time=0.0
            )
            
            # Persist to database if available
            if self.db_session:
                await self._persist_target(target)
            
            # Start monitoring if active
            if target.status == SurveillanceStatus.ACTIVE:
                await self._start_target_monitoring(target.target_id)
            
            logger.info(f"Surveillance target added: {target.target_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to add surveillance target: {e}")
            return False
    
    async def remove_surveillance_target(self, target_id: str) -> bool:
        """Remove surveillance target."""
        try:
            # Stop monitoring
            await self._stop_target_monitoring(target_id)
            
            # Remove from active targets
            if target_id in self.active_targets:
                del self.active_targets[target_id]
            
            # Remove metrics
            if target_id in self.metrics:
                del self.metrics[target_id]
            
            # Remove from database if available
            if self.db_session:
                await self._remove_target_from_db(target_id)
            
            logger.info(f"Surveillance target removed: {target_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to remove surveillance target: {e}")
            return False
    
    async def start_surveillance(self, target_id: str) -> bool:
        """Start surveillance for specific target."""
        try:
            if target_id not in self.active_targets:
                logger.error(f"Target not found: {target_id}")
                return False
            
            target = self.active_targets[target_id]
            target.status = SurveillanceStatus.ACTIVE
            
            await self._start_target_monitoring(target_id)
            
            logger.info(f"Surveillance started for target: {target_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to start surveillance: {e}")
            return False
    
    async def stop_surveillance(self, target_id: str) -> bool:
        """Stop surveillance for specific target."""
        try:
            if target_id not in self.active_targets:
                logger.error(f"Target not found: {target_id}")
                return False
            
            target = self.active_targets[target_id]
            target.status = SurveillanceStatus.STOPPED
            
            await self._stop_target_monitoring(target_id)
            
            logger.info(f"Surveillance stopped for target: {target_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to stop surveillance: {e}")
            return False
    
    async def _start_target_monitoring(self, target_id: str) -> None:
        """Start monitoring task for target."""
        if target_id in self.monitoring_tasks:
            # Already monitoring
            return
        
        target = self.active_targets[target_id]
        
        # Create monitoring task
        task = asyncio.create_task(
            self._monitor_target_loop(target)
        )
        
        self.monitoring_tasks[target_id] = task
        logger.info(f"Monitoring task started for: {target_id}")
    
    async def _stop_target_monitoring(self, target_id: str) -> None:
        """Stop monitoring task for target."""
        if target_id in self.monitoring_tasks:
            task = self.monitoring_tasks[target_id]
            task.cancel()
            
            try:
                await task
            except asyncio.CancelledError:
                pass
            
            del self.monitoring_tasks[target_id]
            logger.info(f"Monitoring task stopped for: {target_id}")
    
    async def _monitor_target_loop(self, target: SurveillanceTarget) -> None:
        """Main monitoring loop for surveillance target."""
        target_id = target.target_id
        
        try:
            while target.status == SurveillanceStatus.ACTIVE:
                start_time = time.time()
                
                try:
                    # Perform surveillance check
                    alerts = await self._perform_surveillance_check(target)
                    
                    # Process alerts
                    for alert in alerts:
                        await self._process_alert(alert)
                    
                    # Update metrics
                    metrics = self.metrics[target_id]
                    metrics.total_checks += 1
                    metrics.successful_checks += 1
                    metrics.alerts_generated += len(alerts)
                    
                    response_time = time.time() - start_time
                    metrics.average_response_time = (
                        (metrics.average_response_time * (metrics.total_checks - 1) + response_time) 
                        / metrics.total_checks
                    )
                    
                    # Update target timestamps
                    target.last_check = datetime.now()
                    target.next_check = self._calculate_next_check(target)
                    
                except Exception as e:
                    logger.error(f"Surveillance check failed for {target_id}: {e}")
                    
                    # Update error metrics
                    metrics = self.metrics[target_id]
                    metrics.total_checks += 1
                    metrics.failed_checks += 1
                    metrics.last_error = str(e)
                    
                    # Update target status
                    target.status = SurveillanceStatus.ERROR
                
                # Calculate sleep time based on monitoring frequency
                sleep_time = self._get_monitoring_interval(target.monitoring_frequency)
                await asyncio.sleep(sleep_time)
                
        except asyncio.CancelledError:
            logger.info(f"Monitoring loop cancelled for: {target_id}")
            raise
        except Exception as e:
            logger.error(f"Monitoring loop failed for {target_id}: {e}")
            target.status = SurveillanceStatus.ERROR
    
    async def _perform_surveillance_check(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """Perform surveillance check for target."""
        alerts = []
        
        try:
            # Check each platform
            for platform in target.platforms:
                platform_alerts = await self._check_platform(target, platform)
                alerts.extend(platform_alerts)
            
            # Check specific URLs
            for url in target.target_urls:
                url_alerts = await self._check_url(target, url)
                alerts.extend(url_alerts)
            
            # Perform keyword monitoring
            if target.keywords:
                keyword_alerts = await self._check_keywords(target)
                alerts.extend(keyword_alerts)
            
            # Perform content fingerprint matching
            if target.content_fingerprints:
                fingerprint_alerts = await self._check_fingerprints(target)
                alerts.extend(fingerprint_alerts)
            
            # Filter alerts based on threshold
            filtered_alerts = [
                alert for alert in alerts 
                if alert.confidence_score >= target.alert_threshold
            ]
            
            return filtered_alerts
            
        except Exception as e:
            logger.error(f"Surveillance check failed: {e}")
            return []
    
    async def _check_platform(self, target: SurveillanceTarget, platform: str) -> List[SurveillanceAlert]:
        """Check specific platform for target content."""
        alerts = []
        
        try:
            # Platform-specific monitoring logic
            if platform == "youtube":
                alerts.extend(await self._check_youtube(target))
            elif platform == "instagram":
                alerts.extend(await self._check_instagram(target))
            elif platform == "tiktok":
                alerts.extend(await self._check_tiktok(target))
            elif platform == "twitter":
                alerts.extend(await self._check_twitter(target))
            elif platform == "facebook":
                alerts.extend(await self._check_facebook(target))
            elif platform == "spotify":
                alerts.extend(await self._check_spotify(target))
            else:
                # Generic web monitoring
                alerts.extend(await self._check_generic_platform(target, platform))
            
            return alerts
            
        except Exception as e:
            logger.error(f"Platform check failed for {platform}: {e}")
            return []
    
    async def _check_url(self, target: SurveillanceTarget, url: str) -> List[SurveillanceAlert]:
        """Check specific URL for content changes."""
        alerts = []
        
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(url) as response:
                    if response.status == 200:
                        content = await response.text()
                        
                        # Analyze content for threats
                        threat_analysis = await self._analyze_content_threats(
                            target, content, url
                        )
                        
                        if threat_analysis:
                            alert = SurveillanceAlert(
                                alert_id=str(uuid.uuid4()),
                                target_id=target.target_id,
                                user_id=target.user_id,
                                alert_type="content_change",
                                severity=threat_analysis.threat_level,
                                title=f"Content detected on {urlparse(url).netloc}",
                                description=threat_analysis.description,
                                evidence_urls=[url],
                                confidence_score=threat_analysis.confidence,
                                detected_at=datetime.now(),
                                platform=urlparse(url).netloc,
                                metadata=threat_analysis.metadata
                            )
                            alerts.append(alert)
            
            return alerts
            
        except Exception as e:
            logger.error(f"URL check failed for {url}: {e}")
            return []
    
    async def _check_keywords(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """Check for keyword-based content detection."""
        alerts = []
        
        try:
            # This would integrate with search APIs or crawling results
            # For now, we'll simulate keyword detection
            
            for keyword in target.keywords:
                # Search for keyword across platforms
                search_results = await self._search_keyword_across_platforms(
                    keyword, target.platforms
                )
                
                for result in search_results:
                    # Analyze if this is a potential threat
                    if result.get('confidence', 0) >= target.alert_threshold:
                        alert = SurveillanceAlert(
                            alert_id=str(uuid.uuid4()),
                            target_id=target.target_id,
                            user_id=target.user_id,
                            alert_type="keyword_detection",
                            severity=ThreatLevel.MEDIUM,
                            title=f"Keyword '{keyword}' detected",
                            description=f"Content containing keyword '{keyword}' found",
                            evidence_urls=[result.get('url', '')],
                            confidence_score=result.get('confidence', 0),
                            detected_at=datetime.now(),
                            platform=result.get('platform', ''),
                            matched_content=result.get('content', ''),
                            metadata={'keyword': keyword}
                        )
                        alerts.append(alert)
            
            return alerts
            
        except Exception as e:
            logger.error(f"Keyword check failed: {e}")
            return []
    
    async def _check_fingerprints(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """Check for content fingerprint matches."""
        alerts = []
        
        try:
            # This would integrate with fingerprinting system
            # For now, we'll simulate fingerprint matching
            
            for fingerprint_id in target.content_fingerprints:
                # Search for similar content
                matches = await self._search_similar_content(fingerprint_id)
                
                for match in matches:
                    if match.get('similarity_score', 0) >= target.alert_threshold:
                        alert = SurveillanceAlert(
                            alert_id=str(uuid.uuid4()),
                            target_id=target.target_id,
                            user_id=target.user_id,
                            alert_type="fingerprint_match",
                            severity=self._calculate_threat_level(match.get('similarity_score', 0)),
                            title="Similar content detected",
                            description=f"Content with {match.get('similarity_score', 0):.2%} similarity found",
                            evidence_urls=[match.get('url', '')],
                            confidence_score=match.get('similarity_score', 0),
                            detected_at=datetime.now(),
                            platform=match.get('platform', ''),
                            similarity_score=match.get('similarity_score', 0),
                            metadata={'fingerprint_id': fingerprint_id}
                        )
                        alerts.append(alert)
            
            return alerts
            
        except Exception as e:
            logger.error(f"Fingerprint check failed: {e}")
            return []
    
    async def _analyze_content_threats(
        self, 
        target: SurveillanceTarget, 
        content: str, 
        url: str
    ) -> Optional[ThreatAssessment]:
        """Analyze content for potential threats."""
        try:
            # Run threat classifiers
            threat_indicators = []
            confidence_scores = []
            
            for classifier in self.threat_classifiers:
                result = await classifier(content, target)
                if result:
                    threat_indicators.extend(result.get('indicators', []))
                    confidence_scores.append(result.get('confidence', 0))
            
            if not threat_indicators:
                return None
            
            # Calculate overall threat level
            avg_confidence = sum(confidence_scores) / len(confidence_scores)
            threat_level = self._calculate_threat_level(avg_confidence)
            
            # Generate threat assessment
            assessment = ThreatAssessment(
                threat_id=str(uuid.uuid4()),
                target_id=target.target_id,
                threat_level=threat_level,
                confidence=avg_confidence,
                threat_type="content_analysis",
                description=f"Threat detected in content from {url}",
                indicators=threat_indicators,
                recommended_actions=self._get_recommended_actions(threat_level),
                assessed_at=datetime.now(),
                metadata={'url': url, 'content_length': len(content)}
            )
            
            return assessment
            
        except Exception as e:
            logger.error(f"Threat analysis failed: {e}")
            return None
    
    async def _process_alert(self, alert: SurveillanceAlert) -> None:
        """Process and handle surveillance alert."""
        try:
            # Check alert cooldown
            if not self._check_alert_cooldown(alert):
                return
            
            # Log alert
            logger.warning(f"Surveillance alert: {alert.alert_type} - {alert.title}")
            
            # Send notifications
            await self._send_alert_notifications(alert)
            
            # Execute automated responses if enabled
            target = self.active_targets.get(alert.target_id)
            if target and target.automated_response:
                await self._execute_automated_response(alert)
            
            # Update metrics
            if alert.target_id in self.metrics:
                metrics = self.metrics[alert.target_id]
                if alert.severity in [ThreatLevel.HIGH, ThreatLevel.CRITICAL]:
                    metrics.threats_detected += 1
            
            # Store alert
            await self._store_alert(alert)
            
        except Exception as e:
            logger.error(f"Alert processing failed: {e}")
    
    async def _send_alert_notifications(self, alert: SurveillanceAlert) -> None:
        """Send alert notifications through configured channels."""
        target = self.active_targets.get(alert.target_id)
        if not target:
            return
        
        # Get notification preferences from target metadata
        notification_channels = target.metadata.get('notification_channels', ['email'])
        
        for channel in notification_channels:
            try:
                if channel in self.alert_handlers:
                    await self.alert_handlers[channel](alert)
                else:
                    logger.warning(f"No handler for notification channel: {channel}")
            except Exception as e:
                logger.error(f"Notification failed for channel {channel}: {e}")
    
    async def _execute_automated_response(self, alert: SurveillanceAlert) -> None:
        """Execute automated response actions."""
        try:
            actions = []
            
            # Determine actions based on threat level
            if alert.severity == ThreatLevel.CRITICAL:
                actions.extend([
                    "immediate_takedown_request",
                    "escalate_to_legal",
                    "preserve_evidence"
                ])
            elif alert.severity == ThreatLevel.HIGH:
                actions.extend([
                    "dmca_takedown_request",
                    "preserve_evidence"
                ])
            elif alert.severity == ThreatLevel.MEDIUM:
                actions.extend([
                    "collect_evidence",
                    "monitor_closely"
                ])
            
            # Execute actions
            for action in actions:
                try:
                    await self._execute_action(action, alert)
                    alert.automated_actions.append(action)
                except Exception as e:
                    logger.error(f"Automated action '{action}' failed: {e}")
            
        except Exception as e:
            logger.error(f"Automated response failed: {e}")
    
    # Platform-specific monitoring methods
    async def _check_youtube(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """YouTube-specific monitoring."""
        # Implementation would use YouTube API
        return []
    
    async def _check_instagram(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """
Instagram-specific monitoring."""
        # Implementation would use Instagram API
        return []
    
    async def _check_tiktok(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """
TikTok-specific monitoring."""
        # Implementation would use TikTok API or scraping
        return []
    
    async def _check_twitter(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """
Twitter-specific monitoring."""
        # Implementation would use Twitter API
        return []
    
    async def _check_facebook(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """
Facebook-specific monitoring."""
        # Implementation would use Facebook API
        return []
    
    async def _check_spotify(self, target: SurveillanceTarget) -> List[SurveillanceAlert]:
        """
Spotify-specific monitoring."""
        # Implementation would use Spotify API
        return []
    
    async def _check_generic_platform(self, target: SurveillanceTarget, platform: str) -> List[SurveillanceAlert]:
        """
Generic platform monitoring."""
        # Implementation would use web scraping
        return []
    
    # Helper methods
    def _validate_target(self, target: SurveillanceTarget) -> bool:
        """
Validate surveillance target configuration."""
        if not target.target_id or not target.user_id:
            return False
        
        if not target.target_urls and not target.keywords and not target.content_fingerprints:
            return False
        
        if target.alert_threshold < 0 or target.alert_threshold > 1:
            return False
        
        return True
    
    def _calculate_next_check(self, target: SurveillanceTarget) -> datetime:
        """
Calculate next check time based on monitoring frequency."""
        now = datetime.now()
        interval = self._get_monitoring_interval(target.monitoring_frequency)
        return now + timedelta(seconds=interval)
    
    def _get_monitoring_interval(self, frequency: MonitoringFrequency) -> int:
        """
Get monitoring interval in seconds."""
        intervals = {
            MonitoringFrequency.REAL_TIME: 30,
            MonitoringFrequency.EVERY_MINUTE: 60,
            MonitoringFrequency.EVERY_5_MINUTES: 300,
            MonitoringFrequency.EVERY_15_MINUTES: 900,
            MonitoringFrequency.HOURLY: 3600,
            MonitoringFrequency.DAILY: 86400,
            MonitoringFrequency.WEEKLY: 604800
        }
        return intervals.get(frequency, 300)
    
    def _calculate_threat_level(self, confidence: float) -> ThreatLevel:
        """
Calculate threat level based on confidence score."""
        if confidence >= 0.9:
            return ThreatLevel.CRITICAL
        elif confidence >= 0.7:
            return ThreatLevel.HIGH
        elif confidence >= 0.5:
            return ThreatLevel.MEDIUM
        elif confidence >= 0.3:
            return ThreatLevel.LOW
        else:
            return ThreatLevel.UNKNOWN
    
    def _get_recommended_actions(self, threat_level: ThreatLevel) -> List[str]:
        """
Get recommended actions for threat level."""
        actions = {
            ThreatLevel.CRITICAL: [
                "immediate_takedown_request",
                "legal_escalation",
                "preserve_evidence",
                "notify_authorities"
            ],
            ThreatLevel.HIGH: [
                "dmca_takedown_request",
                "preserve_evidence",
                "contact_platform"
            ],
            ThreatLevel.MEDIUM: [
                "collect_evidence",
                "monitor_closely",
                "analyze_further"
            ],
            ThreatLevel.LOW: [
                "continue_monitoring",
                "document_occurrence"
            ]
        }
        return actions.get(threat_level, [])
    
    def _check_alert_cooldown(self, alert: SurveillanceAlert) -> bool:
        """Check if alert is within cooldown period."""
        # Implementation would check Redis for recent alerts
        return True
    
    async def _search_keyword_across_platforms(
        self, 
        keyword: str, 
        platforms: List[str]
    ) -> List[Dict[str, Any]]:
        """
Search for keyword across multiple platforms."""
        # Placeholder implementation
        return []
    
    async def _search_similar_content(self, fingerprint_id: str) -> List[Dict[str, Any]]:
        """
Search for content similar to fingerprint."""
        # Placeholder implementation
        return []
    
    async def _execute_action(self, action: str, alert: SurveillanceAlert) -> None:
        """
Execute automated action."""
        # Placeholder implementation
        logger.info(f"Executing action '{action}' for alert {alert.alert_id}")
    
    async def _persist_target(self, target: SurveillanceTarget) -> None:
        """Persist target to database."""
        try:
            logger.info(f"Persisting surveillance target: {target.target_id}")
            
            # Prepare target data for storage
            target_data = {
                'target_id': target.target_id,
                'target_type': target.target_type.value,
                'url': target.url,
                'metadata': target.metadata,
                'created_at': target.created_at.isoformat(),
                'last_checked': target.last_checked.isoformat() if target.last_checked else None,
                'status': target.status.value,
                'check_frequency': target.check_frequency,
                'is_active': target.is_active
            }
            
            # Store in local cache first
            self.target_cache[target.target_id] = target_data
            
            # Persist to database if available
            try:
                if hasattr(self, 'database_connection') and self.database_connection:
                    # Use database connection
                    async with self.database_connection.begin() as transaction:
                        await self.database_connection.execute(
                            """INSERT INTO surveillance_targets 
                               (target_id, target_type, url, metadata, created_at, 
                                last_checked, status, check_frequency, is_active)
                               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                               ON CONFLICT (target_id) DO UPDATE SET
                               target_type = excluded.target_type,
                               url = excluded.url,
                               metadata = excluded.metadata,
                               last_checked = excluded.last_checked,
                               status = excluded.status,
                               check_frequency = excluded.check_frequency,
                               is_active = excluded.is_active""",
                            (target_data['target_id'], target_data['target_type'], 
                             target_data['url'], json.dumps(target_data['metadata']),
                             target_data['created_at'], target_data['last_checked'],
                             target_data['status'], target_data['check_frequency'],
                             target_data['is_active'])
                        )
                        await transaction.commit()
                else:
                    # Fallback to file storage
                    storage_path = f"surveillance_data/targets/{target.target_id}.json"
                    os.makedirs(os.path.dirname(storage_path), exist_ok=True)
                    
                    with open(storage_path, 'w') as f:
                        json.dump(target_data, f, indent=2)
                        
            except Exception as storage_error:
                logger.warning(f"Database storage failed, using file backup: {storage_error}")
                # Backup to file system
                backup_path = f"surveillance_backup/targets_{datetime.now().strftime('%Y%m%d')}.jsonl"
                os.makedirs(os.path.dirname(backup_path), exist_ok=True)
                
                with open(backup_path, 'a') as f:
                    f.write(json.dumps(target_data) + '\n')
            
            logger.debug(f"Successfully persisted target {target.target_id}")
            
        except Exception as e:
            logger.error(f"Error persisting target {target.target_id}: {str(e)}")
            raise
    
    async def _remove_target_from_db(self, target_id: str) -> None:
        """Remove target from database."""
        try:
            logger.info(f"Removing surveillance target: {target_id}")
            
            # Remove from local cache
            if target_id in self.target_cache:
                del self.target_cache[target_id]
            
            # Remove from database if available
            try:
                if hasattr(self, 'database_connection') and self.database_connection:
                    async with self.database_connection.begin() as transaction:
                        result = await self.database_connection.execute(
                            "DELETE FROM surveillance_targets WHERE target_id = ?",
                            (target_id,)
                        )
                        await transaction.commit()
                        
                        if result.rowcount > 0:
                            logger.info(f"Removed target {target_id} from database")
                        else:
                            logger.warning(f"Target {target_id} not found in database")
                else:
                    # Fallback to file removal
                    storage_path = f"surveillance_data/targets/{target_id}.json"
                    if os.path.exists(storage_path):
                        os.remove(storage_path)
                        logger.info(f"Removed target file {storage_path}")
                        
            except Exception as storage_error:
                logger.warning(f"Database removal failed: {storage_error}")
                # Try file system cleanup
                try:
                    storage_path = f"surveillance_data/targets/{target_id}.json"
                    if os.path.exists(storage_path):
                        os.remove(storage_path)
                        
                    # Also mark as deleted in backup
                    backup_path = f"surveillance_backup/deleted_{datetime.now().strftime('%Y%m%d')}.jsonl"
                    os.makedirs(os.path.dirname(backup_path), exist_ok=True)
                    
                    deletion_record = {
                        'target_id': target_id,
                        'deleted_at': datetime.now().isoformat(),
                        'reason': 'user_request'
                    }
                    
                    with open(backup_path, 'a') as f:
                        f.write(json.dumps(deletion_record) + '\n')
                        
                except Exception as file_error:
                    logger.error(f"File cleanup also failed: {file_error}")
            
            # Remove from active surveillance
            if hasattr(self, 'active_targets'):
                self.active_targets.discard(target_id)
            
            logger.debug(f"Successfully removed target {target_id}")
            
        except Exception as e:
            logger.error(f"Error removing target {target_id}: {str(e)}")
            raise
    
    async def _store_alert(self, alert: SurveillanceAlert) -> None:
        """Store alert in database."""
        try:
            logger.info(f"Storing surveillance alert: {alert.alert_id}")
            
            # Prepare alert data for storage
            alert_data = {
                'alert_id': alert.alert_id,
                'alert_type': alert.alert_type.value,
                'target_id': alert.target_id,
                'severity': alert.severity.value,
                'title': alert.title,
                'message': alert.message,
                'data': alert.data,
                'timestamp': alert.timestamp.isoformat(),
                'acknowledged': alert.acknowledged,
                'actions_taken': alert.actions_taken
            }
            
            # Store in local alert cache
            if not hasattr(self, 'alert_cache'):
                self.alert_cache = {}
            self.alert_cache[alert.alert_id] = alert_data
            
            # Persist to database if available
            try:
                if hasattr(self, 'database_connection') and self.database_connection:
                    async with self.database_connection.begin() as transaction:
                        await self.database_connection.execute(
                            """INSERT INTO surveillance_alerts 
                               (alert_id, alert_type, target_id, severity, title, 
                                message, data, timestamp, acknowledged, actions_taken)
                               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                            (alert_data['alert_id'], alert_data['alert_type'],
                             alert_data['target_id'], alert_data['severity'],
                             alert_data['title'], alert_data['message'],
                             json.dumps(alert_data['data']), alert_data['timestamp'],
                             alert_data['acknowledged'], json.dumps(alert_data['actions_taken']))
                        )
                        await transaction.commit()
                else:
                    # Fallback to file storage
                    alert_dir = f"surveillance_data/alerts/{datetime.now().strftime('%Y%m%d')}"
                    os.makedirs(alert_dir, exist_ok=True)
                    
                    alert_file = f"{alert_dir}/{alert.alert_id}.json"
                    with open(alert_file, 'w') as f:
                        json.dump(alert_data, f, indent=2)
                        
            except Exception as storage_error:
                logger.warning(f"Primary storage failed, using backup: {storage_error}")
                # Backup storage
                backup_path = f"surveillance_backup/alerts_{datetime.now().strftime('%Y%m%d')}.jsonl"
                os.makedirs(os.path.dirname(backup_path), exist_ok=True)
                
                with open(backup_path, 'a') as f:
                    f.write(json.dumps(alert_data) + '\n')
            
            # Trigger real-time notifications for high severity alerts
            if alert.severity in [AlertSeverity.HIGH, AlertSeverity.CRITICAL]:
                await self._send_real_time_notification(alert)
            
            # Update metrics
            if hasattr(self, 'metrics'):
                self.metrics['alerts_stored'] = self.metrics.get('alerts_stored', 0) + 1
                self.metrics[f'alerts_{alert.severity.value}'] = self.metrics.get(f'alerts_{alert.severity.value}', 0) + 1
            
            logger.debug(f"Successfully stored alert {alert.alert_id}")
            
        except Exception as e:
            logger.error(f"Error storing alert {alert.alert_id}: {str(e)}")
            raise
    
    async def _send_real_time_notification(self, alert: SurveillanceAlert) -> None:
        """Send real-time notification for critical alerts."""
        try:
            notification_data = {
                'alert_id': alert.alert_id,
                'severity': alert.severity.value,
                'title': alert.title,
                'message': alert.message[:200],  # Truncate for notification
                'timestamp': alert.timestamp.isoformat()
            }
            
            # Here you would integrate with notification services
            # For now, log the notification
            logger.warning(f"CRITICAL ALERT: {alert.title} - {alert.message}")
            
            # Could integrate with:
            # - Email notifications
            # - Slack/Teams webhooks
            # - SMS alerts
            # - Push notifications
            # - Dashboard real-time updates
            
        except Exception as e:
            logger.error(f"Error sending notification for alert {alert.alert_id}: {str(e)}")
    
    # Public interface methods
    def register_alert_handler(self, alert_type: AlertType, handler: Callable) -> None:
        """Register alert notification handler."""
        self.alert_handlers[alert_type] = handler
        logger.info(f"Alert handler registered for: {alert_type}")
    
    def register_threat_classifier(self, classifier: Callable) -> None:
        """Register threat classification function."""
        self.threat_classifiers.append(classifier)
        logger.info("Threat classifier registered")
    
    async def get_surveillance_status(self, target_id: str) -> Optional[Dict[str, Any]]:
        """Get surveillance status for target."""
        if target_id not in self.active_targets:
            return None
        
        target = self.active_targets[target_id]
        metrics = self.metrics.get(target_id)
        
        return {
            'target': target,
            'metrics': metrics,
            'is_monitoring': target_id in self.monitoring_tasks,
            'task_status': 'running' if target_id in self.monitoring_tasks else 'stopped'
        }
    
    async def get_all_surveillance_status(self) -> Dict[str, Any]:
        """
Get status of all surveillance targets."""
        status = {}
        
        for target_id in self.active_targets:
            status[target_id] = await self.get_surveillance_status(target_id)
        
        return {
            'targets': status,
            'total_targets': len(self.active_targets),
            'active_monitors': len(self.monitoring_tasks),
            'total_metrics': {
                'total_checks': sum(m.total_checks for m in self.metrics.values()),
                'total_alerts': sum(m.alerts_generated for m in self.metrics.values()),
                'total_threats': sum(m.threats_detected for m in self.metrics.values())
            }
        }
    
    async def cleanup(self) -> None:
        """
Cleanup surveillance engine resources."""
        # Stop all monitoring tasks
        for target_id in list(self.monitoring_tasks.keys()):
            await self._stop_target_monitoring(target_id)
        
        logger.info("Surveillance engine cleaned up")

class AlertNotificationManager:
    """
    Manages alert notifications across different channels.
    """
    
    def __init__(self):
        """
Initialize notification manager."""
        self.handlers = {}
        self.rate_limiters = {}
    
    async def send_email_alert(self, alert: SurveillanceAlert) -> bool:
        """
Send email alert notification."""
        try:
            # Implementation would send email
            logger.info(f"Email alert sent for: {alert.alert_id}")
            return True
        except Exception as e:
            logger.error(f"Email notification failed: {e}")
            return False
    
    async def send_sms_alert(self, alert: SurveillanceAlert) -> bool:
        """Send SMS alert notification."""
        try:
            # Implementation would send SMS
            logger.info(f"SMS alert sent for: {alert.alert_id}")
            return True
        except Exception as e:
            logger.error(f"SMS notification failed: {e}")
            return False
    
    async def send_webhook_alert(self, alert: SurveillanceAlert) -> bool:
        """Send webhook alert notification."""
        try:
            # Implementation would send webhook
            logger.info(f"Webhook alert sent for: {alert.alert_id}")
            return True
        except Exception as e:
            logger.error(f"Webhook notification failed: {e}")
            return False
    
    async def send_slack_alert(self, alert: SurveillanceAlert) -> bool:
        """Send Slack alert notification."""
        try:
            # Implementation would send to Slack
            logger.info(f"Slack alert sent for: {alert.alert_id}")
            return True
        except Exception as e:
            logger.error(f"Slack notification failed: {e}")
            return False

# Factory functions
def create_surveillance_engine(
    redis_client: Optional[redis.Redis] = None,
    celery_app: Optional[Celery] = None,
    db_session: Optional[AsyncSession] = None
) -> SurveillanceEngine:
    """Create surveillance engine with configuration."""
    return SurveillanceEngine(redis_client, celery_app, db_session)

def create_surveillance_target(
    user_id: str,
    name: str,
    description: str,
    target_urls: Optional[List[str]] = None,
    keywords: Optional[List[str]] = None,
    content_fingerprints: Optional[List[str]] = None,
    platforms: Optional[List[str]] = None,
    monitoring_frequency: MonitoringFrequency = MonitoringFrequency.HOURLY,
    alert_threshold: float = 0.7
) -> SurveillanceTarget:
    """
Create surveillance target configuration."""
    return SurveillanceTarget(
        target_id=str(uuid.uuid4()),
        user_id=user_id,
        name=name,
        description=description,
        target_urls=target_urls or [],
        keywords=keywords or [],
        content_fingerprints=content_fingerprints or [],
        platforms=platforms or [],
        monitoring_frequency=monitoring_frequency,
        alert_threshold=alert_threshold,
        threat_detection_enabled=True,
        automated_response=False,
        status=SurveillanceStatus.ACTIVE,
        created_at=datetime.now()
    )

def create_alert_notification_manager() -> AlertNotificationManager:
    """
Create alert notification manager."""
    return AlertNotificationManager()

# Export main components
__all__ = [
    'SurveillanceStatus',
    'ThreatLevel',
    'AlertType',
    'MonitoringFrequency',
    'SurveillanceTarget',
    'SurveillanceAlert',
    'ThreatAssessment',
    'MonitoringMetrics',
    'SurveillanceEngine',
    'AlertNotificationManager',
    'create_surveillance_engine',
    'create_surveillance_target',
    'create_alert_notification_manager',
]
