"""
Backend AI Module - Consolidated AI Agents System
================================================

This module provides a consolidated interface to all AI agents in the Ainflue platform.
Organizes 53+ specialized AI agents into 5 manageable files for improved maintainability.

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright (c) 2025 Fahed Mlaiel. All rights reserved.

⚠️  CRITICAL LEGAL NOTICE:
This code is the exclusive intellectual property of Fahed Mlaiel.
Unauthorized use is strictly prohibited. Contact: mlaiel@live.de
"""

from .agent_registry import AgentRegistry, get_agent, list_agents
from .core_business_agents import CoreBusinessAgents
from .content import ContentAgents, ContentProcessingResult, create_content_agents
from .technical_agents import TechnicalAgents

from .analytics import (
    AnalyticsHub,
    TrendAnalyzer,
    EngagementPredictor,
    AudienceAnalyzer,
    CompetitorMonitor,
    AnalyticsRequest,
    AnalyticsResponse,
    analyze_trends,
    predict_engagement,
    analyze_audience,
    monitor_competitors,
    comprehensive_analytics
)
from .conversational import (
    ConversationalAI,
    AIInteractionEngine,
    BusinessWorkflowAI,
    ContentCreatorAI,
    CollaborationAI,
    MonetizationAI,
    ProtectionAI,
    ConversationMode,
    ConversationState,
    ConversationContext,
    ConversationResponse,
    create_conversational_ai,
    create_ai_interaction_engine,
    create_business_workflow_ai,
    create_content_creator_ai,
    create_collaboration_ai,
    create_monetization_ai,
    create_protection_ai
)

from .nlp import (
    NLPPipeline,
    LanguageDetector,
    EntityRecognizer,
    IntentClassifier,
    SentimentAnalyzer,
    KeywordExtractor,
    TextSummarizer,
    TranslationEngine,
    ContentNLPProcessor,
    BusinessNLPProcessor,
    Entity,
    Intent,
    NLPResult,
    LanguageCode,
    EntityType,
    IntentType,
    create_nlp_pipeline,
    create_content_nlp_processor,
    create_business_nlp_processor
)

from .agents import (
    ConversationalAgentManager,
    BaseConversationalAgent,
    ChatOrchestrationAgent,
    BusinessAdvisorAgent,
    ContentCreatorAgent,
    CollaborationMatcherAgent,
    MonetizationAssistantAgent,
    ProtectionAdvisorAgent,
    AgentType,
    AgentCapability,
    AgentRequest,
    AgentResponse,
    create_conversational_agent_manager,
    create_chat_orchestration_agent,
    create_business_advisor_agent,
    create_content_creator_agent,
    create_collaboration_matcher_agent,
    create_monetization_assistant_agent,
    create_protection_advisor_agent
)

from .memory import (
    MemoryManager,
    InMemoryStorage,
    ConversationMemoryManager,
    ContextTracker,
    MemoryCleanupManager,
    MemoryEntry,
    ConversationContext,
    UserContext,
    MemoryType,
    ContextScope,
    MemoryPriority,
    create_in_memory_storage,
    create_conversation_memory_manager,
    create_context_tracker,
    create_memory_cleanup_manager
)

from .training import (
    ModelTrainer,
    FineTuningManager,
    ModelOptimizer,
    TrainingConfig,
    TrainingMetrics,
    TrainingJob,
    ModelType,
    TrainingStatus,
    OptimizationStrategy,
    create_model_trainer,
    create_fine_tuning_manager,
    create_model_optimizer
)

from .evaluation import (
    EvaluationEngine,
    MetricsCalculator,
    TestExecutor,
    PerformanceBenchmark,
    MetricResult,
    TestCase,
    TestResult,
    EvaluationSuite,
    EvaluationReport,
    MetricType,
    TestType,
    EvaluationStatus,
    create_evaluation_engine,
    create_metrics_calculator,
    create_test_executor,
    create_performance_benchmark
)

from .responses import (
    PersonalizedResponseGenerator,
    TemplateEngine,
    MultiModalResponseGenerator,
    ABTestingResponseEngine,
    BaseResponseGenerator,
    ResponseContext,
    ResponseCandidate,
    GeneratedResponse,
    ResponseTemplate,
    ResponseType,
    ResponseTone,
    PersonalizationLevel,
    ResponseQuality,
    create_personalized_response_generator,
    create_template_engine,
    create_multimodal_response_generator,
    create_ab_testing_response_engine
)

from .integrations import (
    IntegrationManager,
    WebhookManager,
    BaseServiceIntegration,
    SocialMediaIntegration,
    PaymentProcessorIntegration,
    AIServiceIntegration,
    EmailServiceIntegration,
    AnalyticsIntegration,
    ServiceCredentials,
    IntegrationConfig,
    APIResponse,
    WebhookEvent,
    ServiceType,
    IntegrationStatus,
    AuthenticationType,
    create_integration_manager,
    create_webhook_manager,
    create_social_media_integration,
    create_payment_processor_integration,
    create_ai_service_integration,
    create_email_service_integration,
    create_analytics_integration
)

from .human_services import (
    CompanionService,
    ICompanionService,
    CompanionPersonalityType,
    TherapyAIService,
    TherapySessionType,
    WellbeingStatus,
    TherapySession,
    EducationAIService,
    IEducationAIService,
    CourseType,
    DifficultyLevel,
    LearningStyle,
    Course,
    StudentProfile,
    create_companion_service,
    create_therapy_service,
    create_education_service,
    create_friendly_companion,
    create_professional_companion,
    create_creative_companion,
    create_mentor_companion,
    create_content_creator_tutor,
    create_business_development_tutor
)

from .specialized_agents import (
    PersonalityAgents,
    BasePersonalityAgent,
    FashionExpertAgent,
    FitnessCoachAgent,
    TechReviewerAgent,
    FoodCriticAgent,
    SpecialtyAgents,
    BaseSpecialtyAgent,
    AudioSpecialistAgent,
    VideoSpecialistAgent,
    ImageSpecialistAgent,
    TextSpecialistAgent,
    EngagementSpecialistAgent,
    PersonalityType,
    ExpertiseLevel,
    PersonalityTone,
    SpecialtyType,
    SpecializationLevel,
    PersonalityProfile,
    PersonalityResponse,
    SpecialtyResult,
    create_personality_agents,
    create_specialty_agents,
    create_fashion_expert,
    create_fitness_coach,
    create_tech_reviewer,
    create_food_critic
)

__version__ = "1.0.0"
__author__ = "Fahed Mlaiel"
__email__ = "mlaiel@live.de"

__all__ = [
    "AgentRegistry",
    "get_agent", 
    "list_agents",
    "CoreBusinessAgents",
    "ContentAgents",
    "ContentProcessingResult",
    "create_content_agents",
    "TechnicalAgents",
    
    # Analytics Agents - Data Analysis and Insights
    "AnalyticsHub",
    "TrendAnalyzer",
    "EngagementPredictor",
    "AudienceAnalyzer",
    "CompetitorMonitor",
    "AnalyticsRequest",
    "AnalyticsResponse",
    "analyze_trends",
    "predict_engagement",
    "analyze_audience",
    "monitor_competitors",
    "comprehensive_analytics",
    
    # Conversational AI Core
    "ConversationalAI",
    "AIInteractionEngine",
    "BusinessWorkflowAI",
    "ContentCreatorAI",
    "CollaborationAI",
    "MonetizationAI",
    "ProtectionAI",
    "ConversationMode",
    "ConversationState",
    "ConversationContext",
    "ConversationResponse",
    "create_conversational_ai",
    "create_ai_interaction_engine",
    "create_business_workflow_ai",
    "create_content_creator_ai",
    "create_collaboration_ai",
    "create_monetization_ai",
    "create_protection_ai",
    
    # NLP Processing
    "NLPPipeline",
    "LanguageDetector",
    "EntityRecognizer",
    "IntentClassifier",
    "SentimentAnalyzer",
    "KeywordExtractor",
    "TextSummarizer",
    "TranslationEngine",
    "ContentNLPProcessor",
    "BusinessNLPProcessor",
    "Entity",
    "Intent",
    "NLPResult",
    "LanguageCode",
    "EntityType",
    "IntentType",
    "create_nlp_pipeline",
    "create_content_nlp_processor",
    "create_business_nlp_processor",
    
    # Conversational Agents
    "ConversationalAgentManager",
    "BaseConversationalAgent",
    "ChatOrchestrationAgent",
    "BusinessAdvisorAgent",
    "ContentCreatorAgent",
    "CollaborationMatcherAgent",
    "MonetizationAssistantAgent",
    "ProtectionAdvisorAgent",
    "AgentType",
    "AgentCapability",
    "AgentRequest",
    "AgentResponse",
    "create_conversational_agent_manager",
    "create_chat_orchestration_agent",
    "create_business_advisor_agent",
    "create_content_creator_agent",
    "create_collaboration_matcher_agent",
    "create_monetization_assistant_agent",
    "create_protection_advisor_agent",
    
    # Memory and Context Management
    "MemoryManager",
    "InMemoryStorage",
    "ConversationMemoryManager",
    "ContextTracker",
    "MemoryCleanupManager",
    "MemoryEntry",
    "UserContext",
    "MemoryType",
    "ContextScope",
    "MemoryPriority",
    "create_in_memory_storage",
    "create_conversation_memory_manager",
    "create_context_tracker",
    "create_memory_cleanup_manager",
    
    # Model Training and Fine-tuning
    "ModelTrainer",
    "FineTuningManager",
    "ModelOptimizer",
    "TrainingConfig",
    "TrainingMetrics",
    "TrainingJob",
    "ModelType",
    "TrainingStatus",
    "OptimizationStrategy",
    "create_model_trainer",
    "create_fine_tuning_manager",
    "create_model_optimizer",
    
    # Evaluation and Testing
    "EvaluationEngine",
    "MetricsCalculator",
    "TestExecutor",
    "PerformanceBenchmark",
    "MetricResult",
    "TestCase",
    "TestResult",
    "EvaluationSuite",
    "EvaluationReport",
    "MetricType",
    "TestType",
    "EvaluationStatus",
    "create_evaluation_engine",
    "create_metrics_calculator",
    "create_test_executor",
    "create_performance_benchmark",
    
    # Response Generation
    "PersonalizedResponseGenerator",
    "TemplateEngine",
    "MultiModalResponseGenerator",
    "ABTestingResponseEngine",
    "BaseResponseGenerator",
    "ResponseContext",
    "ResponseCandidate",
    "GeneratedResponse",
    "ResponseTemplate",
    "ResponseType",
    "ResponseTone",
    "PersonalizationLevel",
    "ResponseQuality",
    "create_personalized_response_generator",
    "create_template_engine",
    "create_multimodal_response_generator",
    "create_ab_testing_response_engine",
    
    # External Service Integrations
    "IntegrationManager",
    "WebhookManager",
    "BaseServiceIntegration",
    "SocialMediaIntegration",
    "PaymentProcessorIntegration",
    "AIServiceIntegration",
    "EmailServiceIntegration",
    "AnalyticsIntegration",
    "ServiceCredentials",
    "IntegrationConfig",
    "APIResponse",
    "WebhookEvent",
    "ServiceType",
    "IntegrationStatus",
    "AuthenticationType",
    "create_integration_manager",
    "create_webhook_manager",
    "create_social_media_integration",
    "create_payment_processor_integration",
    "create_ai_service_integration",
    "create_email_service_integration",
    "create_analytics_integration",
    
    # Human-Centric Services
    "CompanionService",
    "ICompanionService",
    "CompanionPersonalityType",
    "TherapyAIService",
    "TherapySessionType",
    "WellbeingStatus",
    "TherapySession",
    "EducationAIService",
    "IEducationAIService",
    "CourseType",
    "DifficultyLevel",
    "LearningStyle",
    "Course",
    "StudentProfile",
    "create_companion_service",
    "create_therapy_service",
    "create_education_service",
    "create_friendly_companion",
    "create_professional_companion",
    "create_creative_companion",
    "create_mentor_companion",
    "create_content_creator_tutor",
    "create_business_development_tutor",
    
    # Specialized AI Personalities and Capabilities
    "PersonalityAgents",
    "BasePersonalityAgent",
    "FashionExpertAgent",
    "FitnessCoachAgent",
    "TechReviewerAgent",
    "FoodCriticAgent",
    "SpecialtyAgents",
    "BaseSpecialtyAgent",
    "AudioSpecialistAgent",
    "VideoSpecialistAgent",
    "ImageSpecialistAgent",
    "TextSpecialistAgent",
    "EngagementSpecialistAgent",
    "PersonalityType",
    "ExpertiseLevel",
    "PersonalityTone",
    "SpecialtyType",
    "SpecializationLevel",
    "PersonalityProfile",
    "PersonalityResponse",
    "SpecialtyResult",
    "create_personality_agents",
    "create_specialty_agents",
    "create_fashion_expert",
    "create_fitness_coach",
    "create_tech_reviewer",
    "create_food_critic"
]