# 🔒 SECURE CONFIGURATION TEMPLATE
# Generated by Security Expert

# Security Headers
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "X-XSS-Protection": "1; mode=block",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "Content-Security-Policy": "default-src 'self'",
    "Referrer-Policy": "strict-origin-when-cross-origin"
}

# Rate Limiting
RATE_LIMIT_SETTINGS = {
    "default": "100/minute",
    "api": "1000/hour",
    "auth": "5/minute"
}

# Session Security
SESSION_SECURITY = {
    "secure": True,
    "httponly": True,
    "samesite": "strict",
    "max_age": 3600
}

# Password Requirements
PASSWORD_POLICY = {
    "min_length": 12,
    "require_uppercase": True,
    "require_lowercase": True,
    "require_numbers": True,
    "require_symbols": True,
    "max_age_days": 90
}

# Encryption Settings
ENCRYPTION_CONFIG = {
    "algorithm": "AES-256-GCM",
    "key_rotation_days": 30,
    "backup_keys_count": 3
}
