apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8001'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: content-upload-service
    environment: development
    service-type: content-service
  name: content-upload-service
  namespace: ainflue-development
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: content-upload-service
  type: ClusterIP
