apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: content-processing-service
    service-type: content-service
  name: content-processing-service-sa
  namespace: ainflue-production
spec: {}
