apiVersion: v1
kind: Namespace
metadata:
  annotations:
    contact: mlaiel@live.de
    description: Ainflue microservices - production
  labels:
    environment: production
    managed-by: enterprise-orchestrator
    project: ainflue
  name: ainflue-production
spec: {}
