apiVersion: v1
data:
  sampling_strategies.json: "{\n  \"default_strategy\": {\n    \"type\": \"probabilistic\"\
    ,\n    \"param\": 0.1\n  },\n  \"per_service_strategies\": [\n    {\n      \"\
    service\": \"ainflue-api\",\n      \"type\": \"probabilistic\",\n      \"param\"\
    : 0.5\n    },\n    {\n      \"service\": \"ainflue-ai-engine\",\n      \"type\"\
    : \"probabilistic\",\n      \"param\": 1.0\n    },\n    {\n      \"service\":\
    \ \"ainflue-auth\",\n      \"type\": \"ratelimiting\",\n      \"param\": 100\n\
    \    }\n  ],\n  \"per_operation_strategies\": [\n    {\n      \"service\": \"\
    ainflue-api\",\n      \"operation\": \"POST /upload\",\n      \"type\": \"probabilistic\"\
    ,\n      \"param\": 1.0\n    },\n    {\n      \"service\": \"ainflue-api\",\n\
    \      \"operation\": \"GET /health\",\n      \"type\": \"probabilistic\",\n \
    \     \"param\": 0.01\n    }\n  ]\n}"
kind: ConfigMap
metadata:
  name: jaeger-sampling
  namespace: jaeger-system
