"""Guardian tables 644 languages

Revision ID: 68bf4dfb8c07
Revises: 
Create Date: 2025-10-12 22:26:20.066087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf4dfb8c07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'COORDINATOR', 'VOLUNTEER', 'GUEST', name='userrole'), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('bio_translations', sa.JSON(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('spoken_languages', sa.JSON(), nullable=True),
    sa.Column('language_proficiency', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('ban_reason_translations', sa.JSON(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('background_check_completed', sa.Boolean(), nullable=True),
    sa.Column('background_check_date', sa.DateTime(), nullable=True),
    sa.Column('total_missions', sa.Integer(), nullable=True),
    sa.Column('completed_missions', sa.Integer(), nullable=True),
    sa.Column('total_hours_volunteered', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=True),
    sa.Column('show_location', sa.Boolean(), nullable=True),
    sa.Column('show_contact', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'MISSION_CREATED', 'MISSION_UPDATED', 'MISSION_DELETED', 'MISSION_PUBLISHED', 'MISSION_COMPLETED', 'VOLUNTEER_APPLIED', 'VOLUNTEER_ACCEPTED', 'VOLUNTEER_REJECTED', 'VOLUNTEER_WITHDRAWN', 'MESSAGE_SENT', 'MESSAGE_DELETED', 'MESSAGE_EDITED', 'MESSAGE_FLAGGED', 'FILE_UPLOADED', 'FILE_DOWNLOADED', 'FILE_DELETED', 'STREAM_STARTED', 'STREAM_ENDED', 'CONTENT_MODERATED', 'USER_BANNED', 'USER_UNBANNED', 'USER_WARNED', 'SUSPICIOUS_ACTIVITY', 'RATE_LIMIT_EXCEEDED', 'UNAUTHORIZED_ACCESS', 'SETTINGS_CHANGED', 'USER_ROLE_CHANGED', 'PERMISSION_CHANGED', name='auditeventtype'), nullable=True),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='auditseverity'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'LOCATION', 'SYSTEM', name='messagetype'), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('content_translations', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_by_recipient', sa.Boolean(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=True),
    sa.Column('moderation_result', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_messages_id'), 'direct_messages', ['id'], unique=False)
    op.create_index(op.f('ix_direct_messages_message_id'), 'direct_messages', ['message_id'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_code', sa.String(length=50), nullable=True),
    sa.Column('title_translations', sa.JSON(), nullable=False),
    sa.Column('description_translations', sa.JSON(), nullable=False),
    sa.Column('requirements_translations', sa.JSON(), nullable=True),
    sa.Column('objectives_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('mission_type', sa.Enum('HUMANITARIAN', 'ENVIRONMENTAL', 'EDUCATION', 'HEALTH', 'COMMUNITY', 'EMERGENCY', 'DEVELOPMENT', 'OTHER', name='missiontype'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='missionstatus'), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_translations', sa.JSON(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.Column('partner_organization', sa.String(length=200), nullable=True),
    sa.Column('partner_organization_translations', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('volunteers_needed', sa.Integer(), nullable=True),
    sa.Column('volunteers_registered', sa.Integer(), nullable=True),
    sa.Column('volunteers_confirmed', sa.Integer(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('budget_required', sa.Float(), nullable=True),
    sa.Column('budget_secured', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('success_indicators_translations', sa.JSON(), nullable=True),
    sa.Column('expected_impact_translations', sa.JSON(), nullable=True),
    sa.Column('identified_risks_translations', sa.JSON(), nullable=True),
    sa.Column('safety_measures_translations', sa.JSON(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_email', sa.String(length=200), nullable=True),
    sa.Column('social_media_links', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('applications_count', sa.Integer(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_impact_score', sa.Float(), nullable=True),
    sa.Column('accessibility_features', sa.JSON(), nullable=True),
    sa.Column('disability_friendly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_mission_code'), 'missions', ['mission_code'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=50), nullable=True),
    sa.Column('room_type', sa.Enum('PUBLIC', 'PRIVATE', 'MISSION', 'DIRECT', 'GROUP', name='chatroomtype'), nullable=True),
    sa.Column('name_translations', sa.JSON(), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('admins', sa.JSON(), nullable=True),
    sa.Column('banned_users', sa.JSON(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('allow_files', sa.Boolean(), nullable=True),
    sa.Column('allow_voice', sa.Boolean(), nullable=True),
    sa.Column('allow_video', sa.Boolean(), nullable=True),
    sa.Column('auto_translate', sa.Boolean(), nullable=True),
    sa.Column('supported_languages', sa.JSON(), nullable=True),
    sa.Column('moderation_enabled', sa.Boolean(), nullable=True),
    sa.Column('profanity_filter', sa.Boolean(), nullable=True),
    sa.Column('spam_protection', sa.Boolean(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('active_members_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_room_code'), 'chat_rooms', ['room_code'], unique=True)
    op.create_table('live_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(length=50), nullable=True),
    sa.Column('streamer_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('title_translations', sa.JSON(), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('stream_key', sa.String(length=100), nullable=True),
    sa.Column('rtmp_url', sa.String(length=500), nullable=True),
    sa.Column('hls_url', sa.String(length=500), nullable=True),
    sa.Column('quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='streamquality'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'PAUSED', 'ENDED', 'FAILED', name='streamstatus'), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('auto_captions_enabled', sa.Boolean(), nullable=True),
    sa.Column('available_caption_languages', sa.JSON(), nullable=True),
    sa.Column('real_time_translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('translation_languages', sa.JSON(), nullable=True),
    sa.Column('viewers_count', sa.Integer(), nullable=True),
    sa.Column('max_viewers', sa.Integer(), nullable=True),
    sa.Column('viewer_list', sa.JSON(), nullable=True),
    sa.Column('chat_enabled', sa.Boolean(), nullable=True),
    sa.Column('moderation_enabled', sa.Boolean(), nullable=True),
    sa.Column('moderators', sa.JSON(), nullable=True),
    sa.Column('is_recorded', sa.Boolean(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['streamer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_key')
    )
    op.create_index(op.f('ix_live_streams_id'), 'live_streams', ['id'], unique=False)
    op.create_index(op.f('ix_live_streams_stream_id'), 'live_streams', ['stream_id'], unique=True)
    op.create_table('video_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=50), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('name_translations', sa.JSON(), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('waiting_room', sa.JSON(), nullable=True),
    sa.Column('real_time_translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('participant_languages', sa.JSON(), nullable=True),
    sa.Column('captions_enabled', sa.Boolean(), nullable=True),
    sa.Column('recording_enabled', sa.Boolean(), nullable=True),
    sa.Column('screen_sharing_enabled', sa.Boolean(), nullable=True),
    sa.Column('chat_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_rooms_id'), 'video_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_video_rooms_room_id'), 'video_rooms', ['room_id'], unique=True)
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_code', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'REVIEWING', 'ACCEPTED', 'REJECTED', 'ACTIVE', 'COMPLETED', 'WITHDRAWN', name='volunteerstatus'), nullable=True),
    sa.Column('motivation_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('skills_translations', sa.JSON(), nullable=True),
    sa.Column('skills_list', sa.JSON(), nullable=True),
    sa.Column('experience_translations', sa.JSON(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('spoken_languages', sa.JSON(), nullable=True),
    sa.Column('language_proficiency', sa.JSON(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('available_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('current_country', sa.String(length=100), nullable=True),
    sa.Column('current_city', sa.String(length=100), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('willing_to_travel', sa.Boolean(), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('cover_letter_url', sa.String(length=500), nullable=True),
    sa.Column('certificates', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('background_check_completed', sa.Boolean(), nullable=True),
    sa.Column('background_check_date', sa.DateTime(), nullable=True),
    sa.Column('background_check_status', sa.String(length=50), nullable=True),
    sa.Column('training_completed', sa.JSON(), nullable=True),
    sa.Column('training_required', sa.JSON(), nullable=True),
    sa.Column('orientation_completed', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('feedback_translations', sa.JSON(), nullable=True),
    sa.Column('missions_completed', sa.Integer(), nullable=True),
    sa.Column('total_hours_volunteered', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('medical_conditions_translations', sa.JSON(), nullable=True),
    sa.Column('allergies_translations', sa.JSON(), nullable=True),
    sa.Column('special_requirements_translations', sa.JSON(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=200), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('preferred_mission_types', sa.JSON(), nullable=True),
    sa.Column('preferred_regions', sa.JSON(), nullable=True),
    sa.Column('work_style_preferences', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decision_made_at', sa.DateTime(), nullable=True),
    sa.Column('decision_by', sa.Integer(), nullable=True),
    sa.Column('decision_notes_translations', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_index(op.f('ix_volunteers_volunteer_code'), 'volunteers', ['volunteer_code'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('chat_room_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'LOCATION', 'SYSTEM', name='messagetype'), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('content_translations', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=True),
    sa.Column('moderation_result', sa.JSON(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flagged_by', sa.JSON(), nullable=True),
    sa.Column('flagged_reason_translations', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edit_history', sa.JSON(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=True)
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('chat_room_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'ARCHIVE', 'OTHER', name='filetype'), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_size_human', sa.String(length=20), nullable=True),
    sa.Column('description_translations', sa.JSON(), nullable=True),
    sa.Column('tags_translations', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='filestatus'), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=True),
    sa.Column('moderation_result', sa.JSON(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('allowed_users', sa.JSON(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_file_hash'), 'file_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_id'), 'file_uploads', ['file_id'], unique=True)
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_hash'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_volunteers_volunteer_code'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_video_rooms_room_id'), table_name='video_rooms')
    op.drop_index(op.f('ix_video_rooms_id'), table_name='video_rooms')
    op.drop_table('video_rooms')
    op.drop_index(op.f('ix_live_streams_stream_id'), table_name='live_streams')
    op.drop_index(op.f('ix_live_streams_id'), table_name='live_streams')
    op.drop_table('live_streams')
    op.drop_index(op.f('ix_chat_rooms_room_code'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_missions_mission_code'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_direct_messages_message_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_id'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
