#!/usr/bin/env python3
"""
🔒 SECURITY HARDENING IMPLEMENTATION
===================================

Comprehensive security audit and hardening implementation.

Author: Security Expert
"""

import os
import re
import json
import hashlib
import subprocess
from typing import Dict, List, Any, Optional
from pathlib import Path
import logging

class SecurityHardening:
    """Comprehensive security hardening system"""
    
    def __init__(self, base_path: str = "."):
        self.base_path = Path(base_path)
        self.logger = logging.getLogger(self.__class__.__name__)
        self.vulnerabilities_found = []
        self.fixes_applied = []
        
    def audit_security(self) -> Dict[str, Any]:
        """Perform comprehensive security audit"""
        audit_results = {
            "vulnerabilities": [],
            "critical_issues": [],
            "recommendations": [],
            "hardening_applied": []
        }
        
        # Scan for common vulnerabilities
        self._scan_hardcoded_secrets(audit_results)
        self._scan_sql_injection_risks(audit_results)
        self._scan_insecure_configurations(audit_results)
        self._apply_security_hardening(audit_results)
        
        return audit_results
    
    def _scan_hardcoded_secrets(self, results: Dict[str, Any]) -> None:
        """Scan for hardcoded secrets and API keys"""
        secret_patterns = [
            r'(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*["\']([^"\']{8,})["\']',
            r'(?i)(aws_access_key|aws_secret|database_url)\s*[:=]\s*["\']([^"\']{8,})["\']',
            r'(?i)(github_token|stripe_key|openai_key)\s*[:=]\s*["\']([^"\']{8,})["\']'
        ]
        
        for py_file in self.base_path.rglob("*.py"):
            try:
                content = py_file.read_text()
                for pattern in secret_patterns:
                    matches = re.findall(pattern, content)
                    for match in matches:
                        if len(match) > 1 and not self._is_safe_value(match[1]):
                            vulnerability = {
                                "type": "hardcoded_secret",
                                "severity": "critical",
                                "file": str(py_file),
                                "line": self._find_line_number(content, match[0]),
                                "description": f"Hardcoded {match[0]} found"
                            }
                            results["vulnerabilities"].append(vulnerability)
                            results["critical_issues"].append(vulnerability)
            except Exception as e:
                self.logger.warning(f"Could not scan {py_file}: {e}")
    
    def _scan_sql_injection_risks(self, results: Dict[str, Any]) -> None:
        """Scan for SQL injection vulnerabilities"""
        sql_patterns = [
            r'(?i)execute\s*\(\s*["\'].*?%s.*?["\']',
            r'(?i)query\s*\(\s*["\'].*?\+.*?["\']',
            r'(?i)SELECT.*?WHERE.*?\+.*?["\']'
        ]
        
        for py_file in self.base_path.rglob("*.py"):
            try:
                content = py_file.read_text()
                for pattern in sql_patterns:
                    if re.search(pattern, content):
                        vulnerability = {
                            "type": "sql_injection_risk",
                            "severity": "high",
                            "file": str(py_file),
                            "description": "Potential SQL injection vulnerability"
                        }
                        results["vulnerabilities"].append(vulnerability)
            except Exception as e:
                self.logger.warning(f"Could not scan {py_file}: {e}")
    
    def _scan_insecure_configurations(self, results: Dict[str, Any]) -> None:
        """Scan for insecure configurations"""
        # Check environment files
        for env_file in self.base_path.glob(".env*"):
            try:
                content = env_file.read_text()
                if "DEBUG=True" in content or "DEBUG=true" in content:
                    vulnerability = {
                        "type": "insecure_config",
                        "severity": "medium",
                        "file": str(env_file),
                        "description": "Debug mode enabled in production"
                    }
                    results["vulnerabilities"].append(vulnerability)
            except Exception as e:
                self.logger.warning(f"Could not scan {env_file}: {e}")
    
    def _apply_security_hardening(self, results: Dict[str, Any]) -> None:
        """Apply security hardening measures"""
        
        # Create secure configuration template
        secure_config = '''# 🔒 SECURE CONFIGURATION TEMPLATE
# Generated by Security Expert

# Security Headers
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "X-XSS-Protection": "1; mode=block",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "Content-Security-Policy": "default-src 'self'",
    "Referrer-Policy": "strict-origin-when-cross-origin"
}

# Rate Limiting
RATE_LIMIT_SETTINGS = {
    "default": "100/minute",
    "api": "1000/hour",
    "auth": "5/minute"
}

# Session Security
SESSION_SECURITY = {
    "secure": True,
    "httponly": True,
    "samesite": "strict",
    "max_age": 3600
}

# Password Requirements
PASSWORD_POLICY = {
    "min_length": 12,
    "require_uppercase": True,
    "require_lowercase": True,
    "require_numbers": True,
    "require_symbols": True,
    "max_age_days": 90
}

# Encryption Settings
ENCRYPTION_CONFIG = {
    "algorithm": "AES-256-GCM",
    "key_rotation_days": 30,
    "backup_keys_count": 3
}
'''
        
        config_path = self.base_path / "security" / "hardened_config.py"
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(secure_config)
        
        results["hardening_applied"].append("Created secure configuration template")
        
        # Create security middleware
        middleware_code = '''#!/usr/bin/env python3
"""
🔒 SECURITY MIDDLEWARE
=====================

Security middleware for request validation and protection.
"""

import time
import hashlib
import hmac
from typing import Dict, Any, Optional
from datetime import datetime, timedelta

class SecurityMiddleware:
    """Security middleware for request protection"""
    
    def __init__(self):
        self.rate_limits: Dict[str, List[datetime]] = {}
        self.blocked_ips: set = set()
        self.security_headers = {
            "X-Content-Type-Options": "nosniff",
            "X-Frame-Options": "DENY",
            "X-XSS-Protection": "1; mode=block",
            "Strict-Transport-Security": "max-age=31536000; includeSubDomains"
        }
    
    def validate_request(self, request_data: Dict[str, Any]) -> Dict[str, Any]:
        """Validate incoming request for security threats"""
        
        client_ip = request_data.get("client_ip", "unknown")
        
        # Check if IP is blocked
        if client_ip in self.blocked_ips:
            return {"allowed": False, "reason": "IP blocked"}
        
        # Check rate limiting
        if not self._check_rate_limit(client_ip):
            return {"allowed": False, "reason": "Rate limit exceeded"}
        
        # Validate input
        if not self._validate_input(request_data.get("data", {})):
            return {"allowed": False, "reason": "Invalid input detected"}
        
        return {"allowed": True, "headers": self.security_headers}
    
    def _check_rate_limit(self, client_ip: str, limit: int = 100) -> bool:
        """Check rate limiting for client IP"""
        now = datetime.now()
        
        if client_ip not in self.rate_limits:
            self.rate_limits[client_ip] = []
        
        # Remove old requests
        cutoff_time = now - timedelta(minutes=1)
        self.rate_limits[client_ip] = [
            req_time for req_time in self.rate_limits[client_ip]
            if req_time > cutoff_time
        ]
        
        # Check if under limit
        if len(self.rate_limits[client_ip]) >= limit:
            return False
        
        self.rate_limits[client_ip].append(now)
        return True
    
    def _validate_input(self, data: Dict[str, Any]) -> bool:
        """Validate input data for malicious content"""
        
        dangerous_patterns = [
            r'<script[^>]*>.*?</script>',  # XSS
            r'javascript:',                # JavaScript injection
            r'on\w+\s*=',                 # Event handlers
            r'(?i)(union|select|insert|update|delete|drop)\s+',  # SQL injection
            r'\.\./',                     # Path traversal
        ]
        
        def check_value(value):
            if isinstance(value, str):
                for pattern in dangerous_patterns:
                    if re.search(pattern, value):
                        return False
            elif isinstance(value, dict):
                return all(check_value(v) for v in value.values())
            elif isinstance(value, list):
                return all(check_value(item) for item in value)
            return True
        
        return check_value(data)

# Global security middleware
security_middleware = SecurityMiddleware()
'''
        
        middleware_path = self.base_path / "security" / "middleware.py"
        middleware_path.write_text(middleware_code)
        
        results["hardening_applied"].append("Created security middleware")
        
        # Add recommendations
        results["recommendations"].extend([
            "Implement regular security audits",
            "Use environment variables for all secrets",
            "Enable HTTPS only in production",
            "Implement proper session management",
            "Regular dependency vulnerability scanning",
            "Implement proper logging and monitoring"
        ])
    
    def _is_safe_value(self, value: str) -> bool:
        """Check if a value is a safe placeholder"""
        safe_patterns = [
            "your_api_key_here", "example", "test", "placeholder",
            "change_me", "secret_key_here", "xxx", "yyy"
        ]
        return any(pattern in value.lower() for pattern in safe_patterns)
    
    def _find_line_number(self, content: str, search_text: str) -> int:
        """Find line number for given text"""
        lines = content.split('\n')
        for i, line in enumerate(lines, 1):
            if search_text in line:
                return i
        return 0

# Execute security audit
if __name__ == "__main__":
    security = SecurityHardening()
    results = security.audit_security()
    
    with open("SECURITY_AUDIT_RESULTS.json", "w") as f:
        json.dump(results, f, indent=2)
    
    print(f"🔒 Security audit completed")
    print(f"📊 Vulnerabilities found: {len(results['vulnerabilities'])}")
    print(f"🚨 Critical issues: {len(results['critical_issues'])}")
    print(f"✅ Hardening applied: {len(results['hardening_applied'])}")