"""Backend Mobile Services
Mobile-specific backend services and integrations

Enterprise Mobile Backend Architecture implementing:
- Creator Multi-Format Upload Integration
- Mobile Content Orchestration  
- Mobile-Optimized Media Processing
- Creator Workflow Mobile Integration
- IA Processing Mobile Integration

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright: (c) 2025 Fahed Mlaiel. All rights reserved.
"""

# Original mobile services
from .push_notifications import PushNotificationService, NotificationPriority, NotificationType
from .offline_sync import OfflineSyncManager, SyncStrategy, ConflictResolution

# Phase 1: Creator Mobile Workflow Core (CRITICAL PRIORITY)
from .mobile_content_orchestrator import (
    MobileContentOrchestrator,
    MobileContentRequest, 
    WorkflowStatus,
    CreatorType,
    WorkflowStage,
    MobileOptimization
)

from .creator_upload_manager import (
    CreatorUploadManager,
    UploadRequest,
    UploadProgress,
    CreatorUploadSettings,
    ContentFormat,
    UploadStatus,
    UploadMethod
)

from .mobile_media_processor import (
    MobileMediaProcessor,
    ProcessingRequest,
    ProcessingResult,
    MobileProcessingSettings,
    QualityLevel,
    MobileFormat,
    ProcessingStatus
)

from .creator_workflow_mobile import (
    CreatorWorkflowMobile,
    CreatorWorkflowState,
    MobileWorkflowConfiguration,
    MobileWorkflowEvent,
    WorkflowEvent
)

# Phase 2: IA Processing Mobile Integration (CRITICAL)
from .mobile_ai_orchestrator import (
    MobileAIOrchestrator,
    AIProcessingRequest,
    AIProcessingResult,
    MobileAISettings,
    AIProcessingType,
    AIModelSize,
    ProcessingPriority
)

from .content_intelligence_mobile import (
    ContentIntelligenceMobile,
    ContentAnalysisRequest,
    ContentInsights,
    AutoGeneratedMetadata,
    TrendAnalysis,
    ContentCategory,
    ContentMood,
    ContentComplexity
)

from .ai_analysis_mobile import (
    AIAnalysisMobile,
    MobileAnalysisRequest,
    ComprehensiveAnalysisResult,
    VisualAnalysisResult,
    AudioAnalysisResult,
    TextAnalysisResult,
    PatternAnalysisResult,
    AnalysisConfiguration,
    AnalysisType,
    AnalysisComplexity
)

from .mobile_ai_cache_manager import (
    MobileAICacheManager,
    CacheEntry,
    CacheConfiguration,
    CachePerformanceMetrics,
    CacheStrategy,
    CacheLevel,
    CachePriority
)

# Phase 3: Content Protection Mobile (CRITICAL)
from .mobile_protection_orchestrator import (
    MobileProtectionOrchestrator,
    MobileProtectionRequest,
    MobileProtectionResult,
    MobileProtectionConfiguration,
    MobileProtectionMode,
    MobileDeviceType,
    MobileNetworkType
)

from .fingerprint_mobile_engine import (
    MobileFingerprintEngine,
    MobileFingerprintRequest,
    MobileFingerprintResult,
    MobileFingerprintConfig,
    MobileFingerprintType,
    MobileContentType,
    MobileFingerprintQuality
)

from .watermark_mobile_processor import (
    MobileWatermarkProcessor,
    MobileWatermarkRequest,
    MobileWatermarkResult,
    MobileWatermarkConfig,
    MobileWatermarkType,
    MobileWatermarkStrength,
    MobileWatermarkPosition
)

from .violation_alert_mobile import (
    MobileViolationAlertSystem,
    MobileViolationEvent,
    MobileAlertRequest,
    MobileAlertResult,
    MobileAlertConfiguration,
    MobileViolationType,
    MobileAlertSeverity,
    MobileAlertChannel
)

# Phase 4: SEO & Distribution Mobile (CRITICAL)
from .mobile_seo_orchestrator import (
    MobileSEOOrchestrator,
    MobileSEORequest,
    MobileSEOResult,
    MobileSEOConfiguration,
    MobileSEOStrategy,
    MobilePlatformType,
    MobileContentCategory,
    MobileDeviceOptimization,
    create_mobile_seo_orchestrator
)

from .platform_adapter_mobile import (
    MobilePlatformAdapter,
    MobilePlatformRequest,
    MobilePlatformAdaptationResult,
    PlatformAdaptationResult,
    MobilePlatformConfiguration,
    MobilePlatformType,
    MobileAdaptationType,
    MobileDeviceCategory,
    ContentOptimizationLevel,
    create_mobile_platform_adapter
)

from .metadata_optimizer_mobile import (
    MobileMetadataOptimizer,
    MobileMetadataRequest,
    MobileMetadataResult,
    OptimizedMetadata,
    MobileMetadataConfiguration,
    MobileMetadataType,
    MetadataOptimizationStrategy,
    MobileMetadataFormat,
    create_mobile_metadata_optimizer
)

from .trending_analyzer_mobile import (
    MobileTrendingAnalyzer,
    MobileTrendRequest,
    MobileTrendResult,
    TrendInsight,
    MobileTrendConfiguration,
    TrendAnalysisType,
    TrendScope,
    TrendTimeframe,
    ViralPotential,
    create_mobile_trending_analyzer
)

from .engagement_predictor_mobile import (
    MobileEngagementPredictor,
    MobileEngagementRequest,
    MobileEngagementResult,
    EngagementPrediction,
    MobileEngagementConfiguration,
    EngagementMetric,
    PredictionModel,
    create_mobile_engagement_predictor
)

from .distribution_manager_mobile import (
    MobileDistributionManager,
    MobileDistributionRequest,
    MobileDistributionResult,
    PlatformDistributionResult,
    MobileDistributionConfiguration,
    DistributionStrategy,
    DistributionStatus
)

from .social_optimizer_mobile import (
    MobileSocialOptimizer,
    MobileSocialRequest,
    MobileSocialResult,
    SocialPlatformOptimization,
    MobileSocialConfiguration,
    SocialPlatform,
    SocialOptimizationType
)

from .audience_targeting_mobile import (
    MobileAudienceTargeting,
    MobileAudienceRequest,
    MobileAudienceResult,
    AudienceInsight,
    MobileAudienceConfiguration,
    TargetingStrategy,
    AudienceSegment
)

# Phase 5: Collaboration & Gamification Mobile (CRITICAL)
from .collaboration_orchestrator_mobile import (
    MobileCollaborationOrchestrator,
    MobileCollaborationRequest,
    MobileCollaborationResult,
    CollaborationEvent,
    MobileCollaborationConfiguration,
    CollaborationType,
    CollaborationStatus,
    MobileFeature,
    create_mobile_collaboration_orchestrator
)

from .creator_matching_mobile import (
    MobileCreatorMatching,
    MobileMatchingRequest,
    MobileMatchingResult,
    MatchResult,
    CreatorProfile,
    MobileMatchingConfiguration,
    MatchingStrategy,
    CompatibilityLevel,
    create_mobile_creator_matching
)

from .project_management_mobile import (
    MobileProjectManagement,
    MobileProjectRequest,
    MobileProjectResult,
    ProjectTask,
    ProjectMilestone,
    MobileProjectConfiguration,
    ProjectStatus,
    TaskStatus,
    TaskPriority
)

from .team_workspace_mobile import (
    MobileTeamWorkspace,
    MobileWorkspaceRequest,
    MobileWorkspaceResult,
    WorkspaceMember,
    MobileWorkspaceConfiguration,
    WorkspaceType,
    AccessLevel
)

from .gamification_mobile_engine import (
    MobileGamificationEngine,
    MobileGamificationRequest,
    MobileGamificationResult,
    Achievement,
    GamificationReward,
    MobileGamificationConfiguration,
    AchievementType,
    RewardType
)

from .achievement_tracker_mobile import (
    MobileAchievementTracker,
    MobileAchievementRequest,
    MobileAchievementResult,
    AchievementProgress,
    MobileAchievementConfiguration,
    AchievementCategory,
    ProgressStatus
)

from .reward_system_mobile import (
    MobileRewardSystem,
    MobileRewardRequest,
    MobileRewardResult,
    Reward,
    RewardDelivery,
    MobileRewardConfiguration,
    RewardCategory,
    RewardStatus
)

from .mobile_workflow_automation import (
    MobileWorkflowAutomation,
    MobileWorkflowRequest,
    MobileWorkflowResult,
    WorkflowRule,
    WorkflowExecution,
    MobileWorkflowConfiguration,
    WorkflowTrigger,
    WorkflowAction,
    WorkflowStatus
)

__all__ = [
    # Original services
    "PushNotificationService",
    "NotificationPriority", 
    "NotificationType",
    "OfflineSyncManager",
    "SyncStrategy",
    "ConflictResolution",
    
    # Phase 1: Creator Mobile Workflow Core
    "MobileContentOrchestrator",
    "MobileContentRequest",
    "WorkflowStatus", 
    "CreatorType",
    "WorkflowStage",
    "MobileOptimization",
    
    "CreatorUploadManager",
    "UploadRequest",
    "UploadProgress",
    "CreatorUploadSettings",
    "ContentFormat",
    "UploadStatus",
    "UploadMethod",
    
    "MobileMediaProcessor", 
    "ProcessingRequest",
    "ProcessingResult",
    "MobileProcessingSettings",
    "QualityLevel",
    "MobileFormat",
    "ProcessingStatus",
    
    "CreatorWorkflowMobile",
    "CreatorWorkflowState",
    "MobileWorkflowConfiguration", 
    "MobileWorkflowEvent",
    "WorkflowEvent",
    
    # Phase 2: IA Processing Mobile Integration
    "MobileAIOrchestrator",
    "AIProcessingRequest",
    "AIProcessingResult",
    "MobileAISettings",
    "AIProcessingType",
    "AIModelSize",
    "ProcessingPriority",
    
    "ContentIntelligenceMobile",
    "ContentAnalysisRequest",
    "ContentInsights",
    "AutoGeneratedMetadata",
    "TrendAnalysis",
    "ContentCategory",
    "ContentMood",
    "ContentComplexity",
    
    "AIAnalysisMobile",
    "MobileAnalysisRequest",
    "ComprehensiveAnalysisResult",
    "VisualAnalysisResult",
    "AudioAnalysisResult",
    "TextAnalysisResult",
    "PatternAnalysisResult",
    "AnalysisConfiguration",
    "AnalysisType",
    "AnalysisComplexity",
    
    "MobileAICacheManager",
    "CacheEntry",
    "CacheConfiguration",
    "CachePerformanceMetrics",
    "CacheStrategy",
    "CacheLevel",
    "CachePriority",
    
    # Phase 3: Content Protection Mobile
    "MobileProtectionOrchestrator",
    "MobileProtectionRequest",
    "MobileProtectionResult",
    "MobileProtectionConfiguration",
    "MobileProtectionMode",
    "MobileDeviceType",
    "MobileNetworkType",
    
    "MobileFingerprintEngine",
    "MobileFingerprintRequest",
    "MobileFingerprintResult",
    "MobileFingerprintConfig",
    "MobileFingerprintType",
    "MobileContentType",
    "MobileFingerprintQuality",
    
    "MobileWatermarkProcessor",
    "MobileWatermarkRequest",
    "MobileWatermarkResult",
    "MobileWatermarkConfig",
    "MobileWatermarkType",
    "MobileWatermarkStrength",
    "MobileWatermarkPosition",
    
    "MobileViolationAlertSystem",
    "MobileViolationEvent",
    "MobileAlertRequest",
    "MobileAlertResult",
    "MobileAlertConfiguration",
    "MobileViolationType",
    "MobileAlertSeverity",
    "MobileAlertChannel",
    
    # Phase 4: SEO & Distribution Mobile
    "MobileSEOOrchestrator",
    "MobileSEORequest",
    "MobileSEOResult",
    "MobileSEOConfiguration",
    "MobileSEOStrategy",
    "create_mobile_seo_orchestrator",
    
    "MobilePlatformAdapter",
    "MobilePlatformRequest",
    "MobilePlatformAdaptationResult",
    "PlatformAdaptationResult",
    "MobilePlatformConfiguration",
    "create_mobile_platform_adapter",
    
    "MobileMetadataOptimizer",
    "MobileMetadataRequest",
    "MobileMetadataResult",
    "OptimizedMetadata",
    "MobileMetadataConfiguration",
    "create_mobile_metadata_optimizer",
    
    "MobileTrendingAnalyzer",
    "MobileTrendRequest",
    "MobileTrendResult",
    "TrendInsight",
    "MobileTrendConfiguration",
    "create_mobile_trending_analyzer",
    
    "MobileEngagementPredictor",
    "MobileEngagementRequest",
    "MobileEngagementResult",
    "EngagementPrediction",
    "MobileEngagementConfiguration",
    "create_mobile_engagement_predictor",
    
    "MobileDistributionManager",
    "MobileDistributionRequest",
    "MobileDistributionResult",
    "PlatformDistributionResult",
    "MobileDistributionConfiguration",
    
    "MobileSocialOptimizer",
    "MobileSocialRequest",
    "MobileSocialResult",
    "SocialPlatformOptimization",
    "MobileSocialConfiguration",
    
    "MobileAudienceTargeting",
    "MobileAudienceRequest",
    "MobileAudienceResult",
    "AudienceInsight",
    "MobileAudienceConfiguration",
    
    # Phase 5: Collaboration & Gamification Mobile
    "MobileCollaborationOrchestrator",
    "MobileCollaborationRequest",
    "MobileCollaborationResult",
    "CollaborationEvent",
    "MobileCollaborationConfiguration",
    "create_mobile_collaboration_orchestrator",
    
    "MobileCreatorMatching",
    "MobileMatchingRequest",
    "MobileMatchingResult",
    "MatchResult",
    "CreatorProfile",
    "MobileMatchingConfiguration",
    "create_mobile_creator_matching",
    
    "MobileProjectManagement",
    "MobileProjectRequest",
    "MobileProjectResult",
    "ProjectTask",
    "ProjectMilestone",
    "MobileProjectConfiguration",
    
    "MobileTeamWorkspace",
    "MobileWorkspaceRequest",
    "MobileWorkspaceResult",
    "WorkspaceMember",
    "MobileWorkspaceConfiguration",
    
    "MobileGamificationEngine",
    "MobileGamificationRequest",
    "MobileGamificationResult",
    "Achievement",
    "GamificationReward",
    "MobileGamificationConfiguration",
    
    "MobileAchievementTracker",
    "MobileAchievementRequest",
    "MobileAchievementResult",
    "AchievementProgress",
    "MobileAchievementConfiguration",
    
    "MobileRewardSystem",
    "MobileRewardRequest",
    "MobileRewardResult",
    "Reward",
    "RewardDelivery",
    "MobileRewardConfiguration",
    
    "MobileWorkflowAutomation",
    "MobileWorkflowRequest",
    "MobileWorkflowResult",
    "WorkflowRule",
    "WorkflowExecution",
    "MobileWorkflowConfiguration"
]