"""Backend Mobile Services
Mobile-specific backend services and integrations

Enterprise Mobile Backend Architecture implementing:
- Creator Multi-Format Upload Integration
- Mobile Content Orchestration  
- Mobile-Optimized Media Processing
- Creator Workflow Mobile Integration
- IA Processing Mobile Integration

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright: (c) 2025 Fahed Mlaiel. All rights reserved.
"""

# Original mobile services
from .push_notifications import PushNotificationService, NotificationPriority, NotificationType
from .offline_sync import OfflineSyncManager, SyncStrategy, ConflictResolution

# Phase 1: Creator Mobile Workflow Core (CRITICAL PRIORITY)
from .mobile_content_orchestrator import (
    MobileContentOrchestrator,
    MobileContentRequest, 
    WorkflowStatus,
    CreatorType,
    WorkflowStage,
    MobileOptimization
)

from .creator_upload_manager import (
    CreatorUploadManager,
    UploadRequest,
    UploadProgress,
    CreatorUploadSettings,
    ContentFormat,
    UploadStatus,
    UploadMethod
)

from .mobile_media_processor import (
    MobileMediaProcessor,
    ProcessingRequest,
    ProcessingResult,
    MobileProcessingSettings,
    QualityLevel,
    MobileFormat,
    ProcessingStatus
)

from .creator_workflow_mobile import (
    CreatorWorkflowMobile,
    CreatorWorkflowState,
    MobileWorkflowConfiguration,
    MobileWorkflowEvent,
    WorkflowEvent
)

# Phase 2: IA Processing Mobile Integration (CRITICAL)
from .mobile_ai_orchestrator import (
    MobileAIOrchestrator,
    AIProcessingRequest,
    AIProcessingResult,
    MobileAISettings,
    AIProcessingType,
    AIModelSize,
    ProcessingPriority
)

from .content_intelligence_mobile import (
    ContentIntelligenceMobile,
    ContentAnalysisRequest,
    ContentInsights,
    AutoGeneratedMetadata,
    TrendAnalysis,
    ContentCategory,
    ContentMood,
    ContentComplexity
)

from .ai_analysis_mobile import (
    AIAnalysisMobile,
    MobileAnalysisRequest,
    ComprehensiveAnalysisResult,
    VisualAnalysisResult,
    AudioAnalysisResult,
    TextAnalysisResult,
    PatternAnalysisResult,
    AnalysisConfiguration,
    AnalysisType,
    AnalysisComplexity
)

from .mobile_ai_cache_manager import (
    MobileAICacheManager,
    CacheEntry,
    CacheConfiguration,
    CachePerformanceMetrics,
    CacheStrategy,
    CacheLevel,
    CachePriority
)

__all__ = [
    # Original services
    "PushNotificationService",
    "NotificationPriority", 
    "NotificationType",
    "OfflineSyncManager",
    "SyncStrategy",
    "ConflictResolution",
    
    # Phase 1: Creator Mobile Workflow Core
    "MobileContentOrchestrator",
    "MobileContentRequest",
    "WorkflowStatus", 
    "CreatorType",
    "WorkflowStage",
    "MobileOptimization",
    
    "CreatorUploadManager",
    "UploadRequest",
    "UploadProgress",
    "CreatorUploadSettings",
    "ContentFormat",
    "UploadStatus",
    "UploadMethod",
    
    "MobileMediaProcessor", 
    "ProcessingRequest",
    "ProcessingResult",
    "MobileProcessingSettings",
    "QualityLevel",
    "MobileFormat",
    "ProcessingStatus",
    
    "CreatorWorkflowMobile",
    "CreatorWorkflowState",
    "MobileWorkflowConfiguration", 
    "MobileWorkflowEvent",
    "WorkflowEvent",
    
    # Phase 2: IA Processing Mobile Integration
    "MobileAIOrchestrator",
    "AIProcessingRequest",
    "AIProcessingResult",
    "MobileAISettings",
    "AIProcessingType",
    "AIModelSize",
    "ProcessingPriority",
    
    "ContentIntelligenceMobile",
    "ContentAnalysisRequest",
    "ContentInsights",
    "AutoGeneratedMetadata",
    "TrendAnalysis",
    "ContentCategory",
    "ContentMood",
    "ContentComplexity",
    
    "AIAnalysisMobile",
    "MobileAnalysisRequest",
    "ComprehensiveAnalysisResult",
    "VisualAnalysisResult",
    "AudioAnalysisResult",
    "TextAnalysisResult",
    "PatternAnalysisResult",
    "AnalysisConfiguration",
    "AnalysisType",
    "AnalysisComplexity",
    
    "MobileAICacheManager",
    "CacheEntry",
    "CacheConfiguration",
    "CachePerformanceMetrics",
    "CacheStrategy",
    "CacheLevel",
    "CachePriority"
]