"""Content Intelligence Mobile
=============================

Mobile content intelligence engine providing smart content analysis,
automated metadata generation, and creator-specific insights.

Author: Fahed Mlaiel <mlaiel@live.de>
Copyright: (c) 2025 Fahed Mlaiel. All rights reserved.
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Union
from enum import Enum
from dataclasses import dataclass, asdict
import json
import uuid
import re

logger = logging.getLogger(__name__)


class ContentCategory(str, Enum):
    """Content categories for mobile classification."""
    MUSIC = "music"
    PODCAST = "podcast"
    BLOG_POST = "blog_post"
    TUTORIAL = "tutorial"
    VLOG = "vlog"
    PHOTOGRAPHY = "photography"
    ART = "art"
    COMEDY = "comedy"
    ENTERTAINMENT = "entertainment"
    EDUCATIONAL = "educational"
    NEWS = "news"
    LIFESTYLE = "lifestyle"
    TECH = "tech"
    TRAVEL = "travel"
    FOOD = "food"
    FITNESS = "fitness"
    GAMING = "gaming"


class ContentMood(str, Enum):
    """Content mood classification."""
    ENERGETIC = "energetic"
    CALM = "calm"
    HAPPY = "happy"
    SERIOUS = "serious"
    EMOTIONAL = "emotional"
    INSPIRATIONAL = "inspirational"
    HUMOROUS = "humorous"
    DRAMATIC = "dramatic"
    MYSTERIOUS = "mysterious"
    NOSTALGIC = "nostalgic"


class ContentComplexity(str, Enum):
    """Content complexity levels."""
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    EXPERT = "expert"


@dataclass
class ContentAnalysisRequest:
    """Content analysis request for mobile intelligence."""
    request_id: str
    content_id: str
    creator_id: str
    creator_type: str
    content_type: str  # audio, video, image, text
    content_path: str
    content_metadata: Dict[str, Any]
    mobile_device_id: str
    analysis_depth: str = "standard"  # quick, standard, deep
    include_trends: bool = True
    include_recommendations: bool = True
    real_time_analysis: bool = False
    created_at: datetime = None

    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.utcnow()


@dataclass 
class ContentInsights:
    """Content intelligence insights."""
    content_id: str
    primary_category: ContentCategory
    secondary_categories: List[ContentCategory]
    content_mood: ContentMood
    complexity_level: ContentComplexity
    engagement_score: float  # 0-100
    quality_score: float     # 0-100
    virality_potential: float  # 0-100
    trending_topics: List[str]
    target_audience: Dict[str, Any]
    optimal_platforms: List[str]
    content_themes: List[str]
    keywords: List[str]
    hashtags: List[str]
    content_structure: Dict[str, Any]
    improvement_suggestions: List[str]
    collaboration_opportunities: List[str]
    monetization_potential: Dict[str, Any]
    mobile_optimization_score: float
    accessibility_score: float
    seo_score: float
    generated_at: datetime = None

    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.utcnow()


@dataclass
class AutoGeneratedMetadata:
    """Auto-generated content metadata."""
    title: str
    description: str
    tags: List[str]
    categories: List[str]
    thumbnail_suggestions: List[str]
    chapter_markers: List[Dict[str, Any]]
    transcription: Optional[str]
    translations: Dict[str, str]
    alt_text: Optional[str]
    captions: List[Dict[str, str]]
    summary: str
    key_moments: List[Dict[str, Any]]
    generated_at: datetime = None

    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.utcnow()


@dataclass
class TrendAnalysis:
    """Content trend analysis."""
    trending_topics: List[Dict[str, Any]]
    viral_elements: List[str]
    optimal_timing: Dict[str, Any]
    platform_trends: Dict[str, Any]
    hashtag_trends: List[str]
    competitor_analysis: Dict[str, Any]
    growth_opportunities: List[str]
    market_positioning: Dict[str, Any]
    analyzed_at: datetime = None

    def __post_init__(self):
        if self.analyzed_at is None:
            self.analyzed_at = datetime.utcnow()


class ContentIntelligenceMobile:
    """Mobile content intelligence engine."""

    def __init__(self):
        self.analysis_engines = self._initialize_analysis_engines()
        self.creator_profiles = self._initialize_creator_profiles()
        self.trend_data = self._initialize_trend_data()
        self.intelligence_cache = {}
        
        # Creator-specific analysis patterns
        self.creator_analysis_patterns = self._initialize_creator_patterns()
        self.mobile_optimization_rules = self._initialize_mobile_rules()

    def _initialize_analysis_engines(self) -> Dict[str, Any]:
        """Initialize content analysis engines."""
        return {
            "category_classifier": self._create_category_classifier(),
            "mood_analyzer": self._create_mood_analyzer(),
            "engagement_predictor": self._create_engagement_predictor(),
            "quality_assessor": self._create_quality_assessor(),
            "trend_analyzer": self._create_trend_analyzer(),
            "metadata_generator": self._create_metadata_generator(),
            "seo_analyzer": self._create_seo_analyzer(),
            "accessibility_checker": self._create_accessibility_checker()
        }

    def _initialize_creator_profiles(self) -> Dict[str, Dict[str, Any]]:
        """Initialize creator-specific analysis profiles."""
        return {
            "musician": {
                "primary_categories": [ContentCategory.MUSIC, ContentCategory.ENTERTAINMENT],
                "analysis_focus": ["audio_quality", "genre_classification", "mood_detection"],
                "metadata_priority": ["genre", "tempo", "key", "instruments"],
                "engagement_factors": ["melody", "rhythm", "vocals", "production"],
                "mobile_optimizations": ["audio_compression", "streaming_optimization"]
            },
            "blogger": {
                "primary_categories": [ContentCategory.BLOG_POST, ContentCategory.EDUCATIONAL],
                "analysis_focus": ["readability", "topic_relevance", "seo_optimization"],
                "metadata_priority": ["topic", "keywords", "reading_time", "difficulty"],
                "engagement_factors": ["headline", "structure", "value", "readability"],
                "mobile_optimizations": ["text_formatting", "image_optimization"]
            },
            "photographer": {
                "primary_categories": [ContentCategory.PHOTOGRAPHY, ContentCategory.ART],
                "analysis_focus": ["composition", "color_analysis", "style_detection"],
                "metadata_priority": ["subject", "style", "technique", "equipment"],
                "engagement_factors": ["composition", "lighting", "color", "subject"],
                "mobile_optimizations": ["image_compression", "responsive_sizing"]
            },
            "influencer": {
                "primary_categories": [ContentCategory.LIFESTYLE, ContentCategory.ENTERTAINMENT],
                "analysis_focus": ["trend_alignment", "audience_appeal", "engagement_potential"],
                "metadata_priority": ["trends", "audience", "platform", "timing"],
                "engagement_factors": ["authenticity", "relatability", "trends", "timing"],
                "mobile_optimizations": ["multi_format", "social_optimization"]
            },
            "comedian": {
                "primary_categories": [ContentCategory.COMEDY, ContentCategory.ENTERTAINMENT],
                "analysis_focus": ["humor_detection", "timing_analysis", "audience_reaction"],
                "metadata_priority": ["humor_type", "audience", "delivery", "content"],
                "engagement_factors": ["timing", "delivery", "relatability", "originality"],
                "mobile_optimizations": ["video_optimization", "audio_clarity"]
            }
        }

    def _initialize_trend_data(self) -> Dict[str, Any]:
        """Initialize trend analysis data."""
        return {
            "current_trends": {
                "music": ["ai_music", "lo_fi", "electronic_pop", "acoustic"],
                "video": ["short_form", "tutorials", "behind_scenes", "reactions"],
                "topics": ["sustainability", "mental_health", "technology", "creativity"],
                "hashtags": ["#contentcreator", "#mobile", "#ai", "#creative"]
            },
            "platform_trends": {
                "instagram": {"formats": ["reels", "stories"], "optimal_length": 30},
                "tiktok": {"formats": ["short_video"], "optimal_length": 15},
                "youtube": {"formats": ["shorts", "long_form"], "optimal_length": 60},
                "twitter": {"formats": ["thread", "video"], "optimal_length": 120}
            },
            "audience_trends": {
                "gen_z": {"preferences": ["authentic", "short", "visual", "interactive"]},
                "millennials": {"preferences": ["informative", "nostalgic", "quality", "meaningful"]},
                "gen_x": {"preferences": ["professional", "informative", "traditional", "quality"]}
            }
        }

    def _initialize_creator_patterns(self) -> Dict[str, Dict[str, Any]]:
        """Initialize creator-specific analysis patterns."""
        return {
            "musician": {
                "content_patterns": ["single_release", "album_promotion", "live_performance", "behind_scenes"],
                "success_indicators": ["play_count", "shares", "saves", "comments"],
                "optimization_focus": ["audio_quality", "genre_tagging", "mood_classification"]
            },
            "blogger": {
                "content_patterns": ["how_to", "review", "opinion", "list", "story"],
                "success_indicators": ["read_time", "shares", "comments", "backlinks"],
                "optimization_focus": ["seo", "readability", "structure", "keywords"]
            },
            "photographer": {
                "content_patterns": ["portfolio", "tutorial", "behind_scenes", "equipment_review"],
                "success_indicators": ["likes", "saves", "shares", "feature_requests"],
                "optimization_focus": ["composition", "style", "technique", "quality"]
            }
        }

    def _initialize_mobile_rules(self) -> Dict[str, List[str]]:
        """Initialize mobile optimization rules."""
        return {
            "mobile_first_design": [
                "responsive_layout",
                "touch_friendly_controls",
                "fast_loading",
                "vertical_orientation"
            ],
            "performance_optimization": [
                "image_compression",
                "lazy_loading", 
                "progressive_enhancement",
                "caching_strategy"
            ],
            "accessibility": [
                "alt_text",
                "captions",
                "high_contrast",
                "screen_reader_friendly"
            ]
        }

    async def analyze_content_intelligence(self, request: ContentAnalysisRequest) -> ContentInsights:
        """Analyze content intelligence for mobile."""
        try:
            logger.info(f"Starting content intelligence analysis for {request.content_id}")
            
            # Get creator profile
            creator_profile = self.creator_profiles.get(request.creator_type, {})
            
            # Perform content analysis
            insights = await self._perform_comprehensive_analysis(request, creator_profile)
            
            # Apply mobile optimizations
            insights = await self._apply_mobile_intelligence_optimization(insights, request)
            
            # Cache results
            self.intelligence_cache[request.content_id] = insights
            
            logger.info(f"Content intelligence analysis completed for {request.content_id}")
            return insights
            
        except Exception as e:
            logger.error(f"Content intelligence analysis failed: {e}")
            raise

    async def _perform_comprehensive_analysis(self, request: ContentAnalysisRequest,
                                            creator_profile: Dict[str, Any]) -> ContentInsights:
        """Perform comprehensive content analysis."""
        
        # Category classification
        primary_category, secondary_categories = await self._classify_content_category(
            request, creator_profile
        )
        
        # Mood analysis
        content_mood = await self._analyze_content_mood(request)
        
        # Complexity assessment
        complexity_level = await self._assess_complexity(request)
        
        # Engagement prediction
        engagement_score = await self._predict_engagement(request, creator_profile)
        
        # Quality assessment
        quality_score = await self._assess_content_quality(request)
        
        # Virality potential
        virality_potential = await self._assess_virality_potential(request)
        
        # Trend analysis
        trending_topics = await self._identify_trending_topics(request)
        
        # Audience analysis
        target_audience = await self._analyze_target_audience(request, creator_profile)
        
        # Platform optimization
        optimal_platforms = await self._recommend_optimal_platforms(request, creator_profile)
        
        # Content themes
        content_themes = await self._extract_content_themes(request)
        
        # Keyword extraction
        keywords = await self._extract_keywords(request)
        
        # Hashtag generation
        hashtags = await self._generate_hashtags(request, trending_topics)
        
        # Content structure analysis
        content_structure = await self._analyze_content_structure(request)
        
        # Improvement suggestions
        improvement_suggestions = await self._generate_improvement_suggestions(request, creator_profile)
        
        # Collaboration opportunities
        collaboration_opportunities = await self._identify_collaboration_opportunities(request)
        
        # Monetization potential
        monetization_potential = await self._assess_monetization_potential(request)
        
        # Mobile optimization score
        mobile_optimization_score = await self._calculate_mobile_optimization_score(request)
        
        # Accessibility score
        accessibility_score = await self._calculate_accessibility_score(request)
        
        # SEO score
        seo_score = await self._calculate_seo_score(request)
        
        return ContentInsights(
            content_id=request.content_id,
            primary_category=primary_category,
            secondary_categories=secondary_categories,
            content_mood=content_mood,
            complexity_level=complexity_level,
            engagement_score=engagement_score,
            quality_score=quality_score,
            virality_potential=virality_potential,
            trending_topics=trending_topics,
            target_audience=target_audience,
            optimal_platforms=optimal_platforms,
            content_themes=content_themes,
            keywords=keywords,
            hashtags=hashtags,
            content_structure=content_structure,
            improvement_suggestions=improvement_suggestions,
            collaboration_opportunities=collaboration_opportunities,
            monetization_potential=monetization_potential,
            mobile_optimization_score=mobile_optimization_score,
            accessibility_score=accessibility_score,
            seo_score=seo_score
        )

    async def _classify_content_category(self, request: ContentAnalysisRequest,
                                       creator_profile: Dict[str, Any]) -> tuple:
        """Classify content into categories."""
        primary_categories = creator_profile.get("primary_categories", [ContentCategory.ENTERTAINMENT])
        
        # Simple classification based on creator type and content type
        if request.creator_type == "musician":
            primary = ContentCategory.MUSIC
            secondary = [ContentCategory.ENTERTAINMENT]
        elif request.creator_type == "blogger":
            primary = ContentCategory.BLOG_POST
            secondary = [ContentCategory.EDUCATIONAL]
        elif request.creator_type == "photographer":
            primary = ContentCategory.PHOTOGRAPHY
            secondary = [ContentCategory.ART]
        elif request.creator_type == "influencer":
            primary = ContentCategory.LIFESTYLE
            secondary = [ContentCategory.ENTERTAINMENT]
        elif request.creator_type == "comedian":
            primary = ContentCategory.COMEDY
            secondary = [ContentCategory.ENTERTAINMENT]
        else:
            primary = ContentCategory.ENTERTAINMENT
            secondary = []
        
        return primary, secondary

    async def _analyze_content_mood(self, request: ContentAnalysisRequest) -> ContentMood:
        """Analyze content mood."""
        # Simple mood analysis based on content type and metadata
        content_type = request.content_type
        
        if content_type == "audio":
            return ContentMood.ENERGETIC  # Default for music
        elif content_type == "video":
            return ContentMood.HAPPY      # Default for video content
        elif content_type == "image":
            return ContentMood.CALM       # Default for images
        else:
            return ContentMood.INSPIRATIONAL  # Default for text

    async def _assess_complexity(self, request: ContentAnalysisRequest) -> ContentComplexity:
        """Assess content complexity level."""
        # Simple complexity assessment
        return ContentComplexity.INTERMEDIATE

    async def _predict_engagement(self, request: ContentAnalysisRequest,
                                creator_profile: Dict[str, Any]) -> float:
        """Predict engagement score."""
        base_score = 70.0
        
        # Adjust based on creator type
        creator_boost = {
            "musician": 5.0,
            "influencer": 10.0,
            "comedian": 8.0,
            "photographer": 6.0,
            "blogger": 4.0
        }
        
        score = base_score + creator_boost.get(request.creator_type, 0.0)
        return min(score, 100.0)

    async def _assess_content_quality(self, request: ContentAnalysisRequest) -> float:
        """Assess content quality score."""
        return 85.0  # Placeholder score

    async def _assess_virality_potential(self, request: ContentAnalysisRequest) -> float:
        """Assess virality potential."""
        base_potential = 60.0
        
        # Higher potential for video content
        if request.content_type == "video":
            base_potential += 15.0
        elif request.content_type == "image":
            base_potential += 10.0
        
        return min(base_potential, 100.0)

    async def _identify_trending_topics(self, request: ContentAnalysisRequest) -> List[str]:
        """Identify trending topics related to content."""
        trends = self.trend_data["current_trends"]
        
        if request.content_type == "audio":
            return trends.get("music", [])
        elif request.content_type == "video":
            return trends.get("video", [])
        else:
            return trends.get("topics", [])

    async def _analyze_target_audience(self, request: ContentAnalysisRequest,
                                     creator_profile: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze target audience."""
        return {
            "primary_age_group": "18-34",
            "secondary_age_group": "25-45",
            "interests": ["creativity", "entertainment", "technology"],
            "platforms": ["instagram", "tiktok", "youtube"],
            "engagement_preferences": ["visual", "interactive", "authentic"],
            "optimal_posting_times": ["18:00-21:00", "12:00-14:00"]
        }

    async def _recommend_optimal_platforms(self, request: ContentAnalysisRequest,
                                         creator_profile: Dict[str, Any]) -> List[str]:
        """Recommend optimal platforms for content."""
        creator_platforms = {
            "musician": ["spotify", "youtube", "instagram", "tiktok"],
            "blogger": ["medium", "wordpress", "linkedin", "twitter"],
            "photographer": ["instagram", "pinterest", "behance", "flickr"],
            "influencer": ["instagram", "tiktok", "youtube", "twitter"],
            "comedian": ["youtube", "tiktok", "instagram", "twitter"]
        }
        
        return creator_platforms.get(request.creator_type, ["instagram", "youtube"])

    async def _extract_content_themes(self, request: ContentAnalysisRequest) -> List[str]:
        """Extract content themes."""
        return ["creativity", "innovation", "entertainment", "quality"]

    async def _extract_keywords(self, request: ContentAnalysisRequest) -> List[str]:
        """Extract relevant keywords."""
        base_keywords = ["content", "creative", request.creator_type, request.content_type]
        
        # Add creator-specific keywords
        creator_keywords = {
            "musician": ["music", "audio", "song", "artist"],
            "blogger": ["blog", "article", "writing", "content"],
            "photographer": ["photography", "photo", "image", "visual"],
            "influencer": ["lifestyle", "influence", "social", "trend"],
            "comedian": ["comedy", "humor", "entertainment", "funny"]
        }
        
        base_keywords.extend(creator_keywords.get(request.creator_type, []))
        return base_keywords

    async def _generate_hashtags(self, request: ContentAnalysisRequest, 
                               trending_topics: List[str]) -> List[str]:
        """Generate relevant hashtags."""
        base_hashtags = [f"#{request.creator_type}", f"#{request.content_type}", "#mobile", "#ai"]
        
        # Add trending hashtags
        for topic in trending_topics[:3]:  # Top 3 trending topics
            base_hashtags.append(f"#{topic.replace(' ', '').replace('_', '')}")
        
        # Add creator-specific hashtags
        creator_hashtags = {
            "musician": ["#music", "#audio", "#song", "#artist"],
            "blogger": ["#blog", "#writing", "#content", "#article"],
            "photographer": ["#photography", "#photo", "#art", "#visual"],
            "influencer": ["#lifestyle", "#influence", "#social", "#trend"],
            "comedian": ["#comedy", "#humor", "#funny", "#entertainment"]
        }
        
        base_hashtags.extend(creator_hashtags.get(request.creator_type, []))
        return base_hashtags[:15]  # Limit to 15 hashtags

    async def _analyze_content_structure(self, request: ContentAnalysisRequest) -> Dict[str, Any]:
        """Analyze content structure."""
        return {
            "has_introduction": True,
            "has_main_content": True,
            "has_conclusion": True,
            "content_flow": "good",
            "pacing": "appropriate",
            "structure_score": 85.0
        }

    async def _generate_improvement_suggestions(self, request: ContentAnalysisRequest,
                                              creator_profile: Dict[str, Any]) -> List[str]:
        """Generate improvement suggestions."""
        suggestions = []
        
        # General suggestions
        suggestions.extend([
            "Optimize for mobile viewing",
            "Add engaging thumbnails",
            "Include clear call-to-action",
            "Use trending hashtags"
        ])
        
        # Creator-specific suggestions
        creator_suggestions = {
            "musician": ["Enhance audio quality", "Add album artwork", "Include lyrics"],
            "blogger": ["Improve readability", "Add visual elements", "Optimize SEO"],
            "photographer": ["Enhance composition", "Adjust lighting", "Add descriptions"],
            "influencer": ["Increase authenticity", "Follow trends", "Engage with audience"],
            "comedian": ["Improve timing", "Add visual elements", "Enhance delivery"]
        }
        
        suggestions.extend(creator_suggestions.get(request.creator_type, []))
        return suggestions[:8]  # Limit to 8 suggestions

    async def _identify_collaboration_opportunities(self, request: ContentAnalysisRequest) -> List[str]:
        """Identify collaboration opportunities."""
        return [
            "Cross-promotion with similar creators",
            "Guest appearances on podcasts",
            "Collaborative content creation",
            "Brand partnership opportunities",
            "Community challenges participation"
        ]

    async def _assess_monetization_potential(self, request: ContentAnalysisRequest) -> Dict[str, Any]:
        """Assess monetization potential."""
        return {
            "overall_score": 75.0,
            "revenue_streams": ["advertising", "sponsorships", "merchandise", "subscriptions"],
            "estimated_monthly_revenue": {"min": 100, "max": 1000},
            "monetization_readiness": "good",
            "recommended_strategies": ["build_audience", "create_premium_content", "partner_with_brands"]
        }

    async def _calculate_mobile_optimization_score(self, request: ContentAnalysisRequest) -> float:
        """Calculate mobile optimization score."""
        base_score = 80.0
        
        # Adjust based on content type
        mobile_scores = {
            "video": 85.0,
            "image": 90.0,
            "audio": 88.0,
            "text": 85.0
        }
        
        return mobile_scores.get(request.content_type, base_score)

    async def _calculate_accessibility_score(self, request: ContentAnalysisRequest) -> float:
        """Calculate accessibility score."""
        return 75.0  # Placeholder score

    async def _calculate_seo_score(self, request: ContentAnalysisRequest) -> float:
        """Calculate SEO optimization score."""
        return 82.0  # Placeholder score

    async def _apply_mobile_intelligence_optimization(self, insights: ContentInsights,
                                                    request: ContentAnalysisRequest) -> ContentInsights:
        """Apply mobile-specific intelligence optimizations."""
        
        # Optimize hashtags for mobile platforms
        mobile_hashtags = []
        for hashtag in insights.hashtags:
            if len(hashtag) <= 20:  # Mobile-friendly length
                mobile_hashtags.append(hashtag)
        insights.hashtags = mobile_hashtags
        
        # Prioritize mobile-friendly platforms
        mobile_platforms = ["instagram", "tiktok", "youtube", "twitter"]
        insights.optimal_platforms = [p for p in insights.optimal_platforms if p in mobile_platforms]
        
        # Add mobile-specific improvements
        mobile_improvements = [
            "Optimize for vertical viewing",
            "Add mobile-friendly captions",
            "Ensure fast loading times",
            "Use touch-friendly elements"
        ]
        insights.improvement_suggestions.extend(mobile_improvements)
        
        return insights

    # Placeholder engine creation methods
    def _create_category_classifier(self): return None
    def _create_mood_analyzer(self): return None
    def _create_engagement_predictor(self): return None
    def _create_quality_assessor(self): return None
    def _create_trend_analyzer(self): return None
    def _create_metadata_generator(self): return None
    def _create_seo_analyzer(self): return None
    def _create_accessibility_checker(self): return None

    # Public API methods
    async def generate_auto_metadata(self, request: ContentAnalysisRequest) -> AutoGeneratedMetadata:
        """Generate automatic metadata for content."""
        try:
            insights = await self.analyze_content_intelligence(request)
            
            # Generate title
            title = await self._generate_title(request, insights)
            
            # Generate description
            description = await self._generate_description(request, insights)
            
            # Generate summary
            summary = await self._generate_summary(request, insights)
            
            return AutoGeneratedMetadata(
                title=title,
                description=description,
                tags=insights.keywords,
                categories=[insights.primary_category.value] + [c.value for c in insights.secondary_categories],
                thumbnail_suggestions=await self._suggest_thumbnails(request),
                chapter_markers=await self._generate_chapter_markers(request),
                transcription=await self._generate_transcription(request),
                translations=await self._generate_translations(request),
                alt_text=await self._generate_alt_text(request),
                captions=await self._generate_captions(request),
                summary=summary,
                key_moments=await self._identify_key_moments(request)
            )
            
        except Exception as e:
            logger.error(f"Auto metadata generation failed: {e}")
            raise

    async def analyze_trends(self, request: ContentAnalysisRequest) -> TrendAnalysis:
        """Analyze content trends and opportunities."""
        try:
            trending_topics = await self._analyze_trending_topics(request)
            viral_elements = await self._identify_viral_elements(request)
            optimal_timing = await self._calculate_optimal_timing(request)
            platform_trends = await self._analyze_platform_trends(request)
            hashtag_trends = await self._analyze_hashtag_trends(request)
            competitor_analysis = await self._analyze_competitors(request)
            growth_opportunities = await self._identify_growth_opportunities(request)
            market_positioning = await self._analyze_market_positioning(request)
            
            return TrendAnalysis(
                trending_topics=trending_topics,
                viral_elements=viral_elements,
                optimal_timing=optimal_timing,
                platform_trends=platform_trends,
                hashtag_trends=hashtag_trends,
                competitor_analysis=competitor_analysis,
                growth_opportunities=growth_opportunities,
                market_positioning=market_positioning
            )
            
        except Exception as e:
            logger.error(f"Trend analysis failed: {e}")
            raise

    async def get_creator_intelligence_profile(self, creator_id: str) -> Dict[str, Any]:
        """Get intelligence profile for creator."""
        cached_insights = [insight for insight in self.intelligence_cache.values() 
                          if hasattr(insight, 'content_id')]
        
        if not cached_insights:
            return {"profile": "not_enough_data"}
        
        return {
            "content_analyzed": len(cached_insights),
            "average_engagement_score": sum(i.engagement_score for i in cached_insights) / len(cached_insights),
            "average_quality_score": sum(i.quality_score for i in cached_insights) / len(cached_insights),
            "most_common_category": max(set(i.primary_category for i in cached_insights), 
                                      key=[i.primary_category for i in cached_insights].count),
            "trending_topics_used": list(set(topic for insight in cached_insights 
                                           for topic in insight.trending_topics))
        }

    # Helper methods for metadata generation
    async def _generate_title(self, request: ContentAnalysisRequest, insights: ContentInsights) -> str:
        """Generate optimized title."""
        creator_prefixes = {
            "musician": "🎵",
            "blogger": "📝", 
            "photographer": "📸",
            "influencer": "✨",
            "comedian": "😄"
        }
        
        prefix = creator_prefixes.get(request.creator_type, "🎯")
        base_title = f"{prefix} {insights.primary_category.value.replace('_', ' ').title()}"
        
        if insights.trending_topics:
            base_title += f" - {insights.trending_topics[0].title()}"
        
        return base_title

    async def _generate_description(self, request: ContentAnalysisRequest, insights: ContentInsights) -> str:
        """Generate optimized description."""
        description = f"Discover amazing {insights.primary_category.value.replace('_', ' ')} content "
        description += f"created by a talented {request.creator_type}. "
        
        if insights.content_themes:
            description += f"Featuring themes of {', '.join(insights.content_themes[:3])}. "
        
        description += f"Quality score: {insights.quality_score:.0f}/100. "
        description += "Optimized for mobile viewing."
        
        return description

    async def _generate_summary(self, request: ContentAnalysisRequest, insights: ContentInsights) -> str:
        """Generate content summary."""
        return f"High-quality {insights.primary_category.value.replace('_', ' ')} content " + \
               f"with {insights.content_mood.value} mood and {insights.complexity_level.value} complexity level."

    # Placeholder methods for metadata generation components
    async def _suggest_thumbnails(self, request): return []
    async def _generate_chapter_markers(self, request): return []
    async def _generate_transcription(self, request): return None
    async def _generate_translations(self, request): return {}
    async def _generate_alt_text(self, request): return None
    async def _generate_captions(self, request): return []
    async def _identify_key_moments(self, request): return []
    
    # Placeholder methods for trend analysis components
    async def _analyze_trending_topics(self, request): return []
    async def _identify_viral_elements(self, request): return []
    async def _calculate_optimal_timing(self, request): return {}
    async def _analyze_platform_trends(self, request): return {}
    async def _analyze_hashtag_trends(self, request): return []
    async def _analyze_competitors(self, request): return {}
    async def _identify_growth_opportunities(self, request): return []
    async def _analyze_market_positioning(self, request): return {}