apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8004'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: ai-orchestration-service
    environment: production
    service-type: ai-service
  name: ai-orchestration-service
  namespace: ainflue-production
spec:
  ports:
  - name: http
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: ai-orchestration-service
  type: ClusterIP
