apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8005'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: auth-service
    environment: production
    service-type: security-service
  name: auth-service
  namespace: ainflue-production
spec:
  ports:
  - name: http
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    app: auth-service
  type: ClusterIP
