apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8002'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: content-processing-service
    environment: production
    service-type: content-service
  name: content-processing-service
  namespace: ainflue-production
spec:
  ports:
  - name: http
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: content-processing-service
  type: ClusterIP
