"""
🔒 GRAPHQL PAGINATION TEMPLATE - ENTERPRISE PAGINATION IMPLEMENTATION
====================================================================

© 2025 Fahed Mlaiel <mlaiel@live.de>
TOUS DROITS RÉSERVÉS

Enterprise-grade GraphQL pagination template with:
- Cursor-based pagination
- Relay-style connections
- Performance optimization
- Creator economy integration

Author: Fahed Mlaiel (mlaiel@live.de)
Version: 1.0.0
"""

from typing import Dict, List, Optional, Any, Generic, TypeVar
from dataclasses import dataclass
import logging
import base64
import json

import strawberry
from strawberry.types import Info
from pydantic import BaseModel, Field

from ..template_registry import TemplateInterface, TemplateMetadata, TemplateType, TemplateCategory, SecurityLevel

logger = logging.getLogger(__name__)

T = TypeVar('T')


class GraphQLPaginationConfig(BaseModel):
    """Configuration for GraphQL pagination generation."""
    
    pagination_name: str = Field(..., description="Name of the pagination configuration")
    description: str = Field("", description="Pagination description")
    
    # Pagination settings
    pagination_config: Dict[str, Any] = Field(
        default_factory=lambda: {
            "default_page_size": 20,
            "max_page_size": 100,
            "enable_cursor_pagination": True,
            "enable_offset_pagination": True,
            "enable_total_count": True
        }
    )


class GraphQLPaginationTemplate(TemplateInterface):
    """Enterprise GraphQL pagination template."""
    
    @property
    def metadata(self) -> TemplateMetadata:
        return TemplateMetadata(
            name="graphql_pagination_template",
            template_type=TemplateType.GRAPHQL,
            category=TemplateCategory.ADVANCED,
            version="1.0.0",
            author="Fahed Mlaiel",
            description="Enterprise GraphQL pagination template with cursor and offset support",
            security_level=SecurityLevel.ENTERPRISE,
            dependencies=["strawberry-graphql", "pydantic"],
            tags=["graphql", "pagination", "cursor", "relay"],
            enterprise_features=[
                "Cursor-based pagination",
                "Relay connections",
                "Performance optimization",
                "Flexible page sizes"
            ]
        )
    
    def generate(self, config: Dict[str, Any]) -> str:
        """Generate GraphQL pagination based on configuration."""
        try:
            pagination_config = GraphQLPaginationConfig(**config)
            return self._generate_pagination_code(pagination_config)
        except Exception as e:
            logger.error(f"Failed to generate GraphQL pagination: {e}")
            raise
    
    def validate_config(self, config: Dict[str, Any]) -> bool:
        """Validate pagination configuration."""
        try:
            GraphQLPaginationConfig(**config)
            return True
        except Exception as e:
            logger.error(f"Invalid GraphQL pagination config: {e}")
            return False
    
    def get_schema(self) -> Dict[str, Any]:
        """Return JSON schema for configuration."""
        return GraphQLPaginationConfig.schema()
    
    def get_examples(self) -> List[Dict[str, Any]]:
        """Return example configurations."""
        return [
            {
                "pagination_name": "CreatorPagination",
                "description": "Pagination for creator economy GraphQL API"
            }
        ]
    
    def _generate_pagination_code(self, config: GraphQLPaginationConfig) -> str:
        """Generate the actual GraphQL pagination code."""
        
        code = f'''"""
{config.pagination_name} GraphQL Pagination
Generated by Ainflue GraphQL Pagination Template

{config.description}

🔒 PROTECTION INTELLECTUELLE:
© 2025 Fahed Mlaiel <mlaiel@live.de>
TOUS DROITS RÉSERVÉS
"""

from typing import Dict, List, Optional, Any, Generic, TypeVar, Union
import logging
import base64
import json
from dataclasses import dataclass

import strawberry
from strawberry.types import Info

logger = logging.getLogger(__name__)

T = TypeVar('T')

# Pagination Types

@strawberry.type
class PageInfo:
    """Information about pagination."""
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str] = None
    end_cursor: Optional[str] = None

@strawberry.type
class Edge(Generic[T]):
    """An edge in a connection."""
    node: T
    cursor: str

@strawberry.type
class Connection(Generic[T]):
    """A connection type for pagination."""
    edges: List[Edge[T]]
    page_info: PageInfo
    total_count: Optional[int] = None

@strawberry.input
class PaginationInput:
    """Input for pagination parameters."""
    first: Optional[int] = None
    after: Optional[str] = None
    last: Optional[int] = None
    before: Optional[str] = None

# Cursor utilities

def encode_cursor(value: Any) -> str:
    """Encode cursor value."""
    cursor_data = {{"value": str(value), "type": type(value).__name__}}
    cursor_json = json.dumps(cursor_data)
    return base64.b64encode(cursor_json.encode()).decode()

def decode_cursor(cursor: str) -> Any:
    """Decode cursor value."""
    try:
        cursor_json = base64.b64decode(cursor.encode()).decode()
        cursor_data = json.loads(cursor_json)
        return cursor_data["value"]
    except Exception:
        return None

# Pagination helpers

class PaginationHelper:
    """Helper class for pagination logic."""
    
    @staticmethod
    def validate_pagination_args(
        first: Optional[int] = None,
        after: Optional[str] = None,
        last: Optional[int] = None,
        before: Optional[str] = None,
        max_page_size: int = {config.pagination_config['max_page_size']}
    ) -> Dict[str, Any]:
        """Validate pagination arguments."""
        if first is not None and last is not None:
            raise ValueError("Cannot provide both first and last")
        
        if first is not None and first < 0:
            raise ValueError("first must be non-negative")
        
        if last is not None and last < 0:
            raise ValueError("last must be non-negative")
        
        if first is not None and first > max_page_size:
            raise ValueError(f"first cannot exceed {{max_page_size}}")
        
        if last is not None and last > max_page_size:
            raise ValueError(f"last cannot exceed {{max_page_size}}")
        
        # Default page size
        page_size = first or last or {config.pagination_config['default_page_size']}
        
        return {{
            "page_size": min(page_size, max_page_size),
            "forward": first is not None,
            "backward": last is not None,
            "after_cursor": decode_cursor(after) if after else None,
            "before_cursor": decode_cursor(before) if before else None
        }}
    
    @staticmethod
    def create_connection(
        items: List[T],
        total_count: Optional[int] = None,
        has_next_page: bool = False,
        has_previous_page: bool = False,
        cursor_field: str = "id"
    ) -> Connection[T]:
        """Create connection from items."""
        edges = []
        
        for item in items:
            cursor_value = getattr(item, cursor_field, None)
            cursor = encode_cursor(cursor_value) if cursor_value else ""
            edges.append(Edge(node=item, cursor=cursor))
        
        page_info = PageInfo(
            has_next_page=has_next_page,
            has_previous_page=has_previous_page,
            start_cursor=edges[0].cursor if edges else None,
            end_cursor=edges[-1].cursor if edges else None
        )
        
        return Connection(
            edges=edges,
            page_info=page_info,
            total_count=total_count
        )

# Pagination decorators

def paginated(
    cursor_field: str = "id",
    max_page_size: int = {config.pagination_config['max_page_size']},
    default_page_size: int = {config.pagination_config['default_page_size']},
    enable_total_count: bool = {config.pagination_config['enable_total_count']}
):
    """Decorator for paginated resolvers."""
    def decorator(resolver_func):
        async def wrapper(
            self,
            info: Info,
            pagination: Optional[PaginationInput] = None,
            **kwargs
        ):
            # Extract pagination parameters
            first = pagination.first if pagination else None
            after = pagination.after if pagination else None
            last = pagination.last if pagination else None
            before = pagination.before if pagination else None
            
            # Validate pagination arguments
            pagination_args = PaginationHelper.validate_pagination_args(
                first, after, last, before, max_page_size
            )
            
            # Call original resolver with pagination info
            result = await resolver_func(
                self, info, pagination_args=pagination_args, **kwargs
            )
            
            # Handle different return types
            if isinstance(result, dict):
                items = result.get("items", [])
                total_count = result.get("total_count") if enable_total_count else None
                has_next_page = result.get("has_next_page", False)
                has_previous_page = result.get("has_previous_page", False)
            else:
                items = result
                total_count = None
                has_next_page = False
                has_previous_page = False
            
            # Create connection
            return PaginationHelper.create_connection(
                items=items,
                total_count=total_count,
                has_next_page=has_next_page,
                has_previous_page=has_previous_page,
                cursor_field=cursor_field
            )
        
        return wrapper
    return decorator

# Example usage

@strawberry.type
class Creator:
    """Example Creator type."""
    id: str
    username: str
    email: str

@strawberry.type
class Content:
    """Example Content type."""
    id: str
    title: str
    creator_id: str

@strawberry.type
class Query:
    """Example query with pagination."""
    
    @strawberry.field
    @paginated(cursor_field="id", max_page_size=50)
    async def creators(
        self,
        info: Info,
        pagination_args: Dict[str, Any],
        search: Optional[str] = None
    ) -> Dict[str, Any]:
        """Get paginated creators."""
        # Extract pagination parameters
        page_size = pagination_args["page_size"]
        after_cursor = pagination_args["after_cursor"]
        before_cursor = pagination_args["before_cursor"]
        forward = pagination_args["forward"]
        
        # Build query based on pagination
        query_params = {{"limit": page_size + 1}}  # +1 to check for next page
        
        if forward and after_cursor:
            query_params["id__gt"] = after_cursor
        elif not forward and before_cursor:
            query_params["id__lt"] = before_cursor
        
        # Execute query (example implementation)
        creators = await self._get_creators(query_params, search)
        
        # Check for next/previous pages
        has_next_page = len(creators) > page_size
        has_previous_page = bool(after_cursor or before_cursor)
        
        # Remove extra item used for pagination check
        if has_next_page:
            creators = creators[:page_size]
        
        # Get total count if needed
        total_count = await self._get_creators_count(search) if {config.pagination_config['enable_total_count']} else None
        
        return {{
            "items": creators,
            "total_count": total_count,
            "has_next_page": has_next_page,
            "has_previous_page": has_previous_page
        }}
    
    async def _get_creators(self, query_params: Dict[str, Any], search: Optional[str] = None) -> List[Creator]:
        """Get creators from database."""
        # Implementation specific to your database
        return []
    
    async def _get_creators_count(self, search: Optional[str] = None) -> int:
        """Get total count of creators."""
        # Implementation specific to your database
        return 0

# Configuration
PAGINATION_CONFIG = {config.dict()}

if __name__ == "__main__":
    print(f"✅ {config.pagination_name} initialized successfully")
    print(f"📊 Pagination statistics:")
    print(f"   - Default page size: {config.pagination_config['default_page_size']}")
    print(f"   - Max page size: {config.pagination_config['max_page_size']}")
    print(f"   - Cursor pagination: {config.pagination_config['enable_cursor_pagination']}")
    print(f"   - Total count: {config.pagination_config['enable_total_count']}")
'''
        
        return code


# Register template
from .template_registry import register_template

register_template(
    GraphQLPaginationTemplate,
    GraphQLPaginationTemplate().metadata
)