"""
🔒 MULTI-FACTOR AUTHENTICATION TEMPLATE - ENTERPRISE MFA IMPLEMENTATION
======================================================================

© 2025 Fahed Mlaiel <mlaiel@live.de>
TOUS DROITS RÉSERVÉS

Enterprise-grade Multi-Factor Authentication template with:
- TOTP (Time-based One-Time Password)
- SMS verification
- Email verification
- Backup codes
- Creator economy integration

Author: Fahed Mlaiel (mlaiel@live.de)
Version: 1.0.0
"""

from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum
import logging
import secrets
import qrcode
import pyotp
from datetime import datetime, timedelta

from fastapi import FastAPI, Request, Depends, HTTPException, status
from pydantic import BaseModel, Field
import redis.asyncio as redis

from ..template_registry import TemplateInterface, TemplateMetadata, TemplateType, TemplateCategory, SecurityLevel

logger = logging.getLogger(__name__)


class MFAMethod(Enum):
    """MFA method types."""
    TOTP = "totp"
    SMS = "sms"
    EMAIL = "email"
    BACKUP_CODE = "backup_code"


class MFAConfig(BaseModel):
    """Configuration for MFA generation."""
    
    mfa_name: str = Field(..., description="Name of the MFA configuration")
    description: str = Field("", description="MFA description")
    
    # MFA settings
    mfa_config: Dict[str, Any] = Field(
        default_factory=lambda: {
            "issuer_name": "Ainflue",
            "totp_period": 30,
            "totp_digits": 6,
            "backup_codes_count": 10,
            "sms_enabled": True,
            "email_enabled": True,
            "require_mfa_for_creators": True
        }
    )


class MFATemplate(TemplateInterface):
    """Enterprise MFA template."""
    
    @property
    def metadata(self) -> TemplateMetadata:
        return TemplateMetadata(
            name="multi_factor_auth_template",
            template_type=TemplateType.AUTHENTICATION,
            category=TemplateCategory.SECURITY,
            version="1.0.0",
            author="Fahed Mlaiel",
            description="Enterprise Multi-Factor Authentication template",
            security_level=SecurityLevel.ENTERPRISE,
            dependencies=["pyotp", "qrcode", "redis", "fastapi"],
            tags=["mfa", "totp", "sms", "authentication", "security"],
            enterprise_features=[
                "TOTP authentication",
                "SMS verification",
                "Email verification", 
                "Backup codes",
                "QR code generation"
            ]
        )
    
    def generate(self, config: Dict[str, Any]) -> str:
        """Generate MFA based on configuration."""
        try:
            mfa_config = MFAConfig(**config)
            return self._generate_mfa_code(mfa_config)
        except Exception as e:
            logger.error(f"Failed to generate MFA: {e}")
            raise
    
    def validate_config(self, config: Dict[str, Any]) -> bool:
        """Validate MFA configuration."""
        try:
            MFAConfig(**config)
            return True
        except Exception as e:
            logger.error(f"Invalid MFA config: {e}")
            return False
    
    def get_schema(self) -> Dict[str, Any]:
        """Return JSON schema for configuration."""
        return MFAConfig.schema()
    
    def get_examples(self) -> List[Dict[str, Any]]:
        """Return example configurations."""
        return [
            {
                "mfa_name": "AinflueMFA",
                "description": "Multi-Factor Authentication for Ainflue creator platform"
            }
        ]
    
    def _generate_mfa_code(self, config: MFAConfig) -> str:
        """Generate the actual MFA code."""
        
        code = f'''"""
{config.mfa_name} Multi-Factor Authentication
Generated by Ainflue MFA Template

{config.description}

🔒 PROTECTION INTELLECTUELLE:
© 2025 Fahed Mlaiel <mlaiel@live.de>
TOUS DROITS RÉSERVÉS
"""

from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass
from enum import Enum
import logging
import secrets
import base64
from datetime import datetime, timedelta
import io

import pyotp
import qrcode
from fastapi import FastAPI, Request, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

import redis.asyncio as redis
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

# MFA Types and Models

class MFAMethod(Enum):
    """MFA method types."""
    TOTP = "totp"
    SMS = "sms"
    EMAIL = "email"
    BACKUP_CODE = "backup_code"

@dataclass
class MFASetupData:
    """MFA setup information."""
    secret: str
    qr_code_url: str
    backup_codes: List[str]
    method: MFAMethod

class MFAVerificationRequest(BaseModel):
    """MFA verification request."""
    user_id: str
    code: str
    method: MFAMethod

class MFASetupRequest(BaseModel):
    """MFA setup request."""
    user_id: str
    method: MFAMethod

# MFA Manager

class MFAManager:
    """Multi-Factor Authentication manager."""
    
    def __init__(self):
        self.redis_client = None
        self.issuer_name = "{config.mfa_config['issuer_name']}"
        self.totp_period = {config.mfa_config['totp_period']}
        self.totp_digits = {config.mfa_config['totp_digits']}
        self.backup_codes_count = {config.mfa_config['backup_codes_count']}
    
    async def connect_redis(self):
        """Connect to Redis."""
        if not self.redis_client:
            self.redis_client = redis.Redis.from_url("redis://localhost:6379")
    
    async def setup_totp(self, user_id: str, username: str) -> MFASetupData:
        """Setup TOTP for user."""
        await self.connect_redis()
        
        # Generate secret
        secret = pyotp.random_base32()
        
        # Create TOTP instance
        totp = pyotp.TOTP(
            secret,
            issuer_name=self.issuer_name,
            digits=self.totp_digits,
            interval=self.totp_period
        )
        
        # Generate QR code URL
        qr_url = totp.provisioning_uri(
            name=username,
            issuer_name=self.issuer_name
        )
        
        # Generate backup codes
        backup_codes = self._generate_backup_codes()
        
        # Store MFA data temporarily (user needs to verify before enabling)
        mfa_data = {{
            "secret": secret,
            "backup_codes": backup_codes,
            "method": MFAMethod.TOTP.value,
            "verified": False,
            "created_at": datetime.now().isoformat()
        }}
        
        await self.redis_client.setex(
            f"mfa_setup:{{user_id}}",
            3600,  # 1 hour to complete setup
            json.dumps(mfa_data)
        )
        
        return MFASetupData(
            secret=secret,
            qr_code_url=qr_url,
            backup_codes=backup_codes,
            method=MFAMethod.TOTP
        )
    
    def _generate_backup_codes(self) -> List[str]:
        """Generate backup codes."""
        codes = []
        for _ in range(self.backup_codes_count):
            code = "".join([str(secrets.randbelow(10)) for _ in range(8)])
            # Format as XXXX-XXXX
            formatted_code = f"{{code[:4]}}-{{code[4:]}}"
            codes.append(formatted_code)
        return codes
    
    async def verify_totp_setup(self, user_id: str, code: str) -> bool:
        """Verify TOTP setup with provided code."""
        await self.connect_redis()
        
        # Get setup data
        setup_data = await self.redis_client.get(f"mfa_setup:{{user_id}}")
        if not setup_data:
            return False
        
        mfa_info = json.loads(setup_data)
        secret = mfa_info["secret"]
        
        # Verify code
        totp = pyotp.TOTP(secret, digits=self.totp_digits, interval=self.totp_period)
        if not totp.verify(code, valid_window=1):
            return False
        
        # Mark as verified and move to permanent storage
        mfa_info["verified"] = True
        await self._store_user_mfa(user_id, mfa_info)
        
        # Clean up temporary setup data
        await self.redis_client.delete(f"mfa_setup:{{user_id}}")
        
        return True
    
    async def verify_totp(self, user_id: str, code: str) -> bool:
        """Verify TOTP code for authentication."""
        await self.connect_redis()
        
        # Get user MFA data
        mfa_data = await self._get_user_mfa(user_id)
        if not mfa_data or mfa_data["method"] != MFAMethod.TOTP.value:
            return False
        
        secret = mfa_data["secret"]
        
        # Check if code was recently used (prevent replay attacks)
        if await self._is_code_recently_used(user_id, code):
            return False
        
        # Verify code
        totp = pyotp.TOTP(secret, digits=self.totp_digits, interval=self.totp_period)
        if not totp.verify(code, valid_window=1):
            return False
        
        # Mark code as used
        await self._mark_code_as_used(user_id, code)
        
        return True
    
    async def verify_backup_code(self, user_id: str, code: str) -> bool:
        """Verify backup code."""
        await self.connect_redis()
        
        # Get user MFA data
        mfa_data = await self._get_user_mfa(user_id)
        if not mfa_data:
            return False
        
        backup_codes = mfa_data.get("backup_codes", [])
        
        # Check if code exists and hasn't been used
        if code not in backup_codes:
            return False
        
        # Remove used backup code
        backup_codes.remove(code)
        mfa_data["backup_codes"] = backup_codes
        
        await self._store_user_mfa(user_id, mfa_data)
        
        return True
    
    async def send_sms_code(self, user_id: str, phone_number: str) -> bool:
        """Send SMS verification code."""
        await self.connect_redis()
        
        # Generate 6-digit code
        code = "".join([str(secrets.randbelow(10)) for _ in range(6)])
        
        # Store code temporarily
        await self.redis_client.setex(
            f"sms_code:{{user_id}}",
            300,  # 5 minutes
            code
        )
        
        # Send SMS (implement with your SMS provider)
        success = await self._send_sms(phone_number, f"Your Ainflue verification code: {{code}}")
        
        return success
    
    async def verify_sms_code(self, user_id: str, code: str) -> bool:
        """Verify SMS code."""
        await self.connect_redis()
        
        stored_code = await self.redis_client.get(f"sms_code:{{user_id}}")
        if not stored_code or stored_code.decode() != code:
            return False
        
        # Remove used code
        await self.redis_client.delete(f"sms_code:{{user_id}}")
        
        return True
    
    async def send_email_code(self, user_id: str, email: str) -> bool:
        """Send email verification code."""
        await self.connect_redis()
        
        # Generate 6-digit code
        code = "".join([str(secrets.randbelow(10)) for _ in range(6)])
        
        # Store code temporarily
        await self.redis_client.setex(
            f"email_code:{{user_id}}",
            600,  # 10 minutes
            code
        )
        
        # Send email (implement with your email provider)
        success = await self._send_email(email, "Ainflue Verification Code", f"Your verification code: {{code}}")
        
        return success
    
    async def verify_email_code(self, user_id: str, code: str) -> bool:
        """Verify email code."""
        await self.connect_redis()
        
        stored_code = await self.redis_client.get(f"email_code:{{user_id}}")
        if not stored_code or stored_code.decode() != code:
            return False
        
        # Remove used code
        await self.redis_client.delete(f"email_code:{{user_id}}")
        
        return True
    
    async def is_mfa_enabled(self, user_id: str) -> bool:
        """Check if MFA is enabled for user."""
        mfa_data = await self._get_user_mfa(user_id)
        return mfa_data is not None and mfa_data.get("verified", False)
    
    async def disable_mfa(self, user_id: str) -> bool:
        """Disable MFA for user."""
        await self.connect_redis()
        
        # Remove MFA data
        result = await self.redis_client.delete(f"user_mfa:{{user_id}}")
        
        return result > 0
    
    async def get_backup_codes(self, user_id: str) -> List[str]:
        """Get remaining backup codes."""
        mfa_data = await self._get_user_mfa(user_id)
        if not mfa_data:
            return []
        
        return mfa_data.get("backup_codes", [])
    
    async def regenerate_backup_codes(self, user_id: str) -> List[str]:
        """Regenerate backup codes."""
        mfa_data = await self._get_user_mfa(user_id)
        if not mfa_data:
            return []
        
        # Generate new backup codes
        new_codes = self._generate_backup_codes()
        mfa_data["backup_codes"] = new_codes
        
        await self._store_user_mfa(user_id, mfa_data)
        
        return new_codes
    
    async def _store_user_mfa(self, user_id: str, mfa_data: Dict[str, Any]):
        """Store user MFA data."""
        await self.connect_redis()
        
        await self.redis_client.set(
            f"user_mfa:{{user_id}}",
            json.dumps(mfa_data, default=str)
        )
    
    async def _get_user_mfa(self, user_id: str) -> Optional[Dict[str, Any]]:
        """Get user MFA data."""
        await self.connect_redis()
        
        data = await self.redis_client.get(f"user_mfa:{{user_id}}")
        if not data:
            return None
        
        return json.loads(data)
    
    async def _is_code_recently_used(self, user_id: str, code: str) -> bool:
        """Check if TOTP code was recently used."""
        await self.connect_redis()
        
        key = f"used_code:{{user_id}}:{{code}}"
        return await self.redis_client.exists(key)
    
    async def _mark_code_as_used(self, user_id: str, code: str):
        """Mark TOTP code as recently used."""
        await self.connect_redis()
        
        key = f"used_code:{{user_id}}:{{code}}"
        await self.redis_client.setex(key, self.totp_period * 2, "used")
    
    async def _send_sms(self, phone: str, message: str) -> bool:
        """Send SMS message."""
        # Implement with your SMS provider (Twilio, AWS SNS, etc.)
        logger.info(f"Sending SMS to {{phone}}: {{message}}")
        return True
    
    async def _send_email(self, email: str, subject: str, body: str) -> bool:
        """Send email message."""
        # Implement with your email provider (SendGrid, AWS SES, etc.)
        logger.info(f"Sending email to {{email}}: {{subject}}")
        return True

# MFA Endpoints

app = FastAPI(title="{config.mfa_name}", version="1.0.0")
mfa_manager = MFAManager()

@app.post("/mfa/setup/totp")
async def setup_totp(
    request: MFASetupRequest,
    db: AsyncSession = Depends(get_db_session)
):
    """Setup TOTP for user."""
    # Get user information
    user = await get_user_by_id(request.user_id, db)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    # Setup TOTP
    setup_data = await mfa_manager.setup_totp(request.user_id, user.username)
    
    return {{
        "secret": setup_data.secret,
        "qr_code_url": "/mfa/qr-code/" + request.user_id,
        "backup_codes": setup_data.backup_codes
    }}

@app.get("/mfa/qr-code/{{user_id}}")
async def get_qr_code(user_id: str):
    """Generate QR code for TOTP setup."""
    # Get setup data
    setup_data_raw = await mfa_manager.redis_client.get(f"mfa_setup:{{user_id}}")
    if not setup_data_raw:
        raise HTTPException(status_code=404, detail="MFA setup not found")
    
    setup_data = json.loads(setup_data_raw)
    secret = setup_data["secret"]
    
    # Generate QR code
    totp = pyotp.TOTP(secret, issuer_name=mfa_manager.issuer_name)
    qr_url = totp.provisioning_uri(name=user_id, issuer_name=mfa_manager.issuer_name)
    
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(qr_url)
    qr.make(fit=True)
    
    img = qr.make_image(fill_color="black", back_color="white")
    
    # Return as image stream
    img_buffer = io.BytesIO()
    img.save(img_buffer, format="PNG")
    img_buffer.seek(0)
    
    return StreamingResponse(img_buffer, media_type="image/png")

@app.post("/mfa/verify/setup")
async def verify_mfa_setup(request: MFAVerificationRequest):
    """Verify MFA setup."""
    success = await mfa_manager.verify_totp_setup(request.user_id, request.code)
    
    if not success:
        raise HTTPException(status_code=400, detail="Invalid verification code")
    
    return {{"message": "MFA setup completed successfully"}}

@app.post("/mfa/verify")
async def verify_mfa(request: MFAVerificationRequest):
    """Verify MFA code."""
    
    if request.method == MFAMethod.TOTP:
        success = await mfa_manager.verify_totp(request.user_id, request.code)
    elif request.method == MFAMethod.BACKUP_CODE:
        success = await mfa_manager.verify_backup_code(request.user_id, request.code)
    elif request.method == MFAMethod.SMS:
        success = await mfa_manager.verify_sms_code(request.user_id, request.code)
    elif request.method == MFAMethod.EMAIL:
        success = await mfa_manager.verify_email_code(request.user_id, request.code)
    else:
        raise HTTPException(status_code=400, detail="Unsupported MFA method")
    
    if not success:
        raise HTTPException(status_code=400, detail="Invalid verification code")
    
    return {{"message": "MFA verification successful"}}

@app.post("/mfa/send-sms")
async def send_sms_code(user_id: str, phone: str):
    """Send SMS verification code."""
    success = await mfa_manager.send_sms_code(user_id, phone)
    
    if not success:
        raise HTTPException(status_code=500, detail="Failed to send SMS")
    
    return {{"message": "SMS code sent successfully"}}

@app.post("/mfa/send-email")
async def send_email_code(user_id: str, email: str):
    """Send email verification code."""
    success = await mfa_manager.send_email_code(user_id, email)
    
    if not success:
        raise HTTPException(status_code=500, detail="Failed to send email")
    
    return {{"message": "Email code sent successfully"}}

@app.delete("/mfa/disable/{{user_id}}")
async def disable_mfa(user_id: str):
    """Disable MFA for user."""
    success = await mfa_manager.disable_mfa(user_id)
    
    if not success:
        raise HTTPException(status_code=404, detail="MFA not found")
    
    return {{"message": "MFA disabled successfully"}}

@app.get("/mfa/backup-codes/{{user_id}}")
async def get_backup_codes(user_id: str):
    """Get remaining backup codes."""
    codes = await mfa_manager.get_backup_codes(user_id)
    return {{"backup_codes": codes}}

@app.post("/mfa/backup-codes/regenerate/{{user_id}}")
async def regenerate_backup_codes(user_id: str):
    """Regenerate backup codes."""
    codes = await mfa_manager.regenerate_backup_codes(user_id)
    return {{"backup_codes": codes}}

# Configuration
MFA_CONFIG = {config.dict()}

if __name__ == "__main__":
    print(f"✅ {config.mfa_name} initialized successfully")
    print(f"📊 MFA statistics:")
    print(f"   - TOTP period: {config.mfa_config['totp_period']}s")
    print(f"   - TOTP digits: {config.mfa_config['totp_digits']}")
    print(f"   - Backup codes: {config.mfa_config['backup_codes_count']}")
    print(f"   - SMS enabled: {config.mfa_config['sms_enabled']}")
'''
        
        return code


# Register template
from .template_registry import register_template

register_template(
    MFATemplate,
    MFATemplate().metadata
)