apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8009'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: analytics-service
    environment: development
    service-type: analytics-service
  name: analytics-service
  namespace: ainflue-development
spec:
  ports:
  - name: http
    port: 8009
    protocol: TCP
    targetPort: 8009
  selector:
    app: analytics-service
  type: ClusterIP
