apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8006'
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: ''
  labels:
    app: authz-service
    environment: development
    service-type: security-service
  name: authz-service
  namespace: ainflue-development
spec:
  ports:
  - name: http
    port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    app: authz-service
  type: ClusterIP
